### ISSUE TITLE
LogAwareInterface is not available

### ISSUE THREAD

**Issue by ghost** [dvdoug/BoxPacker#10]
Hi, I wasn't sure how to contact you otherwise, but I'm trying to implement this in my ci application.

I don't have PSR or PHPUnit and whenI try to use this library I get an error because PHP cant find LogAwareInterface.

I removed the code for the logger and it seems to be ok, I used  require() statements instead of the autoload feature because Im using CI.

Finally, do I have to know how many Boxes to create, or do I just define the box sizes available.

cheers

**Comment by dvdoug** [comment]
Closing for lack of update
