### ISSUE TITLE
Unhandled TypeError on some volume related methods

### ISSUE THREAD

**Issue by PhiSYS** [dvdoug/BoxPacker#118]
https://github.com/dvdoug/BoxPacker/blob/f28361222e9cfd0d85648b37ebdab0d86ad61dbc/src/PackedBox.php#L185
Found that somehow high numbers do overflow the expected strict return integer and then triggers an unhandled _TypeError_ even when those values are valid and not throwing the ItemTooLargeException.

**Comment by dvdoug** [comment]
Hello

Can you give me an example of the size of dimensions you're using? PHP_INT_MAX should be large enough I would have thought? 🤔

**Comment by PhiSYS** [comment]
It's **not a real use case** but something I've found in the tests I've written for our domain logic.
In short, we have a number of receptacles R1...R6 and if a item would not fit in them there's R7 which is defined to be as large as 16777215x16777215x16777215 (which is unreal and means that R7 is elsewhere, be it a pallet, a delimited space on the warehouse floor...)
So, in a _sad path unit test_ I exceeded the dimension 120x50x16777216 with the ItemTooLargeException expectation.

I'm not saying it should return float or something, just that we found that it's unhandled.
`if (!is_int($result)) throw new ItemTooLargeException();`
before return will satisfy the exception expectation in my test.

**Comment by dvdoug** [comment]
Hi @PhiSYS 

I've been thinking about this, and I'm going to close it as a wontfix - you can "pack" items up to 2 kilometres x 2 kilometres x 2 kilometres in size before PHP starts resorting to float maths so I don't this isn't a something that needs to be guarded against for any "normal" usage.

Unless I've misunderstood your usecase, I think it could just be handled by not passing R7 into the algorithm as a possible choice and just falling back to it when you get the ItemTooLargeException from trying R1-R6. That would have the same effect as throwing the exception at the point you've placed it.
