### ISSUE TITLE
Gaps In Packing

### ISSUE THREAD

**Issue by OpenCartAddons** [dvdoug/BoxPacker#124]
First I just want to say this is an excellent system and works well in the majority of cases.  Thanks!

I've experienced a weird quirk though where it kept splitting the items into 2 boxes.  Here's what I was using:

```
Item 1 - 8x8x2
Item 2 - 4x4x4
Item 3 - 4x4x4

Box 1 - 14x11x4
```

Result:  
`Box 1 -> Contents[Item 1, Item 2], Box 2 -> Contents[Item 3]`

The system packs the first 2 items correctly but cannot pack the last item beside item 2 and instead grabs a second box.  When the system calls a new row the packing room left and XYZ are as follows:

```
Packing Room Left
Array
(
    [width] => 14
    [length] => 3
    [depth] => 4
)

Packing XYZ
Array
(
    [x] => 0
    [y] => 8
    [z] => 0
)

```

However by rotating the box dimensions the system correctly packs everything into a single box.

`Box 1 - 4x14x11`

Result:
`Box 1 -> Contents{Item 1, Item 2, Item 3}`

Cheers,
Joel.

**Comment by dvdoug** [comment]
Hello

Thanks for the report. I've built a testcase that confirms this behaviour, and from inspection so far I think I can see where there is potentially opportunity for some improvement that would allow this particular example to be packed better.

I don't think it applies to this testcase but please note that by rotating the dimensions of the box around that the packing will occur along a different face of the box than before and that some orientation decisions will therefore vary as stability is taken into account

**Comment by OpenCartAddons** [comment]
Sorry, I meant to reply sooner.  Thanks for getting back to me!

I did notice that by rotating the dimensions it packed the box correctly.


Cheers,
Joel.
