### ISSUE TITLE
Composer Install

### ISSUE THREAD

**Issue by bitsbybob** [dvdoug/BoxPacker#133]
Trying to install v2.4.4 via composer and keep hitting this error:

Problem 1
    - The requested package dvdoug/boxpacker No version set (parsed as 1.0.0) is satisfiable by dvdoug/boxpacker[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

composer.json looks like:

[composer.json.zip](https://github.com/dvdoug/BoxPacker/files/1782319/composer.json.zip)

**Comment by bitsbybob** [comment]
if I change the composer.json to  "dvdoug/boxpacker": "*" then the dependencies seem to install, but there is no /vendor/dvdoug/boxpacker.

God I hate composer with a passion.  :)

**Comment by dvdoug** [comment]
That .zip file is (mostly) the composer.json for the project itself - if you want to use the code standalone to experiment with e.g. to run the tests, then simply run `composer install` once you've cloned the repo and PHPUnit etc will be installed. You don't need to add BoxPacker itself to the requirements as it's already there.

If you want to use it as part of a different project as a library, then run `composer require dvdoug/boxpacker` from the root directory of the other project.

**Comment by bitsbybob** [comment]
<img width="1038" alt="screen shot 2018-03-05 at 5 26 02 pm" src="https://user-images.githubusercontent.com/3876455/37003217-51b74f44-209a-11e8-92c2-8675e9b054a0.png">

OK - now what?  How do I run the tests?

**Comment by dvdoug** [comment]
`vendor/bin/phpunit`
