### ISSUE TITLE
Not getting items which can fit into the bin

### ISSUE THREAD

**Issue by siraz-dev** [dvdoug/BoxPacker#134]
Hello @dvdoug ,

I am trying to integrate your library. I want to know how can I handle following scenario.

Items with following dimestions

Item1 : 100 X 100 X2
Item2 : 200 X 100 X2

And boxes with following

Box1 :(96 X 96 X 2)
Box2 :(196 X 196 X 8)

Now If I want to place above items into the Boxes as per defined parameters, I am getting error ItemTooLargeException for Item 2 and not able to know  in which box I can place the Item 1.

Thanks,
Siraz

**Comment by dvdoug** [comment]
Hello

If you start with the example from http://www.boxpacker.io/en/stable/getting-started.html and adjust from there you should be able to get it working. If not, could I see your sample code?

**Comment by siraz-dev** [comment]
<?php

//namespace DVDoug\BoxPacker;


//echo __DIR__ . '/vendor/autoload.php';exit;

require_once __DIR__ . '/vendor/autoload.php';

require_once "C:\\xampp\\htdocs\\rnd\\BoxPacker-master\\vendor\\phpunit\\phpunit\\tests\\bootstrap.php";

use DVDoug\BoxPacker\ItemTooLargeException;
use DVDoug\BoxPacker\Packer;
use DVDoug\BoxPacker\Test\TestBox;
use DVDoug\BoxPacker\Test\TestItem;


             



 
        $packer = new Packer();

        $packer->addBox(new TestBox('Le petite box', 300, 300, 10, 10, 296, 296, 8, 1000));
        $packer->addBox(new TestBox('Le grande box', 3000, 3000, 100, 100, 2960, 2960, 80, 10000));

        $packer->addItem(new TestItem('Item 1', 2500, 2500, 20, 2000, true));
        $packer->addItem(new TestItem('Item 2', 25000, 2500, 20, 2000, true));
        $packer->addItem(new TestItem('Item 3', 2500, 2500, 20, 2000, true));

        $packedBoxes = $packer->pack();
        
   
    echo "These items fitted into " . count($packedBoxes) . " box(es)" . PHP_EOL;
    foreach ($packedBoxes as $packedBox) {
        $boxType = $packedBox->getBox(); // your own box object, in this case TestBox
        echo "This box is a {$boxType->getReference()}, it is {$boxType->getOuterWidth()}mm wide, {$boxType->getOuterLength()}mm long and {$boxType->getOuterDepth()}mm high" . PHP_EOL;
        echo "The combined weight of this box and the items inside it is {$packedBox->getWeight()}g" . PHP_EOL;

        echo "The items in this box are:" . PHP_EOL;
        $packedItems = $packedBox->getItems();
        foreach ($packedItems as $packedItem) { // $packedItem->getItem() is your own item object, in this case TestItem
         //echo $packedItem->getDescription() . PHP_EOL;
            
           //print_r( $packedItem->getItem()) ;
           
            echo $packedItem->getItem()->getDescription() . PHP_EOL;
        }
    }
     
     
    Result : 


Fatal error: Uncaught DVDoug\BoxPacker\ItemTooLargeException: Item Item 2 is too large to fit into any box in C:\xampp\htdocs\rnd\BoxPacker-master\src\Packer.php:203 Stack trace: #0 C:\xampp\htdocs\rnd\BoxPacker-master\src\Packer.php(181): DVDoug\BoxPacker\Packer->findBestBoxFromIteration(Array) #1 C:\xampp\htdocs\rnd\BoxPacker-master\src\Packer.php(136): DVDoug\BoxPacker\Packer->doVolumePacking() #2 C:\xampp\htdocs\rnd\BoxPacker-master\demo_backup.php(32): DVDoug\BoxPacker\Packer->pack() #3 {main} thrown in C:\xampp\htdocs\rnd\BoxPacker-master\src\Packer.php on line 203

**Comment by siraz-dev** [comment]
`<?php

//namespace DVDoug\BoxPacker;


//echo __DIR__ . '/vendor/autoload.php';exit;

require_once __DIR__ . '/vendor/autoload.php';

require_once "C:\\xampp\\htdocs\\rnd\\BoxPacker-master\\vendor\\phpunit\\phpunit\\tests\\bootstrap.php";

use DVDoug\BoxPacker\ItemTooLargeException;
use DVDoug\BoxPacker\Packer;
use DVDoug\BoxPacker\Test\TestBox;
use DVDoug\BoxPacker\Test\TestItem;


             



 
        $packer = new Packer();

        $packer->addBox(new TestBox('Le petite box', 300, 300, 10, 10, 296, 296, 8, 1000));
        $packer->addBox(new TestBox('Le grande box', 3000, 3000, 100, 100, 2960, 2960, 80, 10000));

        $packer->addItem(new TestItem('Item 1', 2500, 2500, 20, 2000, true));
        $packer->addItem(new TestItem('Item 2', 25000, 2500, 20, 2000, true));
        $packer->addItem(new TestItem('Item 3', 2500, 2500, 20, 2000, true));

        $packedBoxes = $packer->pack();
        
   
    echo "These items fitted into " . count($packedBoxes) . " box(es)" . PHP_EOL;
    foreach ($packedBoxes as $packedBox) {
        $boxType = $packedBox->getBox(); // your own box object, in this case TestBox
        echo "This box is a {$boxType->getReference()}, it is {$boxType->getOuterWidth()}mm wide, {$boxType->getOuterLength()}mm long and {$boxType->getOuterDepth()}mm high" . PHP_EOL;
        echo "The combined weight of this box and the items inside it is {$packedBox->getWeight()}g" . PHP_EOL;

        echo "The items in this box are:" . PHP_EOL;
        $packedItems = $packedBox->getItems();
        foreach ($packedItems as $packedItem) { // $packedItem->getItem() is your own item object, in this case TestItem
         //echo $packedItem->getDescription() . PHP_EOL;
            
           //print_r( $packedItem->getItem()) ;
           
            echo $packedItem->getItem()->getDescription() . PHP_EOL;
        }
    }
     
     
    `

**Comment by siraz-dev** [comment]
Here is the output

`
Fatal error: Uncaught DVDoug\BoxPacker\ItemTooLargeException: Item Item 2 is too large to fit into any box in C:\xampp\htdocs\rnd\BoxPacker-master\src\Packer.php:203 Stack trace: #0 C:\xampp\htdocs\rnd\BoxPacker-master\src\Packer.php(181): DVDoug\BoxPacker\Packer->findBestBoxFromIteration(Array) #1 C:\xampp\htdocs\rnd\BoxPacker-master\src\Packer.php(136): DVDoug\BoxPacker\Packer->doVolumePacking() #2 C:\xampp\htdocs\rnd\BoxPacker-master\demo_backup.php(32): DVDoug\BoxPacker\Packer->pack() #3 {main} thrown in C:\xampp\htdocs\rnd\BoxPacker-master\src\Packer.php on line 203`

**Comment by siraz-dev** [comment]
@dvdoug , If any item cannot fit into available box Then It should display rest of items with boxes in which they can fit. Please let me know how can I do that?

**Comment by dvdoug** [comment]
Ah, OK I get you - sorry I misread your initial example and was thinking that both items should fit into a box. You actually do have an item too large.

The 2nd half of http://www.boxpacker.io/en/stable/too-large-items.html should help

**Comment by siraz-dev** [comment]
@dvdoug , Thanks for reply.  Is there any method where I can generate visual result ?

**Comment by siraz-dev** [comment]
@dvdoug , As Boxpacker always give us x,y,z coordinate values as 0,0,0 to place single item in box. When I pass same values to http://www.packit4me.com api its not properly placing item into box. Can you please guide me for same?

**Comment by siraz-dev** [comment]
@dvdoug , It would be great help if you have integrated  Visual representation like http://www.packit4me.com/api/call/preview. Please share if you have done some progress in that direction.

**Comment by siraz-dev** [comment]
@dvdoug , Do you have created any visual presentation ?

**Comment by dvdoug** [comment]
Hello

No, this is intended to be a pure PHP library, and any visualisations would be better done in something like WebGL. However the raw data is output so that you could feed the co-ordinates into your own visualiser if desired.

What is your issue with using 0,0,0 as co-ordinates for the first(only) item in a box?

**Comment by siraz-dev** [comment]
Hello,

@dvdoug , I am using http://www.packit4me.com/ for visualization 
Issue is that it's not displaying the item as they have different algorighm to calculate coordinates.

If you can suggest me any other WebGL, which can utilizate the result which your library is generate would be great help.

Thanks,
Siraz

**Comment by siraz-dev** [comment]
@dvdoug 

I am using following code to get best fit box for the items & i am getting wrong box (Box 1) . Can you please let me know how my items are getting fix in that box??



    $width = 20;
    $outerwidth = $width  + 4;
    $height = 10;
    $outerheight = $height + 2;
    $len = 26;
    $outerlen = $len + 4;
    $minweight = 0; // As per understanding empty box weight is Zero
    $maxweight = ($width * $len * $height)/ 139;

    $packer->addBox(new TestBox('BOX 1', $outerwidth, $outerlen, $outerheight, $minweight, $width, $len, $height, $maxweight));
    //$packer->addBox(new TestBox('BOX 1', 24, 30, 12, 0, 20, 26, 10, 44.89));
    $packer->addBox(new TestBox('BOX 2', 20, 40, 7, 0, 16, 36, 5, 20.72));
 

    /*
     * Add items to be packed - e.g. from shopping cart stored in user session. Again, the dimensional information
     * (and keep-flat requirement) would normally come from a DB
     */
    $packer->addItem(new TestItem('Item 1', 5.4, 2.8, 3.3, 1.6, false));
    $packer->addItem(new TestItem('Item 2', 16.2, 17, 4.9, 8.4, false));
    $packer->addItem(new TestItem('Item 3', 16.1, 17, 4.9, 8.3, false));

Please let me know what is wrong in above code?

**Comment by dvdoug** [comment]
I'm not used any WebGL libraries myself, so can't give a recommendation. Sorry.

Why do you think Box 1 is wrong? Box 1 fits all 3 items, Items 2 and 3 don't even fit into box 2 given the dimensions you've supplied (box inner width of 16, vs item width of 16.1/16.2)

**Comment by siraz-dev** [comment]
@dvdoug , Thanks for reply. I want to know then why below program give me following out put.

"These items fitted into 1 box(es) This box is a BOX 1, it is 16mm wide, 36mm long and 5mm high The combined weight of this box and the items inside it is 17g The items in this box are: Item 2Item 3Item 1".

It should fit only Item 1 .

Please clear my doubt.

================================================================

$width = 16.0;
    $outerwidth = $width  + 4;
    $height = 5.0;
    $outerheight = $height + 2;
    $len = 36.0;
    $outerlen = $len + 4;
    $minweight = 0; // As per understanding empty box weight is Zero
       
    $maxweight = 1000;

    $packer->addBox(new TestBox('BOX 1', $width, $len, $height, $minweight, $width, $len, $height, $maxweight)); 

  
   $packer->addItem(new TestItem('Item 1', 5.4, 2.8, 3.3, 1.6, true));
    $packer->addItem(new TestItem('Item 2', 16.2, 17, 4.9, 8.4, true));
    $packer->addItem(new TestItem('Item 3', 16.1, 17, 4.9, 8.3, true)); 

Thanks,
Siraz

**Comment by dvdoug** [comment]
http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict

Best practice is to have this turned on, it sounds like you might have it turned off

**Comment by dvdoug** [comment]
Nothing to do here - closing
