### ISSUE TITLE
Units of Width, Lenght , Height & Weight

### ISSUE THREAD

**Issue by siraz-dev** [dvdoug/BoxPacker#135]
@dvdoug , can you please let me know Units of Width, Length , Height & Weight?

**Comment by corbinu** [comment]
@siraz-dev 

You just use the same unit for everything. As far as the math/packer is concerned they are meaningless. What ever you input that’s what you get out

**Comment by siraz-dev** [comment]
@corbinu Thank you very much

**Comment by dvdoug** [comment]
They are nominally set as mm/g but as @corbinu says they're just numbers so as long as you're consistent between items and boxes you can use a different unit if you wish

**Comment by siraz-dev** [comment]
Hello @corbinu ,

I have one box with following dimension

36x10x10 (LxWxH)

I have created box for this using following code .

$packer->addBox(new TestBox('BOX 7', 10, 36, 10, 26, 10, 36, 10, 26));

AND Items with following dimenstion.

27.56 x 7.99 x 7.99 (LxWxH)

$packer->addItem(new TestItem('Item 1', 7.99, 27.56, 7.99, 25.90, false));

May I know the reason why this item not fit into the above box.

Thanks,
Siraz

**Comment by siraz-dev** [comment]
Hello @Garbee @TravisBernard @acabala ,

I have one box with following dimension

36x10x10 (LxWxH)

I have created box for this using following code .

$packer->addBox(new TestBox('BOX 7', 10, 36, 10, 26, 10, 36, 10, 26));

AND Items with following dimenstion.

27.56 x 7.99 x 7.99 (LxWxH)

$packer->addItem(new TestItem('Item 1', 7.99, 27.56, 7.99, 25.90, false));

May I know the reason why this item not fit into the above box.

Thanks,
Siraz

**Comment by corbinu** [comment]
@siraz-dev Please don't spam people with a question you have already opened an issue for. Thanks!

**Comment by siraz-dev** [comment]
@corbinu , Ok.
