### ISSUE TITLE
Truck Loading List

### ISSUE THREAD

**Issue by mindwarpomsg** [dvdoug/BoxPacker#138]
First of all I want to say that this package is epic. Thanks so much for this.

I'm trying to implement BoxPacker as a truck loader, maximizing space but also keeping items from the same order together. I've created a TruckItem class that adds the ordernumber variable and am able to read it back out from the packed list.

From there I'm trying to extend the volume packing class, specifically the packlayer function to check if the item is in the same order and if not, skip for now. I'm having no luck. My current code looks like this:

`class TruckOrderPacker extends VolumePacker
{
    use LoggerAwareTrait;
    protected $items;
    protected $box;

    public function __construct(Box $box, ItemList $items)
    {
        parent::__construct($box, $items);
    }
    protected function packLayer(int $startDepth, int $widthLeft, int $lengthLeft, int $depthLeft): void
    {
        while (count($this->items) > 0) {
			for($currentorder = 0; $currentorder < 100; $currentorder++)
			{
				$itemToPack = $this->items->extract();
				$nextItem = $this->getNextItem();
				if(!empty($nextItem)) {
					if($currentorder <> $nextItem->getOrderNumber()) {
						$this->rebuildItemList();
						continue;
					}
				parent::packLayer($startDepth, $widthLeft, $lengthLeft, $depthLeft);
				}
			}
		}
	}
}
`
and in my TruckPacker class (identical to Packer except that I call TruckOrderPacker instead of VolumePacker)

`    public function doVolumePacking(): PackedBoxList
    {
        $packedBoxes = new PackedBoxList();

        //Keep going until everything packed
        while ($this->items->count()) {
            $packedBoxesIteration = [];

            //Loop through boxes starting with smallest, see what happens
            foreach ($this->boxes as $box) {
                $truckOrderPacker = new TruckOrderPacker($box, clone $this->items);
                $truckOrderPacker->setLogger($this->logger);
                $packedBox = $truckOrderPacker->pack();
                if ($packedBox->getItems()->count()) {
                    $packedBoxesIteration[] = $packedBox;

                    //Have we found a single box that contains everything?
                    if ($packedBox->getItems()->count() === $this->items->count()) {
                        break;
                    }
                }
            }

            //Find best box of iteration, and remove packed items from unpacked list
            $bestBox = $this->findBestBoxFromIteration($packedBoxesIteration);

            /** @var PackedItem $packedItem */
            foreach ($bestBox->getItems() as $packedItem) {
                $this->items->remove($packedItem->getItem());
            }

            $packedBoxes->insert($bestBox);
        }

        return $packedBoxes;
    }
    private function findBestBoxFromIteration($packedBoxes): PackedBox
    {
        //Check iteration was productive
        if (count($packedBoxes) === 0) {
            throw new ItemTooLargeException('Item '.$this->items->top()->getDescription().' is too large to fit into any box', $this->items->top());
        }

        usort($packedBoxes, [$this, 'compare']);

        return array_shift($packedBoxes);
    }
    private static function compare(PackedBox $boxA, PackedBox $boxB): int
    {
        $choice = $boxB->getItems()->count() <=> $boxA->getItems()->count();
        if ($choice === 0) {
            $choice = $boxA->getInnerVolume() <=> $boxB->getInnerVolume();
        }
        if ($choice === 0) {
            $choice = $boxA->getWeight() <=> $boxB->getWeight();
        }

        return $choice;
    }
}
`

I'm getting the following error when running: PHP Fatal error:  Uncaught TypeError: Return value of DVDoug\BoxPacker\ItemList::extract() must implement interface DVDoug\BoxPacker\Item, null returned in /var/www/html/ship.systems/api/vendor/dvdoug/boxpacker/src/ItemList.php:86

To be honest, I'm not even sure I'm going about this the right way... Basically I'm trying to prioritize keeping items together over maximizing space, but still want to best pack the items within that constraint.

Any ideas?

**Comment by Greg0** [comment]
Try to remove declaration of
```
protected $items;
protected $box;
```
in `TruckOrderPacker`. There are already declared in `VolumePacker`

**Comment by mindwarpomsg** [comment]
Resolved! I was missing a closing brace in one of the if statements in doVolumePacking().

Newbie error. Still not getting the results I was expecting, but at least it's returning something now.

**Comment by dvdoug** [comment]
Oh, awesome. Good to hear!

I think you're going to have a problem where by skipping items because order numbers don't match you're going to end up packing things in a relatively inefficient order - e.g. large item from order 1, small item from order 1, large item from order 2, small item from order 2.

You might(?) get better results with a 2 or 3 phase approach - something like this:
 * iterate over orders, summing up the volume of each item until you exceed the capacity of the truck (quick and dirty approximation of possible item list)
 * use the regular packer to pack these items into the truck
 * optional, if some don't fit, remove all items from that order and repack

**Comment by mindwarpomsg** [comment]
Hi dvdoug!

Regarding the efficiency of packing a truck, you're absolutely right, but it's a trade off in efficiency. When delivering orders, trucks are loaded in a Last In, First Out basis so that when the truck arrives at destination 1, all the items are accessible without moving others, then same at destination 2, 3, etc. If not loaded this way, then they need to unload items to get to the ones being delivered, then reload them before continuing to the next destination.

While I was able to get the error resolved, I'm not getting the results I was hoping for and I'm not sure where I should be intervening in the packing order. 

I've attached the code that I'm using to try to make it work, but the general logic is this:
Load order 1 as efficiently as possible
With the remaining space, load order 2 as efficiently as possible
Repeat for all orders.

The extended version of this would then allow for load balancing between trucks, but always keeping complete orders together on one truck.

Right now, when I visualize my order (using ThreeJS) with orders differentiated by colour, I'm getting this:

![truckpacker](https://user-images.githubusercontent.com/33350512/41180403-2c5d9234-6b3c-11e8-85f6-b83ff9452720.PNG)

Now, the easiest way to do this would be to pretend each order is packed into it's own truck, then take the used volume and insert that into a new truck. While this would work, it's going to leave gaps in the stacks and layers that are unused.

Ideally, once the first order is loaded, the second order should be able to be packed on top of or beside it without wasting the volume.

I thought I had figured it out with the compare() function in the ItemList (now TruckItemList) by adding an order number check, but it doesn't seem to be making much of a difference.

Any thoughts?

[TruckPacker.zip](https://github.com/dvdoug/BoxPacker/files/2086034/TruckPacker.zip)

**Comment by dvdoug** [comment]
Ah I see - that makes sense as a logistical requirement. Will give it some thought

**Comment by mindwarpomsg** [comment]
I've made some progress.  I originally started by creating new TruckItem and TruckItemList exdended classes, but soon found I was running into compatibility errors with the interfaces and getting fatal errors when BoxPacker tried to load functions from the parents.  To test my hypothesis, I duplicated the BoxPacker install into a new directory and started making changes directly to the originals.

![image](https://user-images.githubusercontent.com/33350512/41538448-6c8d0ab6-72d9-11e8-9561-59e16d908db3.png)

Now I've gotten the orders to almost pack correctly, but i'm still getting some items (smaller ones) being stacked out of order.

I think it's happening in the tryAndStackItemsIntoSpace function, but I haven't been able to solve it yet.

Here are the changes I've made:

VolumPacker:
 - Construct:  Do not rotate box
 - packLayer loop: add check:
`if($prevItem <> null && $prevItem->getOrderNumber() <> $itemToPack->getOrderNumber()) {
		$this->rebuildItemList($itemToPack);
                $prevItem = null;
                continue;
}`
- tryAndStackItemsIntoSpace: add check: 
`if($prevItem <> null && $prevItem->getOrderNumber() <> $itemToPack->getOrderNumber()) {
		$this->rebuildItemList($itemToPack);
                $prevItem = null;
                continue;
}`

- ItemList: Always sort, remove isSorted check
- ItemList: Add order check to compare
`		$orderDecider = $itemB->getOrderNumber() <=> $itemA->getOrderNumber();
		if($orderDecider !== 0 && !empty($orderDecider)) {
			return $orderDecider; }`

- TestItem: Add getOrderNumber function & variables:
`    public function getOrderNumber(): int
    {
        return $this->ordernumber;
    }`

I feel like I'm getting close. To consider this working, all that's left is to not allow packing of items from another order until the previous one is fully packed. Right now it seems to be doing that until the current order won't fit into the available space, then it grabs the next available box that will, whether it's the same order or not.

Also, I had noticed in the regular boxpacker, but more evidently here: When a layer is packed, there are gaps left behind it if the previous layer had unequal sized boxes. 
![image](https://user-images.githubusercontent.com/33350512/41540393-2f74c6e6-72de-11e8-8eeb-ad0471386f5e.png)
In the circled examples, the next layer could have been pushed back partially, allowing for denser packing. Not sure if this is something on your to do list or if it's beyond the scope of this project.

**Comment by dvdoug** [comment]
I'll try and take a look this weekend at the keeping-items-from-the-same-order-together part.

The "gap" issue can happen with some packing loads - in most cases it's prevented by the pre-sorting of items to pack the larger/deeper items first - then the next smaller items are placed alongside targeting that depth.

When they happen though, it's definitely not an efficient use of space and eliminating them is on my todo list. It requires some reworking of the current data structures used though so needs to be done carefully
