### ISSUE TITLE
v 3.1.1 Undefined Property

### ISSUE THREAD

**Issue by jhox616** [dvdoug/BoxPacker#140]
I upgraded to version 3.1.1 and got the following error. Is there something I can do on my end to define the property?

Notice: Undefined property: DVDoug\BoxPacker\PackedItem::$getItem in C:\xampp\htdocs\WIP\secure_login\cart\3dbinpack\boxpackertest.php on line 57

Fatal error: Uncaught Error: Call to a member function getDescription() on null in C:\xampp\htdocs\WIP\secure_login\cart\3dbinpack\boxpackertest.php:57 Stack trace: #0 {main} thrown in C:\xampp\htdocs\WIP\secure_login\cart\3dbinpack\boxpackertest.php on line 57

**Comment by UCIS** [comment]
This appears to be an error in [the documentation](http://boxpacker.readthedocs.io/en/stable/getting-started.html). getItem is a method, not a property. Simply changing getItem to getItem() fixed it for me.

**Comment by dvdoug** [comment]
@UCIS you're correct, looks like a there's a typo. I'll get that fixed...
