### ISSUE TITLE
Infinite Recursion When Comparing Item Equality

### ISSUE THREAD

**Issue by gazugafan** [dvdoug/BoxPacker#142]
Because of the way PHP compares objects, it's possible to hit an infinite recursion error at the following line...
https://github.com/dvdoug/BoxPacker/blob/61504618697a535ae1db20c7476896b79806619b/src/OrientatedItemFactory.php#L128

The error you would get is "Nesting level too deep - recursive dependency?". I'm running into this right now on PHP 5.6 with BoxPacker 2, at least. Check out the following comment in the PHP docs...
http://php.net/manual/en/language.oop5.object-comparison.php#71623

I can workaround the problem by skipping this check, or customizing how the comparison is performed. I'm not sure how important this bit is, but maybe it would make sense to make the comparison optional? Or maybe it would make sense to make the comparison customizable? Like adding a compareWith($otherItem) method to the Item interface?

**Comment by gazugafan** [comment]
Yeah, super annoying :(

My first thought was that PHP must have a magic __compare() method or something for this, but no such luck. Looking forward to the fix, though! Any chance you can backport it to v2?

**Comment by dvdoug** [comment]
Yeah, this will be in 2.x - will tag a new version shortly
