### ISSUE TITLE
Problem with getX() , getY() and getZ()

### ISSUE THREAD

**Issue by slobcat1337** [dvdoug/BoxPacker#146]
Hi, 
Thanks a lot for making this open source, it's a great project. 

I just cant seem to get the position data from a packed item. I've tried your example from the documentation after packing and can get length/width etc but the getX() getY() and getZ() methods arent working for me. (i am a n00b btw so apologies)

I'm pretty sure my item object is wrong (i just used your testItem example) but i'm not sure what to do to inherit these methods from the PackedItem class. 

I would really apprecaite it if you could provide me with an example of what my item object should look like that would allow me to retrieve the positioning data. 

Thanks in advance

**Comment by slobcat1337** [comment]
Okay i managed to get the x/y/z values (albeit probably the wrong way) and i'm rendering the coordinates using three.js and certain boxes are actually intersecting. 

Is this because the positioning functionality isnt properly implemented until version 3?

**Comment by dvdoug** [comment]
x/y/z aren't officially exposed in v2, as that would require changing the interface. The core algorithm is the same between versions though so if you've got hold of them by extending a class/poking around at the internals I would expect them to be the same as v3 would give.

If you think you've found an example where things overlap, I'd love to see a testcase.

**Comment by slobcat1337** [comment]
Yeah i did some poking. I changed the PackedItem class and just added the following to the constructor: 
	     
                $this->item->x=$x;
		$this->item->y=$y;
		$this->item->z=$z;

The test case is as follows:

  $packer->addBox(new DVDoug\BoxPacker\TestBox('Pallet', 120, 100, 160, 0, 120, 100, 160, 50000));
	   for ($i=0;$i<9;$i++){
		 
			 $packer->addItem(new DVDoug\BoxPacker\TestItem("Test2", 40, 24, 10, 10, true));
		  
	  }

Screenshot:
![intersect](https://user-images.githubusercontent.com/39516454/41763575-7a70d2d2-75f6-11e8-864c-6b416df41238.png)

**Comment by dvdoug** [comment]
I don't have a visualizer, but the numbers I get from running v3 on your test don't quite line up with what you're pulling out of v2 - I don't have anything that matches "64" or "80".

I assume there's a good reason you're running v2 not v3 (needing PHP 5 compatibility?) If so, it might be easier for you to start with v3 and remove the typehints rather than start with v2.

```
{
  "boxes": [
    {
      "reference": "Pallet",
      "description": "Pallet",
      "width": 120,
      "length": 100,
      "depth": 160,
      "items": [
        {
          "reference": "Test 2",
          "description": "Test 2",
          "position": {
            "x": 0,
            "y": 0,
            "z": 0
          },
          "orientation": {
            "width": 40,
            "length": 24,
            "depth": 10
          }
        },
        {
          "reference": "Test 2",
          "description": "Test 2",
          "position": {
            "x": 0,
            "y": 24,
            "z": 0
          },
          "orientation": {
            "width": 40,
            "length": 24,
            "depth": 10
          }
        },
        {
          "reference": "Test 2",
          "description": "Test 2",
          "position": {
            "x": 0,
            "y": 48,
            "z": 0
          },
          "orientation": {
            "width": 40,
            "length": 24,
            "depth": 10
          }
        },
        {
          "reference": "Test 2",
          "description": "Test 2",
          "position": {
            "x": 0,
            "y": 72,
            "z": 0
          },
          "orientation": {
            "width": 40,
            "length": 24,
            "depth": 10
          }
        },
        {
          "reference": "Test 2",
          "description": "Test 2",
          "position": {
            "x": 0,
            "y": 96,
            "z": 0
          },
          "orientation": {
            "width": 40,
            "length": 24,
            "depth": 10
          }
        },
        {
          "reference": "Test 2",
          "description": "Test 2",
          "position": {
            "x": 0,
            "y": 120,
            "z": 0
          },
          "orientation": {
            "width": 40,
            "length": 24,
            "depth": 10
          }
        },
        {
          "reference": "Test 2",
          "description": "Test 2",
          "position": {
            "x": 40,
            "y": 0,
            "z": 0
          },
          "orientation": {
            "width": 40,
            "length": 24,
            "depth": 10
          }
        },
        {
          "reference": "Test 2",
          "description": "Test 2",
          "position": {
            "x": 40,
            "y": 24,
            "z": 0
          },
          "orientation": {
            "width": 40,
            "length": 24,
            "depth": 10
          }
        },
        {
          "reference": "Test 2",
          "description": "Test 2",
          "position": {
            "x": 40,
            "y": 48,
            "z": 0
          },
          "orientation": {
            "width": 40,
            "length": 24,
            "depth": 10
          }
        }
      ]
    }
  ]
}
```

**Comment by slobcat1337** [comment]
I'm actually running 7.0. Is that all that needs changing, The type hints? 

When i tried to use V3 previously there were also errors with "?" before

**Comment by slobcat1337** [comment]
I'm actually running 7.0

I will give V3 another try though, is it just the type hints that need to be removed?

**Comment by slobcat1337** [comment]
I got it working!
