### ISSUE TITLE
VolumePacker issue

### ISSUE THREAD

**Issue by JanCusters** [dvdoug/BoxPacker#147]
Hi,

I have an issue with the VolumePacker. I'm using version 2.4.6.
I construct a box with the following parameters:

- reference: "TEST"
- outerWidth: 250
- outerLength: 1360
- outerDepth: 260
- emptyWeight: 0
- innerWidth: 250
- innerLength: 1360
- innerDepth: 260
- maxWeight: 30000 

Then I create a new ItemList and insert 14 packages into the ItemList, one by one, with the following parameters. (they are all the same)
- width: 90
- length: 200
- depth: 200
- weight: 150
- keepFlat: TRUE

Then I create a new VolumePacker and call the pack method on it to check if all the items fit.

Now when I count the packed items there are only 12, but there should be 14?

  #remainingWidth: 70
  #remainingLength: 160
  #remainingDepth: 60
  #usedWidth: 180
  #usedLength: 1200
  #usedDepth: 200

I can't figure out what I'm doing wrong here :/

**Comment by dvdoug** [comment]
Hello

Sorry for not responding sooner.

Just to check your expectation here - is that you're expecting to fit all 14 items into a single box? Or that you'd be happy if you were told it's 2 boxes, but can't figure out how you'd know it was 2 rather than 1.

**Comment by JanCusters** [comment]
Hi, thanks for replying. I was expecting all 14 items to fit in in a single box indeed.

**Comment by JanCusters** [comment]
@dvdoug Any update on this?

**Comment by fbeke** [comment]
Hi @dvdoug, any news on this, please? 
I experience similar problems, the items are packed into bigger boxes, than necessary.
If i can help somehow with this, just let me know, please!
Thanks!

**Comment by dvdoug** [comment]
Hello

Still working on this I'm afraid! If you could give me a testcase, I'd be happy to confirm if your issue is indeed this bug or perhaps something else entirely

**Comment by fbeke** [comment]
Hi Dough,
thanks for your reply, also for your great work!

Here is a test case, keep flat is false:

Boxes:
1. 400/100/500, max load 10000g
2. 400/200/500, max load 10000g

2 items to pack:
1. 447/303/62, 965g
2. 495/308/70, 1018g

it packed the items into 2 boxes nr. 1 (1 item in each box), even though it should fit into 1 box nr. 2

Thanks!
