### ISSUE TITLE
Packing Problem 

### ISSUE THREAD

**Issue by nakbill** [dvdoug/BoxPacker#148]
Packing Problem 

Hi 
I am trying your implementation and i am facing the following problem. I set a box
$packer->addBox(new TestBox('Box1',27, 37, 22, 100, 25, 36, 21, 15000));

and try to pack the following items

    $packer->addItem(new TestItem('Item 1', 6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 2', 6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 3', 6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 4', 6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 5', 6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 6', 6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 7', 6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 8', 6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 9', 6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 10',6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 11',6, 12, 20, 10, false));
    $packer->addItem(new TestItem('Item 12', 12, 6, 20, 10, false));
	
In this implementation the result is that the items fitted into two boxes. 
I tested again this case setting the keepflat to true and re-run the algorithm.
    $packer->addItem(new TestItem('Item 1', 6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 2', 6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 3', 6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 4', 6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 5', 6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 6', 6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 7', 6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 8', 6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 9', 6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 10',6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 11',6, 12, 20, 10, true));
    $packer->addItem(new TestItem('Item 12', 12, 6, 20, 10, true));
The result is that the items fitted into one box.
So i believe that  the result in the first case  must have been the same
Items fitted into one box

**Comment by dvdoug** [comment]
Thanks for the bug report!
