### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by nakbill** [dvdoug/BoxPacker#150]
Hi again i just notices some additional bugs i will try to explain in details

I have one main box 

    use DVDoug\BoxPacker\Packer;
    use DVDoug\BoxPacker\Test\TestBox;  
    use DVDoug\BoxPacker\Test\TestItem; 

    $packer->addBox(new TestBox('Le petite box',37, 45, 25, 100, 35, 42, 21, 15000));

	
	/********Case 1*************/
	//In this box i am trying to insert 28 items setting the keep flag to false
 
    for($i=0; $i<28; $i++){

        $packer->addItem(new TestItem('Item '.$i, 7.5, 6, 18.5, 10, false));
    }

	
	//Disable the weight distribution pass completely
    $packer->setMaxBoxesToBalanceWeight(0);
    $packedBoxes = $packer->pack();
	//and Print out the results

	 echo "These items fitted into " . count($packedBoxes) . " box(es)" . PHP_EOL;
    foreach ($packedBoxes as $packedBox) {
        $boxType = $packedBox->getBox(); // your own box object, in this case TestBox

        echo "<br/>Inner Dimension for {$boxType->getReference()}, it is {$boxType->getInnerWidth()}mm wide, {$boxType->getInnerLength()}mm long and {$boxType->getInnerDepth()}mm high" . PHP_EOL;
        echo "<br/>Used Dimension for {$boxType->getReference()}, it is {$packedBox->getUsedWidth()}mm wide, {$packedBox->getUsedlength()}mm long and {$packedBox->getUsedDepth()}mm high" . PHP_EOL;
        echo "<br/>Used Volume  {$packedBox->getInnerVolume()}" . PHP_EOL;
        echo "<br/>Used Volume  {$packedBox->getUsedVolume()}" . PHP_EOL;

        echo "<br/>The combined weight of this box and the items inside it is {$packedBox->getWeight()}g" . PHP_EOL;

    }
	
	/***PRINT OUT THE RESUTLS OF CASE 1**/
	These items fitted into 2 box(es) 
	Inner Dimension for Le petite box, it is 35mm wide, 42mm long and 21mm high 
	Used Dimension for Le petite box, it is 34.5mm wide, 42mm long and 18.5mm high 
	Used Volume 30870 
	Used Volume 21645 
	The combined weight of this box and the items inside it is 360g 
	Inner Dimension for Le petite box, it is 35mm wide, 42mm long and 21mm high 
	Used Dimension for Le petite box, it is 7.5mm wide, 37mm long and 6mm high 
	Used Volume 30870 
	Used Volume 1665 
	The combined weight of this box and the items inside it is 120g
	/*****************************/ 
	
	/********Case 2**************/
	/*****set keep flat to true*/
	for($i=0; $i<28; $i++){

        $packer->addItem(new TestItem('Item '.$i, 7.5, 6, 18.5, 10, true));
    }
	//Disable the weight distribution pass completely
    $packer->setMaxBoxesToBalanceWeight(0);
    $packedBoxes = $packer->pack();
	//and Print out the results

	 echo "These items fitted into " . count($packedBoxes) . " box(es)" . PHP_EOL;
    foreach ($packedBoxes as $packedBox) {
        $boxType = $packedBox->getBox(); // your own box object, in this case TestBox

        echo "<br/>Inner Dimension for {$boxType->getReference()}, it is {$boxType->getInnerWidth()}mm wide, {$boxType->getInnerLength()}mm long and {$boxType->getInnerDepth()}mm high" . PHP_EOL;
        echo "<br/>Used Dimension for {$boxType->getReference()}, it is {$packedBox->getUsedWidth()}mm wide, {$packedBox->getUsedlength()}mm long and {$packedBox->getUsedDepth()}mm high" . PHP_EOL;
        echo "<br/>Used Volume  {$packedBox->getInnerVolume()}" . PHP_EOL;
        echo "<br/>Used Volume  {$packedBox->getUsedVolume()}" . PHP_EOL;

        echo "<br/>The combined weight of this box and the items inside it is {$packedBox->getWeight()}g" . PHP_EOL;

    }
		
	/***PRINT OUT THE RESUTLS OF CASE 2**/
	These items fitted into 1 box(es) 
	Inner Dimension for Le petite box, it is 35mm wide, 42mm long and 21mm high 
	Used Dimension for Le petite box, it is 34.5mm wide, 42mm long and 18.5mm high 
	Used Volume 30870 
	Used Volume 23310 
	The combined weight of this box and the items inside it is 380g
	/*****************************/ 
	
	So in case 1 the items must fit into one box 
	
	
		
	/********Case 3***********************/
	/*********ADD MORE ITEMS**************/
	
		for($i=0; $i<28; $i++){

        $packer->addItem(new TestItem('Item '.$i, 7.5, 6, 18.5, 10, true));
    }

	
	//Disable the weight distribution pass completely
    $packer->setMaxBoxesToBalanceWeight(0);
    $packedBoxes = $packer->pack();
	//and Print out the results

	 echo "These items fitted into " . count($packedBoxes) . " box(es)" . PHP_EOL;
    foreach ($packedBoxes as $packedBox) {
        $boxType = $packedBox->getBox(); // your own box object, in this case TestBox

        echo "<br/>Inner Dimension for {$boxType->getReference()}, it is {$boxType->getInnerWidth()}mm wide, {$boxType->getInnerLength()}mm long and {$boxType->getInnerDepth()}mm high" . PHP_EOL;
        echo "<br/>Used Dimension for {$boxType->getReference()}, it is {$packedBox->getUsedWidth()}mm wide, {$packedBox->getUsedlength()}mm long and {$packedBox->getUsedDepth()}mm high" . PHP_EOL;
        echo "<br/>Used Volume  {$packedBox->getInnerVolume()}" . PHP_EOL;
        echo "<br/>Used Volume  {$packedBox->getUsedVolume()}" . PHP_EOL;

        echo "<br/>The combined weight of this box and the items inside it is {$packedBox->getWeight()}g" . PHP_EOL;

    }
	
	/***PRINT OUT THE RESUTLS OF CASE 3**/
	These items fitted into 1 box(es) 
	Inner Dimension for Le petite box, it is 35mm wide, 42mm long and 21mm high 
	Used Dimension for Le petite box, it is 34.5mm wide, 42mm long and 18.5mm high 
	Used Volume 30870 
	Used Volume 24975 
	The combined weight of this box and the items inside it is 400g
	
	//Problem
	The used Dimensions are the same  with the pre

**Comment by dvdoug** [comment]
Hi

Unfortuntely I can't see a difference between your case 2 and case 3 - they both seem to have 28 items with the same dimensions - can you clarify the difference in the inputs you're using please?

Thanks! :)

**Comment by dvdoug** [comment]
Closing for now, @nakbill please feel free to reopen if you're still having difficulties and can answer that question
