### ISSUE TITLE
No stackable option

### ISSUE THREAD

**Issue by by225** [dvdoug/BoxPacker#156]
Hello,

Love the box packer as it works most of the time. Unfortunately, it seems to be missing a stackable option. Certain items, like some batteries, just can't be stacked. We might be able to fool the packer by sending in abnormally tall dimensions for batteries, but would prefer if it was part of the calculations. How difficult would this feature be to add?

Thank you

**Comment by dvdoug** [comment]
Hi

I think this could be quite tricky to do on a generalised basis - primarily to do with pinning down a definition of "stacked" which would vary depending on the precise usecase. Does "stacked" mean directly on top of each other only but side by side is OK? Or is it any touching banned including side by side? What if the overlap is only 5%, is that OK? You can probably see where I'm going with this.

The library has support for excluding things from the box entirely (to support batteries actually...) via the ConstrainedItem interface (http://www.boxpacker.io/en/stable/advanced-usage.html#custom-constraints).

Although that callback only allows including/excluding from the box entirely, I'd be happy to add something along those lines that also passed in the proposed placement of an item, and allowed a yes/no to be returned. The actual stacking detection would have to be implemented on your side.

Would that be helpful?

**Comment by by225** [comment]
Yes, that might be helpful, if you mean placement by layer.

I think heavier items (like batteries), just need to be restricted to the bottom layer of packing. So, if I could pass in a flag like "bottom_layer_only", that should solve the issue.

**Comment by by225** [comment]
Hello. I still need to be able to set a level for batteries. Are you still able to add something that would allow me to implement that? Thank you.

**Comment by dvdoug** [comment]
Am experimenting with a couple of approaches - should have something soon

**Comment by dvdoug** [comment]
Hi @by225 

The code definitely needs some cleanup, but I've just uploaded https://github.com/dvdoug/BoxPacker/blob/a97a78fc1a97c7d942c92f382ce2416b56407192/tests/VolumePackerTest.php#L119 and https://github.com/dvdoug/BoxPacker/blob/a97a78fc1a97c7d942c92f382ce2416b56407192/tests/Test/PositionallyConstrainedNoStackingTestItem.php as a WIP.

I think that proposed interface 🤞 should handle your usecase. Larger/heavier items are naturally packed first so I don't *think* an explicit hook to say "pack me first" would be needed, but let me know what you think?

**Comment by by225** [comment]
This appears to be working. Specified items are only placed on the first level of the package, and another package is added instead of placing any items on the second level. Thank you!

What method do you recommend for having to pack using two constraints, max count and non-stackable? I could pack the items both ways and compare. I could create a new Test Item containing both tests. Or, is it simpler than that?

**Comment by by225** [comment]
I created a new class called PositionallyConstrainedByCountNoStackingTestItem, which combines the max-count and non-stackable tests. It seems to be working.

**Comment by dvdoug** [comment]
Awesome! I'll add the extended hook into the next release of the library then, which I'm hoping to get out over the Easter period.
