### ISSUE TITLE
Can this work with 2D?

### ISSUE THREAD

**Issue by dennis-fedco** [dvdoug/BoxPacker#16]
I'm considering using this for packing large industrial sized parts like pumps and motors into crates, but not sure if I can make this work.

i.e. It is unlikely I can pack any particular item on top of any other particular item.  Placing a motor on top of a pump won't work, as they will surely fall off in transit.
Some motors can fit along side a pump though, and that might work.
Some pumps look like letter T in shape, and I can achieve better packing by chaining them, one T facing forward, one backwards.  

Overall, ... was thinking of writing my own library, but is there a way to make yours work for my purpose?

**Comment by JHGitty** [comment]
I like to use this library for 2d images but the library does not return the position of each item. That because I cannot use the library for this. :(

**Comment by dvdoug** [comment]
Closing this as nothing to action. @JHGitty your request is already being tracked as a separate issue.
