### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by ferryvg** [dvdoug/BoxPacker#164]
Hi!

1 minute packing these items:

|  width  |  height  |  depth  |  weight  |
|---|---|---|---|
|  110  |  110  |  50  |  100  |
|  100  |  300  |  30  |  100  |
|  100  |  150  |  50  |  100  |
|  100  |  200  |  80  |  110  |
|  80  |  150  |  80  |  50  |
|  80  |  150  |  80  |  50  |
|  80  |  150  |  80  |  50  |
|  270  |  70  |  60  |  350  |
|  150  |  150  |  80  |  180  |
|  80  |  150  |  80  |  50  |

Box dimensions:
820 x 820 x 830

**Comment by spectravp** [comment]
@ferryvg What is the max and empty weights of the box?

I can confirm this running unit tests, albeit, using my own max and empty weights.

Interesting enough, I found the following when adding the boxes one by one, in the order they are provided above:

(Box Weight Distribution at default, each test ran 3 times, average time provided, debug disable on cli)
1 item added: 0.06 seconds
2 items added: 0.04 seconds
3 items added: 0.13 seconds
4 items added: 1.86 seconds
5 items added: 39.65 seconds
6 items added: 30.61 seconds
7 items added: 21.57 seconds
8 items added: 2.9 minutes
9 items added: Timed out (over 600 seconds)
10 items added: Timed out (over 600 seconds)

What I find interesting is how the times drop after the 5th item, then shoots up after the 7th. Disabling weight balancing had no material effect, in fact, seemed to increase the time slightly.

**Comment by dvdoug** [comment]
Apologies for the delay in responding, I hope to have some time over easter to look at this. The last release did add some additional logic to get getter packing results which I expected to slow things down a little, but looks like I may need to tune it a bit further as it shouldn't be taking that long.

**Comment by zannstpierre** [comment]
@dvdoug this is still very much an issue. I've tested v2 and v3 releases and the issue is consistent. It is resolved when you force items to stay flat in packing. However, this is not a viable solution in most cases.

**Comment by dvdoug** [comment]
`3.2.2`
```
doug@SURFACEPRO6:/mnt/c/Users/micro/OneDrive/Documents/GitHub/BoxPacker$ vendor/bin/phpunit --filter testIssue164 tests/VolumePackerTest.php
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 58.63 seconds, Memory: 4.00MB

OK (1 test, 1 assertion)
```

`master`

```doug@SURFACEPRO6:/mnt/c/Users/micro/OneDrive/Documents/GitHub/BoxPacker$ vendor/bin/phpunit --filter testIssue164 tests/VolumePackerTest.php
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 454 ms, Memory: 4.00MB

OK (1 test, 1 assertion)
```

**Comment by dvdoug** [comment]
I'll release a version with the fix shortly. Sorry for ignoring for so long!
