### ISSUE TITLE
Weight not evenly distributed

### ISSUE THREAD

**Issue by by225** [dvdoug/BoxPacker#166]
Hello,

I've got a test case of 40 batteries, with a max count per pallet of 18. The packer rightly places the 40 batteries onto 3 pallets.  However, the quantities placed are 16, 13, and 11. Is there a way to run the weight distribution pass a second time, to get a more balanced placement of items on each pallet?

Thank you

**Comment by dvdoug** [comment]
Hi @by225 

That doesn't sound right - unless perhaps they are of different sizes/shapes?

Do you have a testcase I can run locally and look at?

**Comment by dvdoug** [comment]
Still happy to look at this @by225 if you can supply the testcase

**Comment by by225** [comment]
Hello. Still getting an uneven distribution of products. I thought I would upgrade to your latest version as a starter. But, I don't see PositionallyConstrainedByCountNoStackingTestItem any longer. How do I implement this test object with the latest of version 3?

**Comment by by225** [comment]
Was able to merge ConstrainedPlacementByCountTestItem and ConstrainedPlacementNoStackingTestItem to get ConstrainedPlacementByCountNoStackingTestItem, but still getting same result. How would you like me to supply the test case?

**Comment by dvdoug** [comment]
I can reproduce this, am looking into it
