### ISSUE TITLE
Wrong choice of box for a simple example (wrong volume)

### ISSUE THREAD

**Issue by Hyphen90** [dvdoug/BoxPacker#168]
Hi,

I've two boxes:

Small: 85mm x 190mm x 230mm
Medium: 220mm x 160mm x 160mm

and an item which should be added to a box:

55mm x 85mm x 122mm

Your API choose the medium size box, but it should use the small one. I've my debug output and saw, that your API thinks, that there is more space (air) in the small box (100 - getVolumeUtilisation()). But the calculation for the medium box is wrong, it should be round about 90% air (570cm³ item to 5632cm³ medium box):

Small:
These items fitted into 1 box(es)
This box is a Small Box, it is 85mm x 190mm x 230mm
The combined weight of this box and the items inside it is 380g
The dimensions of the hypothetical box placed around the items is 55mm x 85mm x 122mm
The unused space in the box (air) is 83.6%

Medium:
These items fitted into 1 box(es)
This box is a Medium Box, it is 220mm x 160mm x 160mm
The combined weight of this box and the items inside it is 400g
The dimensions of the hypothetical box placed around the items is 85mm x 55mm x 122mm
The unused space in the box (air) is 80.2%

Please, can you take a look at it? Many thanks ahead!

**Comment by dvdoug** [comment]
Hi @Hyphen90 

The attached testcase based on your example seems to work for me, although I had to guess the weight. 

What do I need to change in it to reproduce your scenario?

**Comment by dvdoug** [comment]
@Hyphen90 ?

**Comment by dvdoug** [comment]
Assuming you resolved this, please reopen if not
