### ISSUE TITLE
Feature Request: Available Quantity of each box

### ISSUE THREAD

**Issue by Noodleyman** [dvdoug/BoxPacker#169]
It would be very helpful if there was an easy way to define the available quantity of each box. Some HazMat materials require special boxes of which only a small quantity of each size may be available. for example, if the items require 4 boxes, but you only have 2 boxes of the correct size available it would be useful to evaluate if other size boxes are available/suitable before marking the items infallible. 

Has anybody been able to achieve something along these lines?

**Comment by Noodleyman** [comment]
I've been trying to figure this out myself, made reasonable progress but hit some odd behaviour I can't quite figure out. 

I've added the stockAmount to the boxes and the total available stockAmount reduces by 1 every time a box is selected as the BestBox, this bit works correctly.

I had hoped I could simply skip any defined boxes during the next iteration if the stockAmount <= 0, however for some reason when I add this step, all items are excluded from boxes, even if they had already been packed. I think I am missing something fundamental in how this library works. 

I modified the doVolumePacking() function as follows:
```
//Loop through boxes starting with smallest, see what happens
foreach ($this->boxes as $box) {
	
	if($box->getStockLevel() <= 0){
		// Skip this box because we ran out of stock
		continue;
	}

	$volumePacker = new VolumePacker($box, clone $this->items);
	$volumePacker->setLogger($this->logger);

	$packedBox = $volumePacker->pack();

	if ($packedBox->getItems()->count()) {
		$packedBoxesIteration[] = $packedBox;

		//Have we found a single box that contains everything?
		if ($packedBox->getItems()->count() === $this->items->count()) {
			break;
		}
	}
}
```

An example would be:
I have 10 items defined, each with a dimension of 100x100x100.

I have 5 boxes available, each with a dimension of 110x110x110
and 50 boxes available, each with a dimension of 125x125x125

The most suitable box is 110x110x110, I would like to fill the available 5 boxes with one item each, and afterwards use the boxes with 125x125x125 for the remaining 5 items.

I considered using the ConstrainedItem methods as per the documentation, however this is targeted to the items in the boxes, rather than the box availability itself.

@dvdoug , would you be able to offer any tips on the correct approach I should be using to try and add this additional functionality?

**Comment by dvdoug** [comment]
I'll certainly give this usecase a think @Noodleyman - to date my assumption has been that a warehouse would always reorder boxes before they got low (plus, stock-count figures are *never* correct 😭 )

In your snippet above I can see the stock count check - where are you decrementing it? Doing it at https://github.com/dvdoug/BoxPacker/blob/master/src/Packer.php#L191 I think should work?

**Comment by Noodleyman** [comment]
Thank you @dvdoug , I appreciate you taking the time to review. I agree with the assumption in most cases. the business case I am working on requires that an inventory of packing materials to be monitored as some products are hazardous (Explosives). Those items require special packing materials to comply with legal requirements as part of the permit and legal requirements by the carrier. in other words, those boxes are "special", they cost more acquire thus the stock level of packing materials for these special boxes are closely monitored. 

to make things more complex, there is a multi-dimensional element in that some smaller boxes can be bundled with larger (I've yet to write this part, but it's on the list).  As the boxes are more expensive, only a limited quantity are kept in stock at any one time to meet the general demands, but there are risks to running out based on unexpected demand. In those cases, I would like for the process to look for other suitable boxes. 

I've got most of the solution working, but was a bit of trial and error whilst learning your solution. I've previously written my own solution to solve the packing problems, but thought your solution was more mature/refined :)

I've added some methods to add/subtract from boxes, here is the complete function I am using at the moment. it appears to be working, however I ran into a problem if whilst figuring out the solution it ran out of boxes entirely, in which case I intend to add a "catch all" box for the remainder, a virtual container so the handler can figure it out. :)

I've paused development for the moment whilst waiting on some details around special requirements for the project, but will be picking this up again sometime soon.

```
public function doVolumePacking(): PackedBoxList
{
	$packedBoxes = new PackedBoxList();

	//Keep going until everything packed
	while ($this->items->count()) {
		$packedBoxesIteration = [];

		//Loop through boxes starting with smallest, see what happens
		foreach ($this->boxes as $box) {

			if($box->getStockLevel() <= 0){
				continue;
			}

			$volumePacker = new VolumePacker($box, clone $this->items);
			$volumePacker->setLogger($this->logger);

			$packedBox = $volumePacker->pack();

			if ($packedBox->getItems()->count()) {
				$packedBoxesIteration[] = $packedBox;

				//Have we found a single box that contains everything?
				if ($packedBox->getItems()->count() === $this->items->count()) {
					break;
				}
			}
		}

		if(!empty($packedBoxesIteration)) {
			foreach ($packedBoxesIteration as $k => $b) {
				if ($b->getBox()->getStockLevel() <= 0 && count($packedBoxesIteration) >= 2) {
					// Never remove the last box, doing this will break everything... instead, when we have absolutely no suitable boxes, allow it to allocate negative boxes.
					// It's either this, or break the ordering process.
					unset($packedBoxesIteration[$k]);
				}
			}
		}

		//Find best box of iteration, and remove packed items from unpacked list
		$bestBox = $this->findBestBoxFromIteration($packedBoxesIteration);

		/** @var PackedItem $packedItem */
		foreach ($bestBox->getItems() as $packedItem) {
			$this->items->remove($packedItem->getItem());
		}

		$packedBoxes->insert($bestBox);
		$tmpBox = $bestBox->getBox();
		$tmpBox->setStockLevel();
	}

	return $packedBoxes;
}
```

```

public function getStockLevel(): int
{
	return $this->stockLevel;
}

public function setStockLevel(): int
{
	$this->stockLevel--;
	return $this->stockLevel;
}

```

**Comment by Noodleyman** [comment]
I finally managed to get back to this item as my project resumed. Now having a better understanding of the way BoxPacker is put together I've added the stock control using an alternate method which seems to be working a lot better than my previous attempt.

In my box class, I've added:
```
    public function __construct(
        string $reference,
        int $outerWidth,
        int $outerLength,
        int $outerDepth,
        int $emptyWeight,
        int $innerWidth,
        int $innerLength,
        int $innerDepth,
        int $maxWeight,
        int $stockLevel
    ) {
        $this->reference = $reference;
        $this->outerWidth = $outerWidth;
        $this->outerLength = $outerLength;
        $this->outerDepth = $outerDepth;
        $this->emptyWeight = $emptyWeight;
        $this->innerWidth = $innerWidth;
        $this->innerLength = $innerLength;
        $this->innerDepth = $innerDepth;
        $this->maxWeight = $maxWeight;
        $this->stockLevel = $stockLevel;
    }
```
```
    public function getStockLevel(): int
    {
        return $this->stockLevel;
    }

    public function reduceStockLevel(): int
    {
        $this->stockLevel--;
        return $this->stockLevel;
    }

    /**
     * {@inheritdoc}
     */
    public function jsonSerialize()
    {
        return [
            'reference' => $this->reference,
            'innerWidth' => $this->innerWidth,
            'innerLength' => $this->innerLength,
            'innerDepth' => $this->innerDepth,
            'emptyWeight' => $this->emptyWeight,
            'maxWeight' => $this->maxWeight,
            'stockLevel' => $this->stockLevel,
        ];
    }
```
This allows the on hand stock level of each box type to be passed when the box is defined.

Then, in Packer.php class:
```
//Find best box of iteration, and remove packed items from unpacked list
$bestBox = $this->findBestBoxFromIteration($packedBoxesIteration);
$bestBox->getBox()->reduceStockLevel();
```

in sanityPrecheck():
```
/** @var Box $box */
foreach ($this->boxes as $box) {

    // Include stock level checking
    if($box->getStockLevel() <= 0){
        // move on...
        continue;
    }

    if ($item->getWeight() <= ($box->getMaxWeight() - $box->getEmptyWeight())) {
        $possibleFits += count((new OrientatedItemFactory($box))->getPossibleOrientationsInEmptyBox($item));
    }
}
```

and in doVolumePacking(),
```
//Loop through boxes starting with smallest, see what happens
foreach ($this->boxes as $box) {
    if($box->getStockLevel() <= 0){
        echo "we cannot use this box, moving on.....<br>";
        // move on...
        continue;
    }

    $volumePacker = new VolumePacker($box, clone $this->items);
    $volumePacker->setLogger($this->logger);
```

Then, standard logic applies. use a try/catch to check if an exception was thrown because you have not got any suitable boxes or enough boxes.


Seems to work great for my test cases.

Thought I would share in case you wanted to recycle the code in any way. giving back etc :)

**Comment by dvdoug** [comment]
I don't think the library should add/require a `setQuantity` anywhere on the boxes - how this would be handled would be very different in different applications (e.g. a DTO vs Entities), and might end up with the library in effect making direct database writes.

Probably much safer to simply take in an available quantity for the packing calculations and let the calling application handle processing any stock deductions afterwards. That would also allow the algorithm to be run in a preview-like mode "could we send?" rather than than assuming "we are sending".

**Comment by Noodleyman** [comment]
Morning Doug,

That's kind of what I have it doing at the moment. I feed in available box quantities for the calculations, although it keeps a tally of how many boxes have already been packed and reduced that (thus the setQuantity() method) . This way it can't use two or more of the same box if we only have 1 available. It's only used by the calculations. 

I then write all final results to a DB, and based on other criteria (IE, has the order been firmed up with a payment), then reduce the stock levels of boxes in the DB.

I found if I didn't have it internally keep track of the on hand quantity, and reduce it once a box had been packed then it would reuse the same box, even if we used the last one.

**Comment by dvdoug** [comment]
Understood, I just need to look at it from more of an application-agnostic POV which means it necessarily needs being a little more complicated - e.g. for apps using weight redistribution, the library will need to add 1 back to the quantity available for working calculation purposes so that the repacking can succeed - so there could easily be tens or hundreds of calls to setQuantity decrementing it, incrementing it and then decrementing it again - and imagine if a call to setQuantity were to trigger an audit trail entry or something it would get overwhelmed.

Also need to not break the API contract, and benchmark the implementation to ensure it doesn't noticably slow things down for people who don't need it. Paranoia is the name of the game 😅

**Comment by dvdoug** [comment]
(I am looking at this btw)

**Comment by Noodleyman** [comment]
Thank you Doug, much appreciated.

I know what you mean about Paranoia, I've had those scenarios where a minor change cascades into a world of pain before, never fun!

I guess as I am not using the weight balance features I've not run into those alternate test cases, but can see why it adds additional complexity. I thought that the weight balancing feature balanced items between boxes that already had been packed as a follow up step? I'm assuming that step should not ever have a need for additional boxes and that the stock level check isn't necessary, however I'm assuming that my assumption is wrong as you are the guru to this solution :)

**Comment by dvdoug** [comment]
The weight balance starts with the already packed boxes, but then does two thing that come into play here:

1) After moving an item from a heavy box to a lighter one, it repacks the heavy one with the full set of boxes in case a smaller/lighter box is now suitable for the reduced item count
2) When attempting to move an item from a lighter box to a heavier one, it again repacks using the full set of boxes because the goal is for the better weight-balanced set to fit into any box, not just the one that's already used.

That does mean there scenarios where the previously heavier box remains with fewer items, and the previously lighter box got more items and a bigger box thereby making things less efficient from a pure volume/spatial POV but as most carriers charge by weight rather than box size (unless the box is grossly oversize) that trade-off is normally OK considering the benefits to the people actually having to lift the things.

**Comment by Noodleyman** [comment]
that makes total sense, and I can feel the heat from the fire in your mind from here.  Keep up the great work! thank you for the solution you have developed with such attention to detail :)
