### ISSUE TITLE
Max Weight for container box not being enforced

### ISSUE THREAD

**Issue by kaminimagento** [dvdoug/BoxPacker#170]
I have a test box set up as 17x12x12 with weight at 0.2 lbs and max weight at 6 lbs. When I try to checkout with qty 100 of a product that is sized 7x13x0.2 with a weight of 0.0657 lbs it shows it shipping in one box when I think it should be split into two boxes due to combined weight and height being over the max limits for that box. 
Also, none of the decimal value of weight not working.

**Comment by dvdoug** [comment]
Yes, the code kinda assumes grams and millimetres whereby fractional amounts *really* don't matter in real-life contexts.

I've multiplied the weights in your example though so they are integers (x10000) and I get 2 boxes as output (see attached test) - can you let me know what I need to change to reproduce your single-box packing?

**Comment by dvdoug** [comment]
@kaminimagento ?

**Comment by dvdoug** [comment]
Assuming you resolved this, please reopen if not
