### ISSUE TITLE
Does a set of items fit into a particular box

### ISSUE THREAD

**Issue by stumarcus576** [dvdoug/BoxPacker#171]
What are the limitations, if any, of the code that determines whether a set of items fit into a particular box (documented here: https://boxpacker.readthedocs.io/en/stable/getting-started.html) ? Does that code stop working if the number of items is too large? Is that code only correct a percentage of the time? Is the algorithm documented in the literature somewhere?

**Comment by kokoshneta** [comment]
I’m not sure about the algorithm, but the code does not stop working (by which I assume you mean halting the script) if there are too many items to fit; the remaining items just won’t be included in $packedBox->getItems(). How correct it is cannot really be answered without having a physical box to compare to.

**Comment by dvdoug** [comment]
Hello @stumarcus576 

When utilising the `VolumePacker` on it's own as in that example, @kokoshneta is absolutely correct - the code won't alert or fail in anyway, the item just won't be packed. If you wanted to know which item(s) in particular weren't packed you would need to count/diff that output against your input list.

When using the `Packer`, the library will open up a 2nd/3rd/4th etc box as appropriate once no more can fit into the first one. Where an item is simply too large to fit into even an empty box, that would then be handled according to https://boxpacker.readthedocs.io/en/stable/too-large-items.html

In terms of algorithm, the literature I found focuses around eking out absolute maximum packing efficiency, whereas this library is designed to approximate what a human is likely to do when confronted with some items and boxes so they are targeting similar, but slightly different problems. Having said that, every solution generated by the library should be reasonably efficient, and more importantly should be always be correct (i.e the items will actually fit into the box!). 

Hope that helps?

**Comment by dvdoug** [comment]
@stumarcus576 am assuming that answered your question, but please reopen if not
