### ISSUE TITLE
How many (identical) items fit into a box?

### ISSUE THREAD

**Issue by kokoshneta** [dvdoug/BoxPacker#172]
I use BoxPacker library as part of a system to optimise our storage of books in a warehouse; the only part that I really need to use is the VolumePacker, to figure out how many of a given item can I fit into a box of a specified size.

Some of the ‘boxes’ we deal with are actually pallets measuring 800 × 1200 × 1300 mm (1.30 m is the maximum height allowed), with a maximum weight allowance of 500 kg. Some of the books are fairly small, with the lightest and smallest measuring just 150 × 110 × 5 mm and weighing just 56 g. Naturally, a big pallet will be able to fit **a lot** of these.

So far, I do pretty much just as described on the [Getting Started](https://boxpacker.readthedocs.io/en/stable/getting-started.html) page:

- Make an ItemList
- Figure out the maximum possible number of books, limited by weight (container’s max weight divided by book weight)
- In a _for_ loop (1 to max number of books), create a new Item object and insert it into the ItemList
- Make a VolumePacker object with the ItemList object
- Pack(), getItems() and count() the result to get the number of books that will fit

This seems rather inefficient to me, especially having to add thousands of objects to the ItemList when you already *know* that every object is completely identical. The actual packing itself often takes long enough for the function to time out after max_execution_time of 120 seconds for a single box.

Is there a more efficient way of doing this? Wouldn’t the fact that all items are identical make the calculation simpler, in that each layer can be assumed to be the same?

**Comment by dvdoug** [comment]
Hello @kokoshneta 

If you can supply a testcase that simulates your example I'd be happy to take a look at what can be done to optimise the code to handle it better - thousands of items is certainly not the type of usecase that I've had in mind when designing the heuristics to date so this could be interesting :)

Would your pallet be thousands of copies of the same book, or would it consist of different titles/dimensions?

**Comment by kokoshneta** [comment]
I’m not sure **how** I’d provide you with a test case, but I’d love to. Could you let me know what exactly a test case would entail?

For my particular use case, yes, it’s always only one title per unit, so it would always be the same measurements and weight for all units. I can definitely see use cases for being able to do it with items of varying sizes and weights, but that would not have the same (I assume) benefit, and I’m not sure much progress can really be made over the current approach. But I do think knowing beforehand that all items are identical should make it possible to reduce processing time (and perhaps memory use as well, since you’d only ever need to create one object which can be referenced repeatedly, rather than creating an arbitrary number of identical objects).

**Comment by dvdoug** [comment]
Cool, if all the items on a pallet are identical, I can use the details from your initial post to test with - I just wanted to make sure that if there was a mix of items on one of your pallets I would be benchmarking with a realistic mix

**Comment by andyg5000** [comment]
I'm testing this out for rate requests on an e-commerce site. When using 3D packing (keep flat = false), I'm getting an excessive increase in time to calculate packages. A quantity of 30 items in the cart and it's pretty much timing out. When I turn that flag off it's (obviously) much faster. 

Not sure if that setting would help @kokoshneta 

Also wondering if there's anything we can do to speed up 3D packing, I know it's an intensive task!

**Comment by dvdoug** [comment]
@andyg5000 would you be able to share an example of the items/dimensions and boxes that you're using here for me to test/benchmark with? Also, I'm curious what usecase you're using the lib for, as 30 sounds a bit high for ecommerce - is this warehousing too?

**Comment by andyg5000** [comment]
Hey @dvdoug,

Thanks for following up. My use case is for B2B and other retailers that sell larger quantities in one order. 

As far as reproducing, I don't remember the exact specs, but it should have been something like:

1 Box type 18 x 18 x 24 
10 Items 10 x 5 x 8 
5 items 5 x 5 x 3 

All of the dimensions were in inches then converted to mm. Switching between 2D and 3D was drastic.

**Comment by dvdoug** [comment]
@andyg5000 on my laptop, the testcase I've just added for that examples runs in 0.25 seconds so something seems amiss if it's taking longer than that on a server. Can I check you're not running xdebug when benchmarking that?

```
doug@SURFACEPRO6:/mnt/c/Users/micro/OneDrive/Documents/GitHub/BoxPacker$ vendor/bin/phpunit tests/VolumePackerTest.php --filter=testIssue172B
PHPUnit 8.3.3 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 247 ms, Memory: 8.00 MB

OK (1 test, 1 assertion)```

**Comment by dvdoug** [comment]
@kokoshneta using your example, I can see a significant non-linear slowdown between trying to pack 10000 items (63 seconds) and 1000 (0.75 seconds). I'll do some profiling to try and figure where that's blowing up.

```doug@SURFACEPRO6:/mnt/c/Users/micro/OneDrive/Documents/GitHub/BoxPacker$ vendor/bin/phpunit tests/VolumePackerTest.php --filter=testIssue172A
PHPUnit 8.3.3 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 1.05 minutes, Memory: 22.00 MB

OK (1 test, 1 assertion)
```
doug@SURFACEPRO6:/mnt/c/Users/micro/OneDrive/Documents/GitHub/BoxPacker$ vendor/bin/phpunit tests/VolumePackerTest.php --filter=testIssue172A
PHPUnit 8.3.3 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 739 ms, Memory: 10.00 MB

OK (1 test, 1 assertion)
```

```

**Comment by dvdoug** [comment]
Current master (released as v3.4.0) brings the time down for the 8928 items to just over 6 seconds in my testing so I'm going to call this closed. I will also try to backport as much of this as I can to v2.x however the key data structure is different so backwards compatibility may impact on what I can do there.

```
PHPUnit 8.3.4 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 6.12 seconds, Memory: 10.00 MB

OK (1 test, 1 assertion)
```

**Comment by konradg123** [comment]
I'm working on a similar case, it seems that comparing item dimensions is taking a lot of time and can be further optimised with a little memory overhead. Method VolumePacker::isSameDimensions could be optimized for this and other kind of tasks by caching item's dimensions for comparison, and since dimensions are sorted therfore invulnerable to items orientation, so caching should significantly influence speed of finding best orientation.

Non-cached
![image](https://user-images.githubusercontent.com/21104121/73353393-8b205880-4293-11ea-811e-f5c9f7689954.png)

Cached
![image](https://user-images.githubusercontent.com/21104121/73353481-b30fbc00-4293-11ea-9bcf-6d158083819f.png)

**Comment by dvdoug** [comment]
Interesting, @konradg123 what are you using for the cache key there? I'll admit to having assumed sorting 3 items was quick enough that a cache wouldn't be helpful

**Comment by konradg123** [comment]
@dvdoug the problem im facing is packing a lot of same small items in different box sizes to minimise shipping costs (the biggest box is not always the best option), 
also by "caching" im nowhere near any persistent cache solution, just simple runtime.

VolumePacker is constantly trying to call the isSameDimensions for exact same item, so its not only sorting but the overhead of 3 getters multiplied by like 1000 items by every other orientation, notice the invocation count on the screens, so it's either:
1. storing the dimensions sorted in the item, and that implies using additional interface to check for the cached dimensions by VolumePacker, no cache key needed
2. using simple spl_object_id to check if its the same item we'r trying to pack, if not run the original sorting since it may have same dimensions

**Comment by dvdoug** [comment]
#2 is in 3.5.1
