### ISSUE TITLE
PHPUnit 

### ISSUE THREAD

**Issue by stumarcus576** [dvdoug/BoxPacker#173]
How does one install PHPUnit for use by BoxPacker? I am getting the following error when I attempt to run one of the test scripts that come with BoxPacker.

php VolumePackerTest.php 
PHP Fatal error:  Class 'PHPUnit\Framework\TestCase' not found in /home/srogers/phpCode/vendor/dvdoug/boxpacker/tests/VolumePackerTest.php on line 19

**Comment by dvdoug** [comment]
With the library installed as a dependecy as it appears you have above, then `vendor/bin/phpunit vendor/dvdoug/boxpacker/tests` works for me assuming PHPUnit is installed as a dependency too

**Comment by dvdoug** [comment]
Assuming this is resolved, please reopen if not
