### ISSUE TITLE
Volume not fully utilized 

### ISSUE THREAD

**Issue by tj-kev** [dvdoug/BoxPacker#175]
Hi,
I've been working on a scenario and wanted to check if its actually possible.

Box:
40x40x40

Items:
Qty: 10 - Each 35x35x5

The box should be capable of holding all 10 items as shown in the images below. 8 stacked up and 2 filling in the sides. However when trying to pack it using the volume pack method it only packs 8 to a box, not filling in the sides. Is this a limitation or am I doing something wrong?

Thanks

![1](https://user-images.githubusercontent.com/15669671/61905238-89f72300-af20-11e9-8818-f8485efa948d.png)

![2](https://user-images.githubusercontent.com/15669671/61905248-8fed0400-af20-11e9-9064-188c673f38bd.png)

**Comment by dvdoug** [comment]
Hi @tj-kev 

I'll need to do some work to investigate this scenario, but from your visuals I suspect this is because the 2 side items are considered non-stable in that orientation and liable to tipping - as it stands that logic only considers items in a standalone manner, and doesn't take into account whether they can be propped up by surrounding items or the box wall

**Comment by dvdoug** [comment]
Also, just out of interest - what tool did you use to make those?

**Comment by tj-kev** [comment]
Ok, thanks for the update. Makes sense.

The images were made in TinkerCad, https://www.tinkercad.com/

**Comment by victorhramos-dev** [comment]
I am having same issues.
I am doing a game api project and i am using this library to pack 2D boxes.
It is starting a new box without filling 100% the previous box.

I am drawing the image using GD.
Look the item highlighted, it was placed in a new box at (0,0,0) but in the previous box (in the image) had a lot of space to place this item.
![image](https://user-images.githubusercontent.com/56742613/67143896-d5328080-f246-11e9-9c22-eed7138d8608.png)
