### ISSUE TITLE
Fatal error: Uncaught Error: Class 'DVDoug\BoxPacker\Packer

### ISSUE THREAD

**Issue by carlofleischmann** [dvdoug/BoxPacker#176]
Hey, i installed BoxPacker(3.3) via composer in a empty folder on my local mamp.

-myFolder
--vendor
---composer
---dvdoug
---psr

I created a new php file with your example. When i execute the php File i get always 

"Fatal error: Uncaught Error: Class 'DVDoug\BoxPacker\Packer' not found in..."

I tried to import the the Packer Class via require_once(PathToPhpFile), then it works.
So there is something wrong with the namespaces?
What did i wrong? In which folder i had to create my example php file?

Thanks for you help.

**Comment by pfcode** [comment]
@carlofleischmann Are you sure you have included Composer autoloader?

After installing a package with Composer, it creates `vendor/autoload.php` file that needs to be imported on top of your PHP script - then you will be able to use classes within this package, just like in examples.

```php
require_once __DIR__ . '/vendor/autoload.php'
```

**Comment by dvdoug** [comment]
Hi @carlofleischmann, I see you gave a 👍 to @pfcode's explanation, does that mean you've resolved this?

**Comment by carlofleischmann** [comment]
Hey, yeah its resolved. Thank you

**Comment by dvdoug** [comment]
Great. Thanks @pfcode!
