### ISSUE TITLE
do not pack vertically up the side of the box

### ISSUE THREAD

**Issue by fbeke** [dvdoug/BoxPacker#177]
Hi Doug,

is there an easy way to switch the packing logic from vertically packing up the side of the box first to pack from the bottom (full layers) up?
I'm trying to pack items/boxes onto pallets with a minimal necessary height (because of the stability, stretch foil usage, etc), but the used height is always near the maximum possible.
I don't have visualizations, but seems, like it really packs up a side of the "box" first.

Thanks in advance for any information!

Regards,
Feri

**Comment by fbeke** [comment]
Hi Doug,

is there an easy way to switch the packing logic from vertically packing up the side of the box first to pack from the bottom (full layers) up?
I'm trying to pack items/boxes onto pallets with a minimal necessary height (because of the stability, stretch foil usage, etc), but the used height is always near the maximum possible.
I don't have visualizations, but seems, like it really packs up a side of the "box" first. 

Thanks in advance for any information!

Regards,
Feri

**Comment by fbeke** [comment]
Sorry for the noise, i probably misinterpreted the documentation on this page: https://boxpacker.readthedocs.io/en/stable/principles.html, also some other circumstances made me believe that, but later i found out, this is not the case, so closing the issue.

**Comment by hormigo** [comment]
Hi Feri:

How did you fix it?. I want to pack items in a pallet and the algorithm left gaps in base and try to fill height first. If i change the height with other axis it seems to work better, but keeps gaps and don't fill layers.

Here and example:
![Captura de pantalla 2019-10-08 a las 14 43 29](https://user-images.githubusercontent.com/3966865/66396477-22f2f180-e9da-11e9-9180-4b7a0288e4f0.png)

There are any way to work with pallets?

Thanks

**Comment by fbeke** [comment]
Did not fixed it, but seems to me, it uses another side as bottom, not the one, i though it should be...
I just define the pallet as a box, then after packing i get the used height and use that for other computes (needed stretch foil, etc), it's a rough estimate, but it's ok for now...
Also check, if you use the latest version, upgrading fixed for me a lot of packing "problems".
