### ISSUE TITLE
Items position not correct

### ISSUE THREAD

**Issue by fbeke** [dvdoug/BoxPacker#178]
Hi Doug, 
i created a quick and simple visualization to better understand some packing decisions, and it seems, that position of some items (or rather just the rotation) are not correct, see the attached picture.
Thanks,
Feri
![items_in_box](https://user-images.githubusercontent.com/750777/62936821-10d64780-bdcb-11e9-878d-5b3c9b1c8e4a.png)

**Comment by dvdoug** [comment]
Hi @fbeke 

Would you be able to share the data (items/box) you used when doing that packing and also (if possible) the script you used for the visualation?

Because, yes that sounds bad

**Comment by fbeke** [comment]
I'm so sorry, i messed it up again... :( I'm doing a conversion between 3 "coordinate systems" (our system - just the dimension orders, your package - dimension orders/positions, three.js - swapped axes, etc), and i had an error. In fact, probably all the items are rotated, but it was not so obvious for 

the others, because of the dimensions - also this was the reason, i was fooled.
The actual visualization is attached - keep in mind, it's just a simple quick method, not so "transparent", but you can rotate/zoom using the mouse.
Actually i still think, there is some problem somewhere, seems, that the "bottom of the box" is one of it's side, there are gaps at the (visualized) bottom

``<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Show package</title>
    <script src="http://threejs.org/build/three.min.js"></script>
    <script src="http://threejs.org/examples/js/controls/OrbitControls.js"></script>
    <style>canvas { width: 100%; height: 100% }</style>
</head>
<body>

<script type="module">
    var camera, scene, renderer, mesh, geometry, pallet;
    var cameraControls;
    var ambientLight, light;

    var container;

    container = new THREE.Vector3();

    var data = JSON.parse('{"box":{"w":295,"h":450,"d":295},"items":[{"x":0,"y":0,"z":0,"w":49,"h":52,"d":161},{"x":196,"y":213,"z":49,"w":49,"h":161,"d":52},{"x":196,"y":213,"z":101,"w":49,"h":161,"d":52},{"x":147,"y":213,"z":101,"w":49,"h":161,"d":52},{"x":98,"y":213,"z":101,"w":49,"h":161,"d":52},{"x":49,"y":213,"z":101,"w":49,"h":161,"d":52},{"x":0,"y":213,"z":101,"w":49,"h":161,"d":52},{"x":245,"y":213,"z":49,"w":49,"h":161,"d":52},{"x":147,"y":213,"z":49,"w":49,"h":161,"d":52},{"x":0,"y":213,"z":153,"w":49,"h":161,"d":52},{"x":98,"y":213,"z":49,"w":49,"h":161,"d":52},{"x":49,"y":213,"z":49,"w":49,"h":161,"d":52},{"x":0,"y":213,"z":49,"w":49,"h":161,"d":52},{"x":208,"y":213,"z":0,"w":52,"h":161,"d":49},{"x":156,"y":213,"z":0,"w":52,"h":161,"d":49},{"x":104,"y":213,"z":0,"w":52,"h":161,"d":49},{"x":245,"y":213,"z":101,"w":49,"h":161,"d":52},{"x":49,"y":213,"z":153,"w":49,"h":161,"d":52},{"x":0,"y":213,"z":0,"w":52,"h":161,"d":49},{"x":245,"y":213,"z":205,"w":49,"h":161,"d":52},{"x":245,"y":374,"z":0,"w":49,"h":52,"d":161},{"x":196,"y":374,"z":0,"w":49,"h":52,"d":161},{"x":147,"y":374,"z":0,"w":49,"h":52,"d":161},{"x":98,"y":374,"z":0,"w":49,"h":52,"d":161},{"x":49,"y":374,"z":0,"w":49,"h":52,"d":161},{"x":0,"y":374,"z":0,"w":49,"h":52,"d":161},{"x":196,"y":213,"z":205,"w":49,"h":161,"d":52},{"x":98,"y":213,"z":153,"w":49,"h":161,"d":52},{"x":147,"y":213,"z":205,"w":49,"h":161,"d":52},{"x":98,"y":213,"z":205,"w":49,"h":161,"d":52},{"x":49,"y":213,"z":205,"w":49,"h":161,"d":52},{"x":0,"y":213,"z":205,"w":49,"h":161,"d":52},{"x":245,"y":213,"z":153,"w":49,"h":161,"d":52},{"x":196,"y":213,"z":153,"w":49,"h":161,"d":52},{"x":147,"y":213,"z":153,"w":49,"h":161,"d":52},{"x":52,"y":213,"z":0,"w":52,"h":161,"d":49},{"x":245,"y":52,"z":205,"w":49,"h":161,"d":52},{"x":49,"y":0,"z":0,"w":49,"h":52,"d":161},{"x":52,"y":52,"z":0,"w":52,"h":161,"d":49},{"x":98,"y":52,"z":49,"w":49,"h":161,"d":52},{"x":49,"y":52,"z":49,"w":49,"h":161,"d":52},{"x":0,"y":52,"z":49,"w":49,"h":161,"d":52},{"x":208,"y":52,"z":0,"w":52,"h":161,"d":49},{"x":156,"y":52,"z":0,"w":52,"h":161,"d":49},{"x":104,"y":52,"z":0,"w":52,"h":161,"d":49},{"x":0,"y":52,"z":0,"w":52,"h":161,"d":49},{"x":196,"y":52,"z":49,"w":49,"h":161,"d":52},{"x":0,"y":0,"z":210,"w":161,"h":52,"d":49},{"x":0,"y":0,"z":161,"w":161,"h":52,"d":49},{"x":245,"y":0,"z":0,"w":49,"h":52,"d":161},{"x":196,"y":0,"z":0,"w":49,"h":52,"d":161},{"x":147,"y":0,"z":0,"w":49,"h":52,"d":161},{"x":98,"y":0,"z":0,"w":49,"h":52,"d":161},{"x":147,"y":52,"z":49,"w":49,"h":161,"d":52},{"x":245,"y":52,"z":49,"w":49,"h":161,"d":52},{"x":196,"y":52,"z":205,"w":49,"h":161,"d":52},{"x":147,"y":52,"z":153,"w":49,"h":161,"d":52},{"x":147,"y":52,"z":205,"w":49,"h":161,"d":52},{"x":98,"y":52,"z":205,"w":49,"h":161,"d":52},{"x":49,"y":52,"z":205,"w":49,"h":161,"d":52},{"x":0,"y":52,"z":205,"w":49,"h":161,"d":52},{"x":245,"y":52,"z":153,"w":49,"h":161,"d":52},{"x":196,"y":52,"z":153,"w":49,"h":161,"d":52},{"x":98,"y":52,"z":153,"w":49,"h":161,"d":52},{"x":0,"y":52,"z":101,"w":49,"h":161,"d":52},{"x":49,"y":52,"z":153,"w":49,"h":161,"d":52},{"x":0,"y":52,"z":153,"w":49,"h":161,"d":52},{"x":245,"y":52,"z":101,"w":49,"h":161,"d":52},{"x":196,"y":52,"z":101,"w":49,"h":161,"d":52},{"x":147,"y":52,"z":101,"w":49,"h":161,"d":52},{"x":98,"y":52,"z":101,"w":49,"h":161,"d":52},{"x":49,"y":52,"z":101,"w":49,"h":161,"d":52},{"x":0,"y":374,"z":161,"w":161,"h":52,"d":49}]}');

    container.set(data.box.w, data.box.h, data.box.d);

    scene = new THREE.Scene();
    scene.background = new THREE.Color( 0xAAAAAA );

    // CAMERA
    camera = new THREE.PerspectiveCamera( 60, window.innerWidth / window.innerHeight, 0.1, 10000 );
    camera.position.set( container.x/2, container.y/2, container.z * 3 );
    camera.lookAt( container.x / 2, container.y / 2, container.z / 2 );

    // LIGHTS
    ambientLight = new THREE.AmbientLight( 0x333333 );	// 0.2
    light = new THREE.DirectionalLight( 0xFFFFFF, 1.0 );

    scene.add( ambientLight );
    scene.add( light );

    renderer = new THREE.WebGLRenderer();
    renderer.setSize(window.innerWidth, window.innerHeight);
    document.body.appendChild(renderer.domElement);

    // EVENTS
    window.addEventListener( 'resize', onWindowResize, false );

    // CONTROLS
    cameraControls = new THREE.OrbitControls( camera, renderer.domElement );
    cameraControls.target.set(container.x / 2, container.y / 2, container.z / 2);
    cameraControls.addEventListener( 'change', render );

    // add box/pallet
    geometry = new THREE.BoxBufferGeometry(container.x, container.y, container.z, 1, 1, 1);
    var material = new THREE.MeshBasicMaterial({color: 0xff0000, wireframe: true});
    pallet = new THREE.Mesh(geometry, material);
    pallet.position.set(container.x / 2, container.y / 2, container.z/2);
    scene.add(pallet);

    var axes = buildAxes( 2000 );

    scene.add(axes);

    //camera.position.z = 4000;
    var materialG = new THREE.MeshBasicMaterial({color: 0x00ff00, wireframe: true});

    // add items
    data.items.forEach(function(item, index){
        addBox(item.x, item.y, item.z, item.w, item.h, item.d, materialG);
    });

    onWindowResize();

    function addBox(x, y, z, w, h, d, material)
    {
        material = new THREE.MeshBasicMaterial({color: Math.random() * 0xffffff, wireframe: true});

        var cubeGeometry = new THREE.BoxGeometry(w, h, d, 2, 2, 2);
        var cube = new THREE.Mesh(cubeGeometry, material);
        cube.position.set(x + w/2, y + h/2, z + d/2);
        scene.add(cube);
    }

    // EVENT HANDLERS
    function onWindowResize() {
        var canvasWidth = window.innerWidth;
        var canvasHeight = window.innerHeight;
        renderer.setSize( canvasWidth, canvasHeight );
        camera.aspect = canvasWidth / canvasHeight;
        camera.updateProjectionMatrix();
        render();
    }

    function render() {
        renderer.render( scene, camera );
    }

    function buildAxis( src, dst, colorHex, dashed ) {
        var geom = new THREE.Geometry(),
            mat;

        if(dashed) {
            mat = new THREE.LineDashedMaterial({ linewidth: 3, color: colorHex, dashSize: 3, gapSize: 3 });
        } else {
            mat = new THREE.LineBasicMaterial({ linewidth: 3, color: colorHex });
        }

        geom.vertices.push( src.clone() );
        geom.vertices.push( dst.clone() );
        geom.computeLineDistances(); // This one is SUPER important, otherwise dashed lines will appear as simple plain lines

        var axis = new THREE.Line( geom, mat, THREE.LineSegments );

        return axis;

    }

    function buildAxes( length ) {
        var axes = new THREE.Object3D();

        axes.add( buildAxis( new THREE.Vector3( 0, 0, 0 ), new THREE.Vector3( length, 0, 0 ), 0xFF0000, false ) ); // +X
        axes.add( buildAxis( new THREE.Vector3( 0, 0, 0 ), new THREE.Vector3( -length, 0, 0 ), 0xFF0000, true) ); // -X
        axes.add( buildAxis( new THREE.Vector3( 0, 0, 0 ), new THREE.Vector3( 0, length, 0 ), 0x00FF00, false ) ); // +Y
        axes.add( buildAxis( new THREE.Vector3( 0, 0, 0 ), new THREE.Vector3( 0, -length, 0 ), 0x00FF00, true ) ); // -Y
        axes.add( buildAxis( new THREE.Vector3( 0, 0, 0 ), new THREE.Vector3( 0, 0, length ), 0x0000FF, false ) ); // +Z
        axes.add( buildAxis( new THREE.Vector3( 0, 0, 0 ), new THREE.Vector3( 0, 0, -length ), 0x0000FF, true ) ); // -Z

        return axes;

    }
</script>
</body>
</html>

**Comment by dvdoug** [comment]
As I understand it, there is nothing to do here. Please reopen if I've misunderstood
