### ISSUE TITLE
Find best Box(es) for given Items

### ISSUE THREAD

**Issue by styler2go** [dvdoug/BoxPacker#181]
Is it also possible to have a set of Boxes and a set of Items and find the best combination of the two?

According to the docs i can either 
1. pack a set of items into a GIVEN set of boxes
2. check if a set of items fit into a GIVEN box

What to do if i want to find the best fitting box(es) for the given items?

**Comment by dvdoug** [comment]
Unless I've misunderstood the question, that is what this library does in (1): you supply all the boxes you have available, and the library returns a result which uses them as efficiently as it can

**Comment by maxtorchel** [comment]
maybe this mean, that if i want to give a some priority to boxes, ie box price, library use a boxes with highest priority, ie lowest price, first. this will be 5d box packer)

**Comment by dvdoug** [comment]
There is an inbuilt assumption inside `Packer` when calculating the most efficient combination that smaller boxes are cheaper than larger boxes and a single box is cheaper than having multiple boxes. If that's not true for your situation and you need custom "best" options, then you'd need to create your own wrapper around `VolumePacker` to select the best option for you.

**Comment by maxtorchel** [comment]
thats great option, maybe you can place an example in advanced doc section for this situation.
