### ISSUE TITLE
v3.3+ noticeably slower to pack

### ISSUE THREAD

**Issue by trowski** [dvdoug/BoxPacker#182]
After upgrading from 3.2.2 to 3.4, I noticed packing speed decreased significantly – at least 2 to 3 times slower. The packager is able to select from 7 boxes. Speed decreases significantly after only ~30 items and gets very noticeable as the item count exceeds 100. None of the items are constrained for position or being packed with other items.

Boxes:
410 x 310 x 310mm
410 x 310 x 260mm
410 x 310 x 205mm
310 x 310 x 210mm
310 x 210 x 210mm
310 x 210 x 155mm
210 x 160 x 105mm

Items: 200 – 150 x 100 x 100mm items.

**Comment by imjohnbon** [comment]
Just wanted to note that I am also seeing this speed issue. I also have 7 boxes. ~25 items were taking over 3 minutes to pack. ~14 items was taking around 40 seconds.

Downgrading from 3.4 to 3.2 reduced that to 6 and 16 seconds respectively.

**Comment by imjohnbon** [comment]
Just wanted to follow up here since my last comment didn't offer much in terms of replicating the issue. Downgrading to 3.2.2 solved the minor speed issues I was having with small amounts of items, but _any_ version of the package (2.x or 3.x) seems to be unable to handle 400+ items. It completely times out NGINX after around 5 minutes. I've seen comments in other issues regarding 1000's of items being processed, so it seemed like it should be possible, but ~400 has been timing out for me entirely.

Here is a gist with the setup for quick replication: https://gist.github.com/imjohnbon/f373498014e35e9802487b996474690f

All lengths/widths/depths are in millimeters and all weights are in grams.

**Comment by imjohnbon** [comment]
Another follow up here 😄 After investing my above sample a little further, I realized that a fairly significant percentage of the items in the list were throwing `ItemTooLargeException`'s.

So I took a closer look at the `InfalliblePacker` and noticed that it works like this:

```
        $itemList = clone $this->items;

        while (true) {
            try {
                return parent::pack();
            } catch (ItemTooLargeException $e) {
                $this->unpackedItems->insert($e->getItem());
                $itemList->remove($e->getItem());
                $this->setItems($itemList);
            }
        }
```

Basically, it keeps trying to pack over and over again, separating items that are too big each time it encounters one. What that means though is that if you have 400 items, and 50 of them are too large to pack, it's going to try and fail to pack 50 times before it successfully packs itself.

As I thought about it more, I started to wonder why I needed to even let the packer try to pack items that are too large. I have the sizes of my shipping boxes and the sizes of my items before even attempting to pack, so theoretically the ones that are clearly too large could be filtered out before a packing attempt.

So my solution was the build my own custom packer based on the InfalliblePacker, which makes an initial attempt to filter out items that are too large before packing. If it encounters a package that's too large while packing it still handles that, but it at least doesn't have to fail 50 times.

Here's a basic stub of that code:

```
use DVDoug\BoxPacker\ItemList;
use DVDoug\BoxPacker\ItemTooLargeException;
use DvDoug\BoxPacker\PackedBoxList;
use DVDoug\BoxPacker\Packer as BoxPacker;

class CustomPacker extends BoxPacker
{
    protected $unpackedItems;

    public function __construct()
    {
        $this->unpackedItems = new ItemList();
        parent::__construct();
    }

    public function getUnpackedItems(): ItemList
    {
        return $this->unpackedItems;
    }

    public function predetermineTooLargeItems($itemList)
    {
        /** Logic to remove items predetermined to be too big */
        
        return $itemList;
    }

    public function pack(): PackedBoxList
    {
        $itemList = $this->predetermineTooLargeItems(clone $this->items);
        $this->setItems($itemList);

        while (true) {
            try {
                return parent::pack();
            } catch (ItemTooLargeException $e) {
                $this->unpackedItems->insert($e->getItem());
                $itemList->remove($e->getItem());
                $this->setItems($itemList);
            }
        }
    }
}
```

The query that was previously timing out was reduced to around 3 seconds with this in place.

**Comment by dvdoug** [comment]
@trowski I think the commit I added yesterday should resolve your issue

**Comment by dvdoug** [comment]
@imjohnbon ah, you have the worst of all cases there - high quantity of distinct items AND a high quantity that don't fit. Optimisations coming up

**Comment by trowski** [comment]
@dvdoug Thank you for looking into this. I can confirm that `3.4.1` resolved the issue I was having with packing many very similar items. I didn't run any benchmarks, but it now appears to be faster than `3.2.x`.

**Comment by dvdoug** [comment]
Awesome! Thanks for letting me know
