### ISSUE TITLE
Feautre Request - Disable any rotation

### ISSUE THREAD

**Issue by victorhramos-dev** [dvdoug/BoxPacker#183]
Is that possible to pack items disabling any rotation? Not even x/y

**Comment by dvdoug** [comment]
Not through a setting, but it should be possible to add this via a custom constraint. What's the use case you have in mind?

**Comment by dvdoug** [comment]
Actually, I'm about to make a change to the packing algorithm that would render that constraint example obsolete.

Am still interested in the use case though in case this can be added in a different way

**Comment by victorhramos-dev** [comment]
Sorry for the late answer.
It's because i used your library to fit items in a 2D scenario.
Have set all boxes and items with 1 mm of depth to make it 2D.

Worked nice but my real scenario don't have the rotation (it's a game, inventory of items) so disable the rotation in any axis would be a solution.

Thanks :)

**Comment by victorhramos-dev** [comment]
https://github.com/dvdoug/BoxPacker/issues/175#issuecomment-544129267

**Comment by dvdoug** [comment]
It would be fairly easy to add into the library code, the issue will be that it will require additional data from the `Item` object to trigger the correct mode, which will mean changing the interface and therefore causing backwards incompatibility. I'll keep this open for v4.

In the meantime, you'd need to fork the code and delete the line at https://github.com/dvdoug/BoxPacker/blob/master/src/OrientatedItemFactory.php#L158
