### ISSUE TITLE
How can i get package postion information?

### ISSUE THREAD

**Issue by harikarank** [dvdoug/BoxPacker#19]
First thanks for your great algorithm..
How can i get information each box fit in big box postion?
For Eg:
Big Box- 500,500,500(W,L,H)
Package 1-100,100,100(W,L,H)
Package 2-200,200,200(W,L,H)
How can i get postion to place Pacakge 1 and Package 2 in Big Box

**Comment by JHGitty** [comment]
I need this feature, too! #29
