### ISSUE TITLE
Wrong Packing due to items not rotated

### ISSUE THREAD

**Issue by alexvremja** [dvdoug/BoxPacker#190]
Hi!
Really a very good work, but I have an issue:

I have a Box of
	200x250x250 mm where I have to put some items with size of
	200x50x60: it should contain up to 20 pcs since:
	200x50 x 5 = 200x250 so it fully uses the bottom, and I can create 4 layers since 60x4=240<250

but with these settings I get the wrong result (the left in the first picture):

	$packer->addBox(new TestBox('Small_Box',250,250,200,100,250,250,200,50000));
	$packer->addItem(new TestItem('Coffee_01',200,60,50,200,false),20);

while if I shuffle the dimensions and set to true the $keepFlat option of the Items
	$packer->addItem(new TestItem('Coffee_01',50,60,200,200,true),20);

I get the right result (the right in the first picture)

![Packing_issue_2](https://user-images.githubusercontent.com/15941605/73473585-4d9ff600-438d-11ea-8f16-2ed2daa58425.jpg)
![Packing_issue](https://user-images.githubusercontent.com/15941605/73473594-509ae680-438d-11ea-9040-7ff668b9a9ca.jpg)

Clearly the target is to get the right result without setting the $keepFlat option to true since rotation is one of the most important feature of the tool.

I tried to understand the logic of the algorithm but without success so far.
Can suggest a solution?
Thanks a lot
Jan

**Comment by dvdoug** [comment]
Hi @alexvremja 

I can confirm I can reproduce this, so I'll take a look and see if I can figure out what's going wrong

**Comment by alexvremja** [comment]
While I was trying to find the bug I discovered that shuffling the dimensions of the Box and of the item it works also with `$keepFlat=false`:

```
$packer->addBox(new TestBox('Small_Box',20,25,25,100,20,25,25,50000));
$packer->addItem(new TestItem('Coffee_01',6,5,20,200,false),20);
```
Do not know if it can helps...

Thanks

**Comment by dvdoug** [comment]
There are 2 inter-related issues that are in play here with this case.

1) The orientation that works most efficiently (the one that works with keep flat) has the items orientated so that the longest dimension is vertical. When 3D rotation is enabled this orientation is being excluded from futher processing for being unstable/liable to tipping. 

2) When I bypass the stability calculation so the known-best orientation is considered viable, the algorithm is currently preferring a different one anyway on this particular testcase.

I'm still trying to work out the the right set of parameters here to use in decision making - so far my attempts that get this particular testcase working better are regressing many others.

**Comment by alexvremja** [comment]
Hi!
Thanks for your efforts.

I found that [this](http://betterwaysystems.github.io/packer/demo/#) algorithm returns the right result (at least on the suggested example and few others)

It is based on react/javascript, but perhaps it can suggest you a solution for your project.

Regards

**Comment by dvdoug** [comment]
Hi @alexvremja 

This specific example and others like it should be resolved in the next release (specifically, where the item is perfect fit in that particular rotation).

For cases where doing that would be a close fit, but not an absolutely perfect one I haven't found a heuristic yet that I'm happy with but I'll keep looking.

**Comment by alexvremja** [comment]
Great!
When do expect next release will be... released?
Thanks again for your efforts!

**Comment by dvdoug** [comment]
There's a couple more things I want to address, but aiming for this week

**Comment by alexvremja** [comment]
Great!
Thanks a lot again!

**Comment by alexvremja** [comment]
Hi, Installed and first test are positive.
Thanks again.
