### ISSUE TITLE
Different results depending on the order of declaration of width, length and depth

### ISSUE THREAD

**Issue by cdurovray** [dvdoug/BoxPacker#191]
Hi,

I have different results with one box and two identicals items depending on the order of declaration

My Box is 400 x 300 x 200 
$packer->addBox(new TestBox('B 1', 400, 300, 200, 10, 400, 300, 200, 1000));

Item is 400 x 150 x 200, so normally I could set two items in one box

If I try 
$packer->addItem(new TestItem('Item 1', 400, 150, 200, 10, false), 2);
=> OK in one BOX

$packer->addItem(new TestItem('Item 1', 400, 200, 150, 10, false), 2);
=> KO (The result is two boxes)

$packer->addItem(new TestItem('Item 1', 200, 400, 150, 10, false), 2);
=> KO (The result is two boxes)

$packer->addItem(new TestItem('Item 1', 400, 150, 200, 10, false), 1);
$packer->addItem(new TestItem('Item 2', 400, 200, 150, 10, false), 1);
=> OK

$packer->addItem(new TestItem('Item 1', 400, 200, 150, 10, false), 1);
$packer->addItem(new TestItem('Item 2', 400, 150, 200, 10, false), 1);
=> KO (The result is two boxes)

Is there an order for the dimensions of boxes and items ?

Thanks a lot

Chris

**Comment by alexvremja** [comment]
I.M.H.O. This is due to an issue in the rotation routine: see my issue #190 
it seems the routine does not test some combinations that requires items rotation:
and this can return wrong results
But if you change the initial position of the item in the way that such rotation is not required the routine returns the right solution: but it is a random result.

**Comment by dvdoug** [comment]
Hi @cdurovray 

This already works as expected on master, so the next release should solve this for you. I've added these examples into the test suite to avoid any accidental regression in the future

**Comment by dvdoug** [comment]
Also, thanks for the report!
