### ISSUE TITLE
Another issue

### ISSUE THREAD

**Issue by cdurovray** [dvdoug/BoxPacker#192]
Hi,

I find a strange issue
I test with one box 400 x 300 x 200

$packer->addBox(new TestBox('Box', 400, 300, 200, 10, 400, 300, 200, 1000));

And four items
$packer->addItem(new TestItem('Item 1', 350, 250, 55, 10, false));
$packer->addItem(new TestItem('Item 2', 225, 180, 55, 10, false));
$packer->addItem(new TestItem('Item 3', 265, 195, 30, 10, false));
$packer->addItem(new TestItem('Item 4', 260, 190, 30, 10, false));

=> the four items fit in the box

but if I reduce certain dimensions it will no longer fit in the box, theses examples doesn't fit : 

$packer->addItem(new TestItem('Item 1', **345**, 250, 55, 10, false));
$packer->addItem(new TestItem('Item 2', 225, 180, 55, 10, false));
$packer->addItem(new TestItem('Item 3', 265, 195, 30, 10, false));
$packer->addItem(new TestItem('Item 4', 260, 190, 30, 10, false));

$packer->addItem(new TestItem('Item 1', 350, 250, 55, 10, false));
$packer->addItem(new TestItem('Item 2', 225, 180, **50**, 10, false));
$packer->addItem(new TestItem('Item 3', 265, 195, 30, 10, false));
$packer->addItem(new TestItem('Item 4', 260, 190, 30, 10, false));

Whereas if I increase these same dimensions it fits in the box

$packer->addItem(new TestItem('Item 1', **360**, 250, 55, 10, false));
$packer->addItem(new TestItem('Item 2', 225, 180, 55, 10, false));
$packer->addItem(new TestItem('Item 3', 265, 195, 30, 10, false));
$packer->addItem(new TestItem('Item 4', 260, 190, 30, 10, false));

$packer->addItem(new TestItem('Item 1', 350, 250, 55, 10, false));
$packer->addItem(new TestItem('Item 2', 225, 180, **60**, 10, false));
$packer->addItem(new TestItem('Item 3', 265, 195, 30, 10, false));
$packer->addItem(new TestItem('Item 4', 260, 190, 30, 10, false));

Thanks you

Chris

**Comment by dvdoug** [comment]
This one is also already fixed on master so will be resolved by the next release. Thanks for the report!
