### ISSUE TITLE
Items fits in box when they should't

### ISSUE THREAD

**Issue by zukovasmartynas** [dvdoug/BoxPacker#195]
`        $packer = new Packer();

        $packer->addBox(new Box('[Box]', 302, 302, 102, 0, 300, 300, 300, 100000));
        $packer->addItem(new Item('Item 1', 300, 300, 50, 1, false), 2); // item, quantity
        $packer->addItem(new Item('Item 2', 300, 300, 50, 1, false), 1);

        /** @var PackedBoxList $packedBoxes */
        $packedBoxes = $packer->pack();

        echo "These items fitted into " . count($packedBoxes) . " box(es)" . PHP_EOL;
        foreach ($packedBoxes as $packedBox) {
            $boxType = $packedBox->getBox(); // your own box object, in this case TestBox
            echo "This box is a {$boxType->getReference()}, it is {$boxType->getOuterWidth()}mm wide, {$boxType->getOuterLength()}mm long and {$boxType->getOuterDepth()}mm Depth" . PHP_EOL;
            echo "The combined weight of this box and the items inside it is {$packedBox->getWeight()}g" . PHP_EOL;

            echo "The items in this box are:" . PHP_EOL;
            $packedItems = $packedBox->getItems();

            echo 'Used Width: ' .  $packedBox->getUsedWidth() . PHP_EOL;
            echo 'Used Length: ' .  $packedBox->getUsedLength() . PHP_EOL;
            echo 'Used Depth: ' .  $packedBox->getUsedDepth() . PHP_EOL;

            /** @var PackedItem $packedItem */
            foreach ($packedItems as $packedItem) {
                echo $packedItem->getItem()->getDescription() . PHP_EOL;
            }
        }`

Only Item1 should be able to fin in boxes, and Item2 - should be going to new box.
But now it looks like all items are fitting well in the box, even when they clearly now. 
Tried with 3.3.0 and 3.5.2  versions. Same result.  Tried to draw box and fit my items - its impossible to fit them all in one box. 
Not sure if this is a bug or I'm doing something wrong. Could you check this one?

**Comment by dvdoug** [comment]
In that example, it looks like there is an outer depth of 102, but the inner depth is still listed as 300? It's the inner dimensions that are used for packing.

The items would indeed fit a 300x300x300.

**Comment by zukovasmartynas** [comment]
Oh my dumb head. Thanks for pointing out. Seems my head doesn't work on the friday.
