### ISSUE TITLE
Adding more items - will reduce boxes amount.

### ISSUE THREAD

**Issue by zukovasmartynas** [dvdoug/BoxPacker#196]
Hello again, now I got something tricky. These will fit into two boxes

$packer = new Packer();
$packer->addBox(new Box('[Box]', 360, 620, 370, 1, 360, 620, 370, 29000));
$packer->addItem(new Item('C5 240 x 165 mm, 1000 vnt.', 259, 375, 99, 5440, false), 4);
$packer->addItem(new Item('170x230+30mm', 200, 300, 10, 194, false), 12);
$packer->addItem(new Item('50 mm x 66 m, ruda', 100, 100, 50, 165, false), 12);
$packedBoxes = $packer->pack();
echo "These items fitted into " . count($packedBoxes) . " box(es)" . PHP_EOL;

But adding additional two items - makes it fit into the one box
$packer->addItem(new Item('175 x 255, B5', 130, 210, 30, 391, false), 2);

Not sure how adding more items causes items to fit into the smaller space.

**Comment by dvdoug** [comment]
Hi @zukovasmartynas 

Annoyingly, that does sometimes happen - it's just the nature of heuristics, they're never absolutely perfect. There's not a single algorithm in the world that gets the best packing result every single time. 😞 

This particular example does already work as expected on master though, so it will be resolved for you in the next release.

**Comment by zukovasmartynas** [comment]
I'm thankful for your response, going to wait for a next release :)
