### ISSUE TITLE
Bug says Item is too large to fit, but item is small why?

### ISSUE THREAD

**Issue by harikarank** [dvdoug/BoxPacker#20]
Bug says Item is too large to fit, but item is small why?
<b>Code:</b>
  <i>$packer->addBox(new TestBox('Le grande box', 100, 100, 300, 1, 100,100, 300, 1500));
  $packer->addItem(new TestItem('Item 1', 150, 50, 50, 20));</i>

<b>Bug:</b>
<strike>Fatal error: Uncaught exception 'RuntimeException' with message 'Item Item 1 is too large to fit into any box' in C:\xampp\htdocs\box\Box.php:511 Stack trace: #0 C:\xampp\htdocs\box\Box.php(467): Packer->doVolumePacking() #1 C:\xampp\htdocs\box\1.php(11): Packer->pack() #2 {main} thrown in C:\xampp\htdocs\box\Box.php on line 511</strike>

![1](https://cloud.githubusercontent.com/assets/8309169/5157686/4aaf9eae-7341-11e4-94b7-7eb62a056fa5.png)

Also I saw issue No 18
Link: https://github.com/dvdoug/BoxPacker/pull/18  - It is working

**Comment by dvdoug** [comment]
"Dumb" 3D rotation is now on master and it (or something better) will be included in the next release when I've finished testing and am happy with how it works.

I've added this testcase to the testsuite now that it passes :)
