### ISSUE TITLE
Force BoxPacker to pack the same items in the same boxes

### ISSUE THREAD

**Issue by Delfins** [dvdoug/BoxPacker#203]
Hi, first of all: Amazing. Honestly. This is one of the best libraries that I've met so far. Really cutting edge.
I would need to ask BoxPacker the following: suppose I need to pack 50 items A and 40 items B and 200 Items C. Now BoxPacker spreads items A, B, C in the way that better fits the available space. Which is correct. But I would like to add a constrain, like: "pleas,e while doing the packing, try to keep together the items of the same type".
So that the most possible items A will be packed in the same box, and not spreaded few in box 1, few in box 4, some in box 30, etc. For logistics reasons, I need that items of the same type, are packed in the same boxes.
Is this a constraing somehow applicable to your library?

Thanks,
Guido

**Comment by dvdoug** [comment]
Hi @Delfins 

Thanks for the 👍 !

This might be the weight redistribution feature (https://www.boxpacker.io/en/stable/weight-distribution.html) that is impacting you, can you try turning it off and let me know if you get a result that you're happier with?

**Comment by Delfins** [comment]
Hi @dvdoug thanks for the answer! You suggetsion seemed working but no, I'm still having the issue. Basically what I would need is that the system is able to keep (as much as possible) in the same box the items that are the same. Any chance it's doable? :-) Thanks

**Comment by dvdoug** [comment]
For clarity - let's say from your 50 items A and 40 items B and 200 Items C.

* 1st Box - 20 item A have been packed so far
* There is not room for a 21st Item A, but there is room for Item C
* You do not want Item C to be packed. Item C (or Item B) can only start to be packed once there are no more Item A left
* This may mean additional boxes and that is OK?

**Comment by Delfins** [comment]
Exactly! You got the requirement

**Comment by progettoautomazione** [comment]
@dvdoug great update! Thanks so much! Cheers
