### ISSUE TITLE
ConstrainedPlacementItem::canBePacked is passed a WorkingVolume instead of a box

### ISSUE THREAD

**Issue by bob2021** [dvdoug/BoxPacker#204]
Hi, 
Using version 3.6 and 3.5.1 (I haven't tested any others) I have found that the `$box` argument of `ConstrainedPlacementItem::canBePacked` is sometimes passed a `WorkingVolume` instead of one of my boxes.  It looks like this happens when `OrientatedItemSorter::calculateAdditionalItemsPackedWithThisOrientation` is generating a lookahead cache entry.

Is this the expected behaviour and I'm supposed to be ignoring those calls that are passed a `WorkingVolume` or should the original box actually be passed through?

**Comment by dvdoug** [comment]
Ah, yes I can see how that could be confusing. You should honour it exactly as you would as if it were one of your own boxes (unless, thinking about it as I type...you can't). Later on after the lookahead has finished, you should be seeing a second callback with the same positional parameters but for the actual box.

**Comment by bob2021** [comment]
Thanks, the problem was that I needed to check if the box is suitable for the item. For example some of the items being packed may require a specific box, but with the `WorkingVolume` it's not possible to determine that.

So if the same call will be made again later with the original box, is it safe to just return true for the lookahead calls?

**Comment by dvdoug** [comment]
Yeah that should be fine as a workaround. I'll need to have a think about what to do with the lookahead code in this case, it might be that it should skip the callback entirely.

**Comment by dvdoug** [comment]
(thanks for reporting it)

**Comment by bob2021** [comment]
Thanks!
