### ISSUE TITLE
No stacking interface doesn't work

### ISSUE THREAD

**Issue by Ren14** [dvdoug/BoxPacker#205]
Hello dvdoug!

I am working with your development, and I wanted to congratulate you on the work done.

I am using the library to optimize the calculation of boxes, for a client that we have in the company where I work.

This client sells perfumery products, and they are packaged in plastic containers. These containers cannot be stacked in the boxes, as they could tip over and spill their liquid.

Regardless of the space left high, the products must be ordered occupying the entire length and width of the box.

I tried the example https://www.boxpacker.io/en/stable/advanced-usage.html#example-don-t-allow-batteries-to-be-stacked but failed to get it working.

I analyzed and implemented the development as you show it in issue # 156, but I couldn't get it to work.

Could you help me or give me an example?

Thank you.

**Comment by dvdoug** [comment]
Hi @Ren14 

There's an example in the test suite that 🤞 works - the constraint code is https://github.com/dvdoug/BoxPacker/blob/master/tests/Test/ConstrainedPlacementNoStackingTestItem.php and the code that's testing it is at https://github.com/dvdoug/BoxPacker/blob/master/tests/VolumePackerTest.php#L92

From your description I think you need a less complex constraint, simply `return $proposedZ === 0` should do if you require the items to be on the bottom of the box.

Does that help at all?

**Comment by dvdoug** [comment]
(that's after checking the item type if not all items are perfume of course)

**Comment by dvdoug** [comment]
Am assuming you got this to work, please reopen if not
