### ISSUE TITLE
ConstrainedPlacementItem::canBePacked() is not working in some cases

### ISSUE THREAD

**Issue by bob2021** [dvdoug/BoxPacker#206]
Hi, 
Using version 3.6 I've noticed that sometimes constrained items are packed together even when `canBePacked` returns false.

Here's an example that packs 3 constrained items into a single box even though the limit is 2:

```php
ConstrainedPlacementByCountTestItem::$limit = 2;
$packer = new Packer();
$packer->addBox(new TestBox('Box', 6, 10, 6, 0, 6, 10, 5, PHP_INT_MAX));
$packer->addItem(new ConstrainedPlacementByCountTestItem('ConstrainedItem', 1, 1, 1, 1, false), 3);
$packer->addItem(new TestItem('RegularItem', 2, 4, 1, 2, false), 5);
$packedBoxes = $packer->pack();
```

Note that in my production code, all items are `ConstrainedPlacementItems` and I see the same problem so I don't think the problem is caused by the mix of item types in the example above.

I have tried to trace through the code to see why this is happening but haven't been able to pinpoint the exact cause.  I can confirm that the value returned by `canBePacked` is correct, so I think either the `PackedItemList` passed to `canBePacked` is incorrect or the return value is being ignored in certain cases. 

This doesn't happen all the time, just in some cases, but I'm not really sure what triggers it.  My best guess so far is that the constraint is being applied to layers rather than the entire box, though that really is just a guess at the moment.

**Comment by dvdoug** [comment]
Confirmed. Will try to figure this out ASAP.

**Comment by dvdoug** [comment]
Thanks for the testcase @bob2021, that helped a lot in narrowing it down. I'll try and tag a new version with the fix in it tonight.

**Comment by bob2021** [comment]
That's great! Thanks
