### ISSUE TITLE
need less item distribution between box for packing

### ISSUE THREAD

**Issue by praveenpalanivel** [dvdoug/BoxPacker#207]
![image](https://user-images.githubusercontent.com/5801055/86220839-c8ba4200-bba1-11ea-965f-4e146ac7aaf3.png)

here there is possible to **pants (also shorts)** as separate box still I have remained more than 20, in this case, 20 as sperate box balance 1 need to join with other balance quantity.

in the same case also tops (except jackets) I have 24, in same case 20 as separate box and 4 balance can join with other balance quantity.

in this case, the balance of top 4 + balance of pants 1 can goes in a separate box.

in simple words:
first, need to create the separate box for the individual items which are fulfilled, after the that all balance quantity can combine together create a separate box.

for example 

pant 47, top 43, bag 25
in this case, all box has the same package dimension. it fills 20 items per box.
inner box size is: 100x100x100
item dimension is: 100x100x5

output needed:
2 box with only pants
2 box with only top
1 box with bag
1 box with 7pant, 3 top, 5 bags

please guide me to solve this type of packing

thanks

Hi @Delfins 

Thanks for the 👍 !

This might be the weight redistribution feature (https://www.boxpacker.io/en/stable/weight-distribution.html) that is impacting you, can you try turning it off and let me know if you get a result that you're happier with?

_Originally posted by @dvdoug in https://github.com/dvdoug/BoxPacker/issues/203#issuecomment-627559223_

**Comment by dvdoug** [comment]
Hello @praveenpalanivel 

I think your requirement is exactly the same as #203 so is not currently supported. I'll mark this as a duplicate, please watch #203 for any updates.
