### ISSUE TITLE
What if my situation that reducing box count is best selection?

### ISSUE THREAD

**Issue by sctaix** [dvdoug/BoxPacker#208]
Hi, dvdoug! First of all, thank you for your BoxPacker :)

In my case, reducing box count is better than use multiple small boxes for saving net shipping cost.

For example,

1 small box + 1 medium box
1 large box (win)

1 small box + 1 medium box + 1 large box
2 large box (win)

2 small boxes + 1 large box
1 medium box + 1 large box (win)

2 small boxes + 2 medium boxes
3 large box (win)

How could I configure it? is it possible?

Please, let me know little more detail about your solution!

Thank you!

**Comment by dvdoug** [comment]
Hello @sctaix.

Using the lowest count of boxes is precisely what already happens 😃

**Comment by dvdoug** [comment]
Assuming that answered the question, please reopen if not
