### ISSUE TITLE
Find 1 box that will fit all the items

### ISSUE THREAD

**Issue by AhtashamImtiyaz** [dvdoug/BoxPacker#212]
Hi, Is there a way to get only 1 box that will going to fit all the given items? For example, we got a list of boxes and list of items that we want to add in only one box.

**Comment by dvdoug** [comment]
Hello @AhtashamImtiyaz 

Assuming that one of your list of boxes is actually large enough to hold all of the items, that's exactly what should be returned already - the packing solution will return just that single box. It will only return multiple boxes where there isn't a single box large enough.

Do you have an example where you think that isn't happening?

**Comment by dvdoug** [comment]
Am assuming you got this to work, please reopen if not
