### ISSUE TITLE
Box items to 3D Canvas

### ISSUE THREAD

**Issue by lojadev5** [dvdoug/BoxPacker#213]
Does anyone have something that can generate a 3D canvas showing all the items as cubes in the box already prepared as I see in images here, that you can share or help me create?
Thanks!!

**Comment by neodisco** [comment]
I'm very interested in this, happy to collaborate on it with you. I would really love to see a nice revolving 3d translucent representation of how the packing was done.

**Comment by lojadev5** [comment]
@dvdoug @neodisco 
https://cssdeck.com/labs/html5-canvas-3d-cubes

This code I believe is already half done, but as much as I read I can barely understand kkk. If we could adapt a function: draw (x, y, z, width, lenght, height) would be perfect!

**Comment by neodisco** [comment]
I will let you know I have had some great success using https://www.babylonjs.com/, and have it working well, as well as I have had dreamed about it for the last 5 years. However it's currently based on a higher level abstraction of my domain over the top of BoxPacker using lots of my own objects, so I can't share the code. However when I can find the time I will make and publish a fully working demo here that works with BoxPacker.

**Comment by dvdoug** [comment]
Literally no idea what I'm doing with this 3D stuff (also my JS is very rusty), but the next release will include an experimental visualisation tool. 

Suggestions on improving it are welcome!
