### ISSUE TITLE
Force all long items to be placed in one box

### ISSUE THREAD

**Issue by pikil** [dvdoug/BoxPacker#218]
Hi Doug,
Would that be possible to force place all the items in the first box which is specifically chosen for the long items?

Like in the example below, the bottom box is the initial one for long items (and any short ones fitting into the unused space) and all the remnants would go to the second smaller box.
However, because there is a long item among the remnants the second box becomes long as well when it should remain short really.

![Screen Shot 2021-01-06 at 11 12 08 AM](https://user-images.githubusercontent.com/26779040/103706616-f7621b00-5011-11eb-8646-c74d2aeadb32.png)
![Screen Shot 2021-01-06 at 11 12 21 AM](https://user-images.githubusercontent.com/26779040/103706625-fa5d0b80-5011-11eb-8c80-901a18ef8ddc.png)

Many thanks for any help!

**Comment by dvdoug** [comment]
Hi @pikil 

Happy to take a look, but have you got some sample code I can use to reproduce the sample with?

**Comment by pikil** [comment]
Hi @dvdoug ,
Sure, please see below:

```
$packer = new InfalliblePacker();
$packer->setMaxBoxesToBalanceWeight(0); // Setting this one to place all the heavy boxes into one 

$packer->addBox(new Box(
      'longBox',
      2200, 2200, // Box length
      1000, 1000, // Box width
      1500, 1500, // Box height
      40000, // Box weight
      800000 // Items weight
    ));

$items = _sort_array_by_multiple_vals($items, 'length', SORT_DESC, 'weight', SORT_DESC); // Internal method - here, we are ordering by length and then by weight to make sure the biggest/heaviest items go to the bottom.

foreach ($items as $item)
      for ($i = 0; $i < $item['reservation_qty']; $i++)
        $packer->addItem(new Item(
          $item['id'] . '-' . ($i + 1), // Item ID
          $item['length'], // Item length
          $item['width'], // Item width
          $item['height'], // Item height
          intval($item['weight'] * 1000), // Item weight
          true, // KeepFlat
          '' // Item SKU
        ));

$boxes = $packer->pack();

$long_box = $pallets[0]; // Code minified here for better readability, expected to collect all the long items due to the order and disabled weight distribution
$small_box = $pallets[1]; // This box will be re-calculated with the smaller Box sizes.  Expected to have only remnants which didn't fit into the long box

```

Here, because of of setMaxBoxesToBalanceWeight(0), all the long items are expected to go to the first pallet, right?

As a recommendation, I think, ideally, canBePacked() should just receive box index so we can make sure that the specific items go only to the first box for example.

Many thanks!

**Comment by dvdoug** [comment]
Hi @pikil 

You didn't include the actual item dimensions for everything in those boxes so I can't run the precise packing you did. Please note though when you call `$packer->addItem()`, that does not respect the pre-sorting you've done, it makes it's own determinations. If you want your own sort order respected, you'll need to do something like this:

```
$itemsAsArray = [];
foreach ($items as $item) {
  $itemsAsArray[] = new Item(...);
}
$itemsAsItemList = ItemList::fromArray($itemsAsArray, true); // second flag indicates pre-sorted
$packer->setItems($itemsAsItemList);
``

I'm happy to take a look at why the same size items didn't stay together if you can supply the extra detail?

**Comment by pikil** [comment]
Ah, nice! Thank you Doug! That customised sorting is just perfect!

**This one is a good one after applying your suggestions about custom sorting:**
![Screen Shot 2021-03-09 at 12 38 41 PM](https://user-images.githubusercontent.com/26779040/110396241-881dab80-80d4-11eb-9c00-fc2c96aaba6c.png)

Just for your information if you want to have a look on what has actually happening with the distribution, please see the items below.
Unfortunately, I do not have that exact example anymore, but you can just have a look at the new ones :)

**This one is without the custom sorting:**
![Screen Shot 2021-03-09 at 12 37 51 PM](https://user-images.githubusercontent.com/26779040/110396284-9ff52f80-80d4-11eb-82c0-31ac4862f3de.png)


* measurements are in mm and kgs

Many thanks again!

$items = [
['id' => 0-0, 'length' => 2260,'width' => 641,'height' => 30,'weight' => 16.1],
['id' => 0-1, 'length' => 2260,'width' => 641,'height' => 30,'weight' => 16.1],
['id' => 0-2, 'length' => 2260,'width' => 641,'height' => 30,'weight' => 16.1],
['id' => 1-0, 'length' => 2164,'width' => 609,'height' => 61,'weight' => 29.65],
['id' => 2-0, 'length' => 2143,'width' => 424,'height' => 32,'weight' => 9.5],
['id' => 3-0, 'length' => 969,'width' => 585,'height' => 175,'weight' => 44.2],
['id' => 3-1, 'length' => 969,'width' => 585,'height' => 175,'weight' => 44.2],
['id' => 3-2, 'length' => 969,'width' => 585,'height' => 175,'weight' => 44.2],
['id' => 3-3, 'length' => 969,'width' => 585,'height' => 175,'weight' => 44.2],
['id' => 3-4, 'length' => 969,'width' => 585,'height' => 175,'weight' => 44.2],
['id' => 3-5, 'length' => 969,'width' => 585,'height' => 175,'weight' => 44.2],
['id' => 3-6, 'length' => 969,'width' => 585,'height' => 175,'weight' => 44.2],
['id' => 3-7, 'length' => 969,'width' => 585,'height' => 175,'weight' => 44.2],
['id' => 3-8, 'length' => 969,'width' => 585,'height' => 175,'weight' => 44.2],
['id' => 3-9, 'length' => 969,'width' => 585,'height' => 175,'weight' => 44.2],
['id' => 4-0, 'length' => 718,'width' => 425,'height' => 122,'weight' => 29.65],
['id' => 5-0, 'length' => 677,'width' => 305,'height' => 62,'weight' => 6],
['id' => 5-1, 'length' => 677,'width' => 305,'height' => 62,'weight' => 6],
['id' => 5-2, 'length' => 677,'width' => 305,'height' => 62,'weight' => 6],
['id' => 5-3, 'length' => 677,'width' => 305,'height' => 62,'weight' => 6],
['id' => 5-4, 'length' => 677,'width' => 305,'height' => 62,'weight' => 6],
['id' => 5-5, 'length' => 677,'width' => 305,'height' => 62,'weight' => 6],
['id' => 5-6, 'length' => 677,'width' => 305,'height' => 62,'weight' => 6],
['id' => 5-7, 'length' => 677,'width' => 305,'height' => 62,'weight' => 6],
['id' => 5-8, 'length' => 677,'width' => 305,'height' => 62,'weight' => 6],
['id' => 5-9, 'length' => 677,'width' => 305,'height' => 62,'weight' => 6],
['id' => 6-0, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 6-1, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 6-2, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 6-3, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 6-4, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 6-5, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 6-6, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 6-7, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 6-8, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 6-9, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-0, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-1, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-2, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-3, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-4, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-5, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-6, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-7, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-8, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-9, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-10, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-11, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-12, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-13, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-14, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-15, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-16, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-17, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-18, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 7-19, 'length' => 600,'width' => 150,'height' => 65,'weight' => 3.5],
['id' => 8-0, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-1, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-2, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-3, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-4, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-5, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-6, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-7, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-8, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-9, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-10, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-11, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-12, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-13, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-14, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-15, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-16, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-17, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-18, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-19, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-20, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-21, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-22, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-23, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-24, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-25, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-26, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-27, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-28, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-29, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-30, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-31, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-32, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-33, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-34, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-35, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-36, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-37, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-38, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-39, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-40, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-41, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-42, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3],
['id' => 8-43, 'length' => 200,'width' => 100,'height' => 100,'weight' => 0.3]
];

**Comment by pikil** [comment]
Hi Doug,
Many thanks for the suggestion, however the sorting by weight does not place all longest items into one big box:

![Screen Shot 2021-03-10 at 3 48 48 PM](https://user-images.githubusercontent.com/26779040/110568822-82999180-81b8-11eb-999e-c5533590cac0.png)

Generally, the idea was to get as little volume as possible for the boxes (useful for storage purposes, when the weight distribution is not important, but the size is :) ).

Cheers!
