### ISSUE TITLE
Your documentation is shit

### ISSUE THREAD

**Issue by treboralmasy** [dvdoug/BoxPacker#219]
You don't even have examples of how to use stuff. For example:
$packer->addBox(new TestBox('Le petite box', 300, 300, 10, 10, 296, 296, 8, 1000));

That doesn't tell you anything about the variables being passed.

**Comment by corbinu** [comment]
@treboralmasy That kind of behavior is completely unacceptable and toxic on any project let alone an open source one. I am betting you would never dare comment that way at work so don’t do so here where people are donating their time, attention, creations and intellectual property for your benefit. If you want to open a documentation PR then do so!

**Comment by treboralmasy** [comment]
"Toxic"?
Liberal confirmed.
For the record I would absolutely comment that way at work. Of course I also wouldn't release something with such poor documentation, but that's just me.

**Comment by corbinu** [comment]
That’s a horrible shame then. Learn to be a better person.

**Comment by treboralmasy** [comment]
Learn not to be offended by words.

**Comment by corbinu** [comment]
😂 wow lost already thats sad

**Comment by dvdoug** [comment]
Wow, @treboralmasy I certainly wouldn't want to be one of your co-workers if this is what you consider to be an acceptable way of communicating in a professional manner.

>Liberal confirmed.

Literally no idea how you get from someone asking you not to be a d*ck to somehow knowing their political leaning. Not that I understand what that would have to do with anything anyway 🤷‍♂️ 

If you don't like the word toxic, how about Respect (image is clickable)
[![](http://img.youtube.com/vi/GOzrAK4gOSo/0.jpg)](http://www.youtube.com/watch?v=GOzrAK4gOSo "Word of the day: Respect")


>Of course I also wouldn't release something with such poor documentation, but that's just me

![image](https://user-images.githubusercontent.com/1571110/105870635-5fdc6080-5ff0-11eb-93cc-8b55536f1f0e.png)
Right....we'll have to take your word for it since leading by example doesn't seem to be your thing

>You don't even have examples of how to use stuff. For example:
>$packer->addBox(new TestBox('Le petite box', 300, 300, 10, 10, 296, 296, 8, 1000));
>
>That doesn't tell you anything about the variables being passed.

You seem to have skipped to the examples without reading the 4 introductory paragraphs. Hint, they are there for a reason,

I'll quote them here because I'm feeling charitable

> BoxPacker is designed to integrate as seamlessly as possible into your existing systems, and therefore makes strong use of
> PHP interfaces. Applications wanting to use this library will typically already have PHP domain objects/entities representing
> the items needing packing, so BoxPacker attempts to take advantage of these as much as possible by allowing you to pass them
> directly into the Packer rather than needing you to construct library-specific datastructures first. This also makes it much
> easier to work with the output of the Packer - the returned list of packed items in each box will contain your own objects,
> not simply references to them so if you want to calculate value for insurance purposes or anything else this is easy to do.
> 
> Similarly, although it's much more uncommon to already have 'Box' objects before implementing this library, you'll typically
> want to implement them in an application-specific way to allow for storage/retrieval from a database. The Packer also allows
> you to pass in these objects directly too.
> 
> To accommodate the wide variety of possible object types, the library defines two interfaces ``BoxPacker\Item`` and
> ``BoxPacker\Box`` which define methods for retrieving the required dimensional data - e.g. ``getWidth()``. There's a good chance
> you may already have at least some of these defined.

And then, right at the top of the example, above the bit you quoted

> ```
>     <?php
>         use DVDoug\BoxPacker\Packer;
>         use DVDoug\BoxPacker\Test\TestBox;  // use your own object
> ```

**Comment by warmwhisky** [comment]
Can you explain what is going on in each item in `new TestBox('Le petite box', 300, 300, 10, 10, 296, 296, 8, 1000)`?

In each case there are 9 entries starting with a label?

I thought maybe the first three numbers were length width height, then maybe weight? then it might be inner length, width, height and then volume? but that would just be a wild guess.

**Comment by dvdoug** [comment]
https://github.com/dvdoug/BoxPacker/blob/master/tests/Test/TestBox.php#L64

**Comment by warmwhisky** [comment]
> https://github.com/dvdoug/BoxPacker/blob/master/tests/Test/TestBox.php#L64

Hmmm. Ok. So I need to create a class like TestBox.php to use this package? Where does that go?

**Comment by dvdoug** [comment]
Sorry, I don't understand what you mean by where does it go...it'll be in your code, so up to you?

**Comment by ServiceSector** [comment]
Woah did not expect to see this on github

**Comment by shakethatweight-simon** [comment]
> Is there any way to donate to the project?

@ServiceSector Yes you can donate to the project and I'm sure @dvdoug would appreciate that : https://github.com/sponsors/dvdoug

**Comment by dvdoug** [comment]
I would indeed, I don't do this for the money but all donations are _very_ much appreciated
