### ISSUE TITLE
Some spaces are left unused

### ISSUE THREAD

**Issue by erthiph** [dvdoug/BoxPacker#221]
So i tested some scenarios.
scenario 1 caps at: 
box: 200x200x200
item1 : 150x150x150 quantity 1
item2 : 50x50x50 quantity 31
but this should be able to pack item 2 quantity of 37

![box-1](https://user-images.githubusercontent.com/20819865/106553491-4fba0900-653b-11eb-85ae-9ddca1ebcfa5.PNG)

scenario 2 caps at: 
box: 40x40x40
item1 : 35x35x5 quantity 8
but this should be able to pack item 1 quantity of 10

![box2](https://user-images.githubusercontent.com/20819865/106553600-8132d480-653b-11eb-8f7e-8c037253b0e7.PNG)
![Capture](https://user-images.githubusercontent.com/20819865/106553607-83952e80-653b-11eb-96e6-441b6d7f9d16.PNG)

Any idea where or why ?

**Comment by dvdoug** [comment]
I'll take a look

**Comment by dvdoug** [comment]
Many thanks for this report @erthiph, debugging this revealed a logic case the core algorithm was accidentally overlooking
