### ISSUE TITLE
isSameDimensions performance

### ISSUE THREAD

**Issue by Gemorroj** [dvdoug/BoxPacker#225]
I have tested some performance for BoxPacker and have a small suggestion for faster compare dimensions.
See https://github.com/dvdoug/BoxPacker/blob/3.x/src/OrientatedItem.php#L130
For that case instead of sorting we can use [array_diff](https://www.php.net/array_diff) or [array_intersect](https://www.php.net/array_intersect).
See that project for more info https://github.com/Gemorroj/array-comparator-boxpacker

According to xdebug profiling, sorting called a lot of times and in summary spent notable time which we can improve.

**Comment by dvdoug** [comment]
Hi @Gemorroj 

Those results look very interesting, thank you very much for the suggestion! I'll certainly add investigating this to my todo list (am currently trying to get a rewrite of a different project over the line)

**Comment by dvdoug** [comment]
Hello @Gemorroj 

I've taken a look, and unfortunately I don't think the change is safe to make: if two dimensions have the same length, those array functions get confused: see https://3v4l.org/T9ZOJ

What do you think?

**Comment by Gemorroj** [comment]
Ye, I think you are right. I don't know how I missed it.

**Comment by dvdoug** [comment]
Thanks for the suggestion anyway 😃
