### ISSUE TITLE
Declaration Incompatible with DVDoug\BoxPacker\ConstrainedPlacementItem::canBePacked

### ISSUE THREAD

**Issue by mantisae** [dvdoug/BoxPacker#228]
Getting an error when trying to use the "don’t allow batteries to be stacked" example from the documentation to disallow stacking of furniture.

`
Fatal error: Declaration of UnstackableFurniture::canBePacked(Box $box, PackedItemList $alreadyPackedItems, int $proposedX, int $proposedY, int $proposedZ, int $width, int $length, int $depth) must be compatible with DVDoug\BoxPacker\ConstrainedPlacementItem::canBePacked(DVDoug\BoxPacker\Box $box, DVDoug\BoxPacker\PackedItemList $alreadyPackedItems, int $proposedX, int $proposedY, int $proposedZ, int $width, int $length, int $depth): bool`

I'm probably missing something simple and I appreciate any help in explaining where I went wrong.
Here's what I have so far using the current 3.9.0 release:

`<?php
	    
	error_reporting(E_ALL);
	ini_set('display_errors', TRUE);
	ini_set('display_startup_errors', TRUE);
	
	require_once($_SERVER["DOCUMENT_ROOT"] . '/vendor/autoload.php');
	
    use DVDoug\BoxPacker\Packer;
    use DVDoug\BoxPacker\Test\TestBox;  // use your own `Box` implementation
    use DVDoug\BoxPacker\Test\TestItem; // use your own `Item` implementation
    use DVDoug\BoxPacker\ConstrainedPlacementItem;
    
    class UnstackableFurniture implements ConstrainedPlacementItem
    {
        public function canBePacked(
            Box $box,
            PackedItemList $alreadyPackedItems,
            int $proposedX,
            int $proposedY,
            int $proposedZ,
            int $width,
            int $length,
            int $depth
        ) {
            $alreadyPackedType = array_filter(
                iterator_to_array($alreadyPackedItems, false),
                function (PackedItem $item) {
                    return $item->getItem()->getDescription() === 'Couch';
                }
            );

            /** @var PackedItem $alreadyPacked */
            foreach ($alreadyPackedType as $alreadyPacked) {
                if (
                    $alreadyPacked->getZ() + $alreadyPacked->getDepth() === $proposedZ &&
                    $proposedX >= $alreadyPacked->getX() && $proposedX <= ($alreadyPacked->getX() + $alreadyPacked->getWidth()) &&
                    $proposedY >= $alreadyPacked->getY() && $proposedY <= ($alreadyPacked->getY() + $alreadyPacked->getLength())) {
                    return false;
                }
            }

            return true;
        }
    }
    

    $packer = new Packer();

    /*
     * Add choices of box type - in this example the dimensions are passed in directly via constructor,
     * but for real code you would probably pass in objects retrieved from a database instead
     */
    //$packer->addBox(new TestBox('Unit Size', OuterWidth, OuterLength, OuterDepth, EmptyWeight, InnerWidth, InnerLength, InnerDepth, MaxWeight)); 
    $packer->addBox(new TestBox('5x10', 60, 120, 96, 0, 56, 112, 96, 0));
    $packer->addBox(new TestBox('10x10', 120, 120, 96, 0, 116, 112, 96, 0));
    $packer->addBox(new TestBox('10x20', 120, 240, 96, 0, 116, 234, 96, 0));

    /*
     * Add items to be packed - e.g. from shopping cart stored in user session. Again, the dimensional information
     * (and keep-flat requirement) would normally come from a DB
     */
    //$packer->addItem(new TestItem('Description', Width, Length, Height, Weight, KeepFlat), Quantity);
    $packer->addItem(new UnstackableFurniture('Couch', 36, 96, 42, 0, true), 1);
    $packer->addItem(new UnstackableFurniture('Recliner', 36, 36, 56, 0, true), 1);
    $packer->addItem(new UnstackableFurniture('Filing Cabinet', 30, 40, 72, 0, true), 1);
    $packer->addItem(new TestItem('Plastic Tub', 24, 36, 30, 0, true), 10);

    $packedBoxes = $packer->pack();

    echo json_encode($packedBoxes);
    
    ?>`

**Comment by dvdoug** [comment]
Hi @mantisae 

I think 🤞 this is a namespace conflict issue - you need to add ```use DVDoug\BoxPacker\Box; use DVDoug\BoxPacker\PackedItemList;```.

**Comment by mantisae** [comment]
unfortunately that did not work
I tried

```
use DVDoug\BoxPacker\Packer;

    use DVDoug\BoxPacker\Box; 

    use DVDoug\BoxPacker\PackedItemList;

    use DVDoug\BoxPacker\Test\TestBox;  // use your own `Box` implementation

    use DVDoug\BoxPacker\Test\TestItem; // use your own `Item` implementation

    use DVDoug\BoxPacker\ConstrainedPlacementItem;

```

**Comment by dvdoug** [comment]
Hi @mantisae

Looks like there was a small missing piece from the documentation examples, so thanks for reporting this and letting me know.
