### ISSUE TITLE
Packing Issue 

### ISSUE THREAD

**Issue by mrehssani** [dvdoug/BoxPacker#231]
Hi,

I faced the same issue with several others concerning the optimal packing, e.g the case is :
Box size of 30X20X20 and items as below:

    $packer->addBox(new TestBox('Box 2.5', 30,20, 20, 2, 30, 20, 20, 1000));

    $packer->addItem(new TestItem('Item 1', 20, 20, 2, 0, false), 4);
    $packer->addItem(new TestItem('Item 2', 8, 3, 2, 0, false), 4);
    $packer->addItem(new TestItem('Item 3', 10, 10, 10, 0, false), 4);
    $packer->addItem(new TestItem('Item 4', 12, 12, 10, 0, false), 2);
    $packer->addItem(new TestItem('Item 5', 6, 4, 2, 0, false), 2);

with 4 of Item 2 , its fine , when I add the 5th , says no space available while there is still space for many many more of Item 2.
It is visualized as below:
![issuepic1](https://user-images.githubusercontent.com/79017992/116239652-272b5f00-a778-11eb-8a16-f3fa0b9c9b81.jpg)

What's the problem here?

Thanks for any help

**Comment by mrehssani** [comment]
same happens by adding even one item 5

**Comment by mrehssani** [comment]
The other case I tested : 
I changed the box direction:  
$packer->addBox(new TestBox('Box 2.5-2', 20,20, 30, 2, 20, 20, 30, 1000));

    $packer->addItem(new TestItem('Item 1', 20, 20, 2, 0,  Item::ROTATION_BEST_FIT), 4); // item, quantity
   $packer->addItem(new TestItem('Item 2', 8, 3, 2, 0,  6), 4);
    $packer->addItem(new TestItem('Item 3', 10, 10, 10, 0, Item::ROTATION_BEST_FIT), 4);
   $packer->addItem(new TestItem('Item 4', 12, 12, 10, 0, Item::ROTATION_BEST_FIT), 2);
    $packer->addItem(new TestItem('Item 5', 6, 4, 2, 0, 6), **_68_**);     68??!!!!

In reality there is space for only 36 of Item5 , but 68 is fitted ??!!

**Comment by mrehssani** [comment]
Something going wrong for json serializer , in LayerPacker , the startx get reset after filling the first step  in X(width) direction:
Check this example :

Box: 
$packer->addBox(new TestBox('Box 2.5-1', 30,20, 20, 2, 30, 20, 20, 1000));
Item:
$packer->addItem(new TestItem('Item 1', 2, 8, 12, 0,  6), 53);

The 51st item starts in position 0,0,0 and so on to 59th

**Comment by dvdoug** [comment]
> 
> 
> Something going wrong for json serializer , in LayerPacker , the startx get reset after filling the first step in X(width) direction:
> Check this example :
> 
> Box:
> $packer->addBox(new TestBox('Box 2.5-1', 30,20, 20, 2, 30, 20, 20, 1000));
> Item:
> $packer->addItem(new TestItem('Item 1', 2, 8, 12, 0, 6), 53);
> 
> The 51st item starts in position 0,0,0 and so on to 59th

I can reproduce this, thanks for reporting!

**Comment by mrehssani** [comment]
Thank you , do the commits work on master version as well?

**Comment by dvdoug** [comment]
Should do!
