### ISSUE TITLE
Overlapping items

### ISSUE THREAD

**Issue by shakethatweight-simon** [dvdoug/BoxPacker#234]
Most cases are ok, but we've noticed some issues with items overlapping when we try to visualise the layouts.

The simplest one I've found so far is this, but there are others. Items 1 and 4, both have origin 0,0,0

It looks like the items do fit in the box, but item 4, should be in a different location?

![Screen Shot 2021-05-10 at 22 09 50](https://user-images.githubusercontent.com/62300999/117725073-8cea0300-b1dc-11eb-89c5-a62665fc47d1.png)

Hopefully there is enough information below for you to recreate the issue. All measurements are 1/10mm so that I could work with integer numbers.

```
{
  "data": [
    {
      "box": {
        "reference": "C5 Letter",
        "innerWidth": 2180,
        "innerLength": 200,
        "innerDepth": 1590
      },
      "items": [
        {
          "x": 0,
          "y": 0,
          "z": 0,
          "width": 1650,
          "length": 140,
          "depth": 1250,
          "item": {
            "description": "Item 1",
            "width": 1250,
            "length": 1650,
            "depth": 140,
            "keepFlat": false
          }
        },
        {
          "x": 0,
          "y": 140,
          "z": 0,
          "width": 850,
          "length": 60,
          "depth": 1400,
          "item": {
            "description": "Item 2",
            "width": 850,
            "length": 1400,
            "depth": 60,
            "keepFlat": false
          }
        },
        {
          "x": 850,
          "y": 140,
          "z": 0,
          "width": 850,
          "length": 60,
          "depth": 1400,
          "item": {
            "description": "Item 3",
            "width": 850,
            "length": 1400,
            "depth": 60,
            "keepFlat": false
          }
        },
        {
          "x": 0,
          "y": 0,
          "z": 0,
          "width": 356,
          "length": 170,
          "depth": 1056,
          "item": {
            "description": "Item 4",
            "width": 356,
            "length": 1056,
            "depth": 170,
            "keepFlat": false
          }
        }
      ]
    }
  ]
}
```

(Order: 7808753)

**Comment by dvdoug** [comment]
Hi @shakethatweight-simon 

Can I check what version you're using? 3.9.0 could have that (unfortunate) issue, but 3.9.1 should have fixed it. In the test packing I just did with 3.9.1, Items 1-3 had the same positioning and orientation, item 4 is placed at x=1700,y=0,z=0 which I think aligns with reality.

**Comment by shakethatweight-simon** [comment]
@dvdoug Thank you, I didn't notice the update. I'm testing now.

**Comment by shakethatweight-simon** [comment]
@dvdoug  Perfect, confirmed with some of the larger orders I'd also spotted last night.
