### ISSUE TITLE
Packing issue with maxWeight

### ISSUE THREAD

**Issue by aurimasrim** [dvdoug/BoxPacker#235]
Hello,
we've found some strange behavior regarding weight and would appreciate it if you could check it.

Version `3.9.1`

Specific example:
```
$packer = new Packer();
$packer->addBox(new TestBox('L', 1000, 1000, 1000, 0, 1000, 1000, 1000, 5));
$packer->addBox(new TestBox('XL', 1500, 1500, 1500, 0, 1500, 1500, 1500, 10));
$packer->addItem(new TestItem('', 1, 1, 1, 3, false));
$packer->addItem(new TestItem('', 1, 1, 1, 3, false));
$packer->addItem(new TestItem('', 1, 1, 1, 3, false));
$packer->addItem(new TestItem('', 1, 1, 1, 3, false));
$packedBoxes = $packer->pack();
foreach ($packedBoxes as $packedBox) {
    echo $packedBox->getBox()->getReference() . PHP_EOL;
}
```
The dimensions of the boxes are very big on purpose so the limiting factor for this packing case would be max weight. 
The actual result is:
```
XL
XL
```
Though I would expect it to be:
```
XL
L
```
The optimal solution would be to pack 3 items into the `XL` box and 1 item into the `L` box. Though the algorithm chooses to pack 2 XL boxes with 2 items in each.

I've debugged it a bit and I found out that it packs correctly at first but then the `L` box is replaced by `XL` box after a call to `findBestBoxFromIteration` https://github.com/dvdoug/BoxPacker/blob/3.9.1/src/Packer.php#L193

Do you know what could be the cause of it?
Thanks in advance!

**Comment by shakethatweight-simon** [comment]
@aurimasrim  Your issue relates to this: https://www.boxpacker.io/en/stable/weight-distribution.html - you can disable this if you want.

**Comment by aurimasrim** [comment]
But shouldn't weight distribution be applied only to already chosen boxes? I mean that if the optimal solution is 1  `XL` and 1 `L` then weight should be distributed between them?

**Comment by aurimasrim** [comment]
Hi @dvdoug
good point. Thanks for the detailed explanation!
