### ISSUE TITLE
help need: how I get most matched box by 3d package finding?

### ISSUE THREAD

**Issue by vidux** [dvdoug/BoxPacker#242]
i calculate weight separately  by summing up products weight, and need only consider about dimensions 

 per-defined boxes only have width , height and length
eg:
     ( width , length , height )
box1 (20,30,20);
box2 (30,50,25);
box3 (40,60,35);

product also have width , height and length

( width , length , height , ,rotatable, qty)
product1 (5,5,10, true, 1);
product1 (8,8,10, true, 1);
product1 (10,12,15, true, 1);

i just need to get matched  index of the box. is it possible with this package without providing other details,(like depth,inner dimensions) ? 
thank you very much.

**Comment by dvdoug** [comment]
What you call height, the library probably calls depth - you can check the diagram at https://www.boxpacker.io/en/stable/getting-started.html to compare what you call the 3 dimensions with what the library uses.

For inner dimensions, my first recommendation would be to obtain them but as an alternative you could assume that `inner = outer` or `inner = outer - 1mm`?

**Comment by vidux** [comment]
yes i misunderstood height with depth. I created custom box class and changed its contractor to get required parameters . i think problem fixed. thank you again.
