### ISSUE TITLE
InfalliblePacker

### ISSUE THREAD

**Issue by shakethatweight-simon** [dvdoug/BoxPacker#244]
I was trying to use the InfalliblePacker to find out what items wouldn't fit if I force a particular box size, but instead it used 2 boxes of the same size. But it has shown that these few items don't fit in the first box, but it does look like at last some of them could fit.

![image](https://user-images.githubusercontent.com/62300999/122967413-575f3a80-d382-11eb-895e-8ed84de99b40.png)
![image](https://user-images.githubusercontent.com/62300999/122967460-62b26600-d382-11eb-8bbc-5058fc19e3e5.png)

is there a way to export the box and item data from the Packer or InfalliblePacker class so I can send you the information?

(My reference: dev:orders/95360 ~ live:orders/100856)

**Comment by dvdoug** [comment]
Hi @shakethatweight-simon 

As long as you're not using any custom constraints, `json_encode($packedBoxes)` would be the bare minimum for me to reproduce with, that contains all the relevant dimensions.

If you could turn it into a runnable testcase though (something like https://github.com/dvdoug/BoxPacker/blob/3.x/tests/PackerTest.php#L169) that would be awesome 😄 


(note for self, I suspect this is https://github.com/dvdoug/BoxPacker/blob/master/src/OrientatedItemFactory.php#L185 being less helpful than it should be)

**Comment by shakethatweight-simon** [comment]
Extracted from the code, slightly different format to your usual tests but should be ok for you? 

The usual routine produces box "12", which has lots of spare space.

```
$packer = new Packer();
$packer->setMaxBoxesToBalanceWeight(0);
$packer->addBox(new TestBox("11", 4400, 1400, 3400, 0, 4600, 1600, 3600, 30000));
$packer->addBox(new TestBox("12", 4570, 3050, 3050, 0, 4770, 3250, 3250, 30000));
$packer->addItem(new TestItem("Shakes", 900, 95, 1500, 34, false), 6);
$packer->addItem(new TestItem("Bars", 356, 170, 1056, 56, false), 6);
$packer->addItem(new TestItem("Noodles", 1250, 140, 1650, 45, false), 6);
$packer->addItem(new TestItem("Ready Meals", 1250, 285, 1600, 270, false), 6);
$packer->addItem(new TestItem("Ready Meals", 1250, 285, 1600, 270, false), 6);
$packer->addItem(new TestItem("Ready Meals", 1250, 285, 1600, 270, false), 3);
$packer->addItem(new TestItem("Ready Meals", 1250, 285, 1600, 270, false), 4);
$packer->addItem(new TestItem("Soups", 1000, 60, 1400, 35, false), 2);
$packer->addItem(new TestItem("Cereals", 850, 60, 1400, 40, false), 3);
$packer->addItem(new TestItem("Snacks", 1600, 300, 2000, 30, false), 1);
$packer->pack();
```

If I use InfalliblePacker and force box "11", then we get the 2 layouts shown in the screenshots originally posted.
(I had originally thought I could use this to force a single box size and find out what doesn't fit in the first box, but realise now that's not how this works.)

```
$packer = new InfalliblePacker();
$packer->setMaxBoxesToBalanceWeight(0);
$packer->addBox(new LimitedSupplyTestBox("11", 4400, 1400, 3400, 0, 4600, 1600, 3600, 30000, 1));
$packer->addItem(new TestItem("Shakes", 900, 95, 1500, 34, false), 6);
$packer->addItem(new TestItem("Bars", 356, 170, 1056, 56, false), 6);
$packer->addItem(new TestItem("Noodles", 1250, 140, 1650, 45, false), 6);
$packer->addItem(new TestItem("Ready Meals", 1250, 285, 1600, 270, false), 6);
$packer->addItem(new TestItem("Ready Meals", 1250, 285, 1600, 270, false), 6);                                                                                                                                      $packer->addItem(new TestItem("Ready Meals", 1250, 285, 1600, 270, false), 3);                                                                                                                                      $packer->addItem(new TestItem("Ready Meals", 1250, 285, 1600, 270, false), 4);                                                                                                                                      $packer->addItem(new TestItem("Soups", 1000, 60, 1400, 35, false), 2);                                                                                                                                              $packer->addItem(new TestItem("Cereals", 850, 60, 1400, 40, false), 3);                                                                                                                                             $packer->addItem(new TestItem("Snacks", 1600, 300, 2000, 30, false), 1);                                                                                                                                            $packer->pack();
```

Looking at the "note to self" you mentioned, I've set `return true` at the start of the `isStable` method, and the box is packed in the smaller size with all items fitting, so that initially sounds good, but... 

Another order has been changed to a larger box when isStable is forced to true, which is not what we'd want.

```
$packer = new Packer();
$packer->setMaxBoxesToBalanceWeight(0);
$packer->addBox(new TestBox("8", 3050, 1520, 3050, 0, 3250, 1720, 3250, 30000, 1));
$packer->addBox(new TestBox("10", 3050, 2290, 1520, 0, 3250, 2490, 1720, 30000, 1));
$packer->addItem(new TestItem("Shakes", 900, 95, 1500, 34, false), 35);
$packer->addItem(new TestItem("Shakes", 900, 95, 1500, 34, false), 35);
$packer->pack();
```
Best fit
![H-SmallerBox](https://user-images.githubusercontent.com/62300999/123254226-4fb8a680-d4e6-11eb-8136-541819a22ea7.png)
Oversized
![I - Oversized](https://user-images.githubusercontent.com/62300999/123254237-51826a00-d4e6-11eb-9aee-82736fd4b5ec.png)

(In these examples I've only shown the boxes that were used, I've ignored the full list of available options.)

**Comment by shakethatweight-simon** [comment]
Don't know if you want this as a new issue, when I forced `isStable = true` I found a few examples like this where the items overlapped.
```
$packer = new Packer();
$packer->setMaxBoxesToBalanceWeight(0);
$packer->addBox(new TestBox("6", 2290, 1520, 1520, 0, 2490, 1720, 1720, 30000, 1));
$packer->addItem(new TestItem("Shakes", 850, 95, 1450, 34, false), 21);
$packer->addItem(new TestItem("Noodles", 1250, 140, 1650, 45, false), 1);
$packer->addItem(new TestItem("Noodles", 1250, 140, 1650, 45, false), 1);
$packer->addItem(new TestItem("Pasta and Rice", 1100, 60, 1400, 45, false), 1);
$packer->addItem(new TestItem("Pasta and Rice", 1250, 140, 1650, 45, false), 1);
$packer->addItem(new TestItem("Soups", 850, 60, 1400, 34, false), 1);
$packer->addItem(new TestItem("Soups", 1000, 60, 1400, 35, false), 2);
$packer->pack();
```

![image](https://user-images.githubusercontent.com/62300999/123256751-39601a00-d4e9-11eb-92ea-065f53a03f2e.png)


If I increase the size of the product very slightly, then it still fits in the same box, but packs it without the overlap.
(All our measurements are in mm)

![image](https://user-images.githubusercontent.com/62300999/123257464-1bdf8000-d4ea-11eb-8e62-c72e5abbc64c.png)

```
$packer = new Packer();
$packer->setMaxBoxesToBalanceWeight(0);
$packer->addBox(new TestBox("6", 2290, 1520, 1520, 0, 2490, 1720, 1720, 30000, 1));
$packer->addItem(new TestItem("Shakes", 900, 95, 1500, 34, false), 21);
$packer->addItem(new TestItem("Noodles", 1250, 140, 1650, 45, false), 1);
$packer->addItem(new TestItem("Noodles", 1250, 140, 1650, 45, false), 1);
$packer->addItem(new TestItem("Pasta and Rice", 1100, 60, 1400, 45, false), 1);
$packer->addItem(new TestItem("Pasta and Rice", 1250, 140, 1650, 45, false), 1);
$packer->addItem(new TestItem("Soups", 850, 60, 1400, 34, false), 1);
$packer->addItem(new TestItem("Soups", 1000, 60, 1400, 35, false), 2);
$packer->pack();
```
