### ISSUE TITLE
Items overlaps in a box

### ISSUE THREAD

**Issue by bendadaniel** [dvdoug/BoxPacker#248]
Hello,
I am using presorted sets for getting the best fitting result. I presort items by some sort functions and then calculate one by one to get the best result. Everything works fine but today I am facing problem that one of my presorted collection returns 1 box and items are overlaped and not return exception or someting else. It should return 2 boxes. 

**PHP code to reproduce:**

`$packer_items = [];`
`$packer = new Packer();`
`$packer->addBox(new LimitedSupplyTestBox('FULL_SLAB', 3150, 1520, 1, 1, 3150, 1520, 1, 10000000, 1000));`
` `
`$packer_items[] = new TestItem('Item 1', 1900, 50, 1, 1, 6);`
`$packer_items[] = new TestItem('Item 2', 700, 50, 1, 1, 6);`
`$packer_items[] = new TestItem('Item 3', 600, 50, 1, 1, 6);`
`$packer_items[] = new TestItem('Item 4', 1300, 50, 1, 1, 6);`
`$packer_items[] = new TestItem('Item 5', 1200, 200, 1, 1, 6);`
`$packer_items[] = new TestItem('Item 6', 2500, 50, 1, 1, 6);`
`$packer_items[] = new TestItem('Item 7', 900, 600, 1, 1, 6);`
`$packer_items[] = new TestItem('Item 8', 1900, 600, 1, 1, 6);`
`$packer_items[] = new TestItem('Item 9', 1300, 600, 1, 1, 6);`
`$packer_items[] = new TestItem('Item 10', 1900, 600, 1, 1, 6);`
`$packer_items[] = new TestItem('Item 11', 1500, 600, 1, 1, 6);`
` `
` `
`$packer->setItems(ItemList::fromArray($packer_items, true)); // true means presorted`
`$packedBoxes = $packer->pack(); `
`//it returns 1 box but it should be 2`

**Overlap vizualization:**
![overlap](https://user-images.githubusercontent.com/15817021/125065236-e1611000-e0b1-11eb-8381-aebcd9191f62.png)

**Do you have some idea how to fix it or make some workaround?**

Thank you very much for this amazing package
Daniel

**Comment by dvdoug** [comment]
Hi @bendadaniel 

I've just tried and cannot reproduce - can I check what version you're using?

![image](https://user-images.githubusercontent.com/1571110/125173776-de9d1280-e1b8-11eb-9fb3-20612f7d79f6.png)

**Comment by bendadaniel** [comment]
Hi @dvdoug 

I was using v3.9.0 it seems there was this bug, when I update to latest version it works fine. SOLVED. 

Once more thank you for this amazing package.

Daniel
