### ISSUE TITLE
3.9.2 contains breaking changes

### ISSUE THREAD

**Issue by BackEndTea** [dvdoug/BoxPacker#249]
We were catching the `ItemTooLargeException` in a few places, but in 3.9.2 the parent `NoBoxesAvailableException` was thrown instead. 

This was a breaking change which should not have happened in a patch version. But its easy to miss. Prehaps a tool like https://github.com/Roave/BackwardCompatibilityCheck could be used to discover potential BC breaks?

**Comment by dvdoug** [comment]
Whoops, sorry about that! I'll look into the tool you mention.
