### ISSUE TITLE
Possible min/max bug

### ISSUE THREAD

**Issue by andrewmostello** [dvdoug/BoxPacker#250]
I've been reviewing the code/algorithm, and I was wondering if the use of `max` in this line should actually be `min`. I could just be confused, but it seems like you want either `PHP_INT_MAX` in the event this is not a `LimitedSupplyBox` (as seen in `Packer` `setBoxes` etc.), or the quantity available plus one. That would be using `min`, not `max`.

https://github.com/dvdoug/BoxPacker/blob/78caa7f9d9a617a564f3b8e6a78ebba830f2cf05/src/WeightRedistributor.php#L173

**Comment by dvdoug** [comment]
Hi

Yes, you're right that code does look suspicious. Thanks for pointing it out 👍

**Comment by dvdoug** [comment]
This won't have had any actual impact on the packing result, but good to clear up anyway 👍
