### ISSUE TITLE
Can't seem to initiate BoxPacker\Item and BoxPacker\Box classes

### ISSUE THREAD

**Issue by booyaamps** [dvdoug/BoxPacker#253]
Hello! First of all, excellent job on this. We use it to provide real time shipping rates for in cart options.

Everything is working very well, but in the test classes, TestItem::ROTATION_BEST_FIT is not useable (PHP Fatal error:  Uncaught Error: Undefined class constant 'ROTATION_BEST_FIT') , so I'd like to move to the regular classes.

One small issue i'm having is this:
The Test\TestItem and Test\TestBox classes work well. However, any time i try to use just the Item and Box classes, i get this issue:
PHP Fatal error:  Uncaught Error: Class 'DVDoug\\BoxPacker\\Box' not found 
PHP Fatal error:  Uncaught Error: Class 'DVDoug\\BoxPacker\\Item' not found 

Code:

use DVDoug\BoxPacker\Packer;
use DVDoug\BoxPacker\ItemList;
use DVDoug\BoxPacker\Item;
use DVDoug\BoxPacker\Box;
use DVDoug\BoxPacker\Test\TestItem;
use DVDoug\BoxPacker\Test\TestBox;

use GuzzleHttp\{
    Client,
    RequestOptions
};

function palletPacker($accessToken, $client, $data, $db, $jsonData) {
    $sendData = array();
    $packData = array();
    parse_str(urldecode($jsonData), $packData);

    $pallet = json_decode($packData['pallet'], 1);

    $packer = new Packer();
    $packer->addBox(new Box($pallet['name'], $pallet['outer_width'] * 25.4, $pallet['outer_length'] * 25.4, $pallet['outer_depth'] * 25.4, $pallet['empty_weight'] * 454, $pallet['inner_width'] * 25.4, $pallet['inner_length'] * 25.4, $pallet['inner_depth'] * 25.4, $pallet['max_weight'] * 454));
    $items = $packData['item'];
    $sendData['items'] = $items;
    foreach ($items as $item) {
        $csv = array_map('str_getcsv', file("wholesale.csv"));
        array_walk($csv, function(&$a) use ($csv) {
            $a = array_combine($csv[0], $a);
        });
        array_shift($csv); # remove column header        
        foreach ($csv as $records) {
            if ($records['name'] == $item['sku']) {
                $itemWeight = (float) $records['weight'] * 454;
                $itemCount=$item['qty'];
                while($itemCount != 0){
                $packer->addItem(new Item($records['name'], (float) $records['width'] * 25.4, (float) $records['length'] * 25.4, (float) $records['height'] * 25.4, $itemWeight, true));
                $itemCount=$itemCount-1;
                }
            }
        }
    }
    //pack the box
    try {   
        $packedBoxes = $packer->pack();
        //$packedBoxes = $packer->doVolumePacking();
    } catch (\Exception $exception) {
        print_r($exception);
        exit;
    }

**Comment by dvdoug** [comment]
Hi @booyaamps 

> PHP Fatal error: Uncaught Error: Undefined class constant 'ROTATION_BEST_FIT'

It sounds like this might a confusion about the version you're looking at - in the current releases, the `Item` interface has a method called `getKeepFlat()` which returns a boolean (see https://github.com/dvdoug/BoxPacker/blob/3.x/src/Item.php).

On `master` (intended for the next major version but unreleased), `ItemList` has `getAllowedRotations()` (see https://github.com/dvdoug/BoxPacker/blob/master/src/Item.php) which returns one of the `Item::ROTATION_*` constants. These constants do not exist in current releases.

I suspect you probably have a released version installed on disk but have come across documentation for the next version instead?

**Comment by booyaamps** [comment]
Ah, dangit. I am definitely on the master docs. My sincere apologies.

I am extremely excited for that feature. We want to use this to pack
pallets. Im already quite a ways into it, and using three.js to render the
pallet as packed.

As far as the item and box classes be unavailable, am i missing something
syntax wise?

**Comment by dvdoug** [comment]
> As far as the item and box classes be unavailable, am i missing something syntax wise?

They're interfaces, not classes - you need to have one of your own classes implement them

**Comment by dvdoug** [comment]
See https://boxpacker.io/en/stable/getting-started.html

**Comment by booyaamps** [comment]
Got it! Thanks!
