### ISSUE TITLE
particular constraints

### ISSUE THREAD

**Issue by Elyos59** [dvdoug/BoxPacker#260]
Hi!

To begin with, I wanted to congratulate you for this very good work.

I have some packing restriction and I don't know how to implement it.

I have 4 kind of item :
1/ Not stackable & keep flat
2/ Not stackable & 3D rotation (useless for the moment)
3/ Stackable & keep flat (useless for the moment)
4/ Stackable & 3D rotation

For the moment, I focus on the 1st and the 4th kind of item.

The 1st can't have another item on it.
The 4th can have one or more items on it only if : 
- same dimensions or less (an item 2x2 can have 2 items 1x1 or 1 item 1x2 or 1 item 2x1 or 1 item 2x2 on it)
AND
- same weight or less (an item of 20kgs can have on it 3 items of 20 kgs or less each)

I think I have to use ConstrainedPlacementItem Class but I don't know how to cause of item below (dimensions/orientations/weight...)

Thanks for any help ;)

**Comment by dvdoug** [comment]
Hello @Elyos59 

https://boxpacker.io/en/stable/advanced-usage.html#example-don-t-allow-batteries-to-be-stacked would probably a good starting point - that example loops through the already packed items to find relevant items that would cause stacking issues. You'd need to modify that to add on your particular additional constraints
