### ISSUE TITLE
An issue and a question

### ISSUE THREAD

**Issue by Shapit0** [dvdoug/BoxPacker#27]
First of all, let me say "thank you" for so great job you've done.

I have a task to fit different 2d figures (squares and rectangles in to bigger rectangle).

So, i have an issue and a question:
Issue:
I know, that items №581, 578, 571, 389 must fit into box1:
 $packer->addBox(new TestBox('BOX1', 2500, 1250, 2, 10, 2500, 1250, 2, 1000));
  $packer->addItem(new TestItem('581', 425, 2369, 2, 0));
  $packer->addItem(new TestItem('571', 305, 2353, 2, 0));
  $packer->addItem(new TestItem('389', 248, 305, 2, 0));
  $packer->addItem(new TestItem('578', 410, 1940, 2, 0));

But it doesn't in my code (389 goes to an extra Box).

Question:
Is it possible to use triangles? :)

Thank you.

**Comment by dvdoug** [comment]
No triangles, sorry
