### ISSUE TITLE
Volume packing set allowed air in box

### ISSUE THREAD

**Issue by YoussefAlmardini** [dvdoug/BoxPacker#270]
Hi, I am using packer to pack normal products in 3 different sizes boxes and it works good!
I would like to ask for features or advice, In some cases i need to use volume packing instead of normal packing, i need to volume packing to save more cartoon but the result is a real puzzle for employees in logistic, so i need to pack 80% (or dynamic value)  form each box instead of full to neck. 

My code: 
`        $packer = new BoxPacker\Packer();

        foreach ($availableBoxes as $availableBox)
            $packer->addBox(new Box($availableBox::class, $availableBox::LENGTH, $availableBox::WIDTH, $availableBox::HEIGHT, 22500));

        try {
            $prettyBoxes = 0;
            foreach ($order->getItems() as $item) {
                if ($item->getWarehouseItem()->isPrettyBox()) {
                    $prettyBoxes ++;
                    $packer->addBox(self::createPrettyBoxCarrier($item->getWarehouseItem()->getLeadingDimensions()));
                }

                $packer->addItem(Item::fromWarehouseItem($item->getWarehouseItem()), $item->getQuantity());
            }
            
            $result = $packer->doVolumePacking();

            return ($result->count() > 9) ? null : $result;
        } catch (BoxPacker\ItemTooLargeException | BoxPacker\NoBoxesAvailableException | UnknownDimensionsException) {
            return null;
        }`

If you have an advice or tip i will be thankful :)

**Comment by shakethatweight-simon** [comment]
There is a visualisation tool available now, we use a slightly different 3d render, but for complex orders our packers can click a button to reveal a 3d render of the packed box to show how to determined which box to use, would this be an option instead of sacrificing efficiency in box size and postage costs over the complexity of packing the box?

**Comment by YoussefAlmardini** [comment]
Thanks for reply, i am already using 3d view and it is fine, but i want really 80% full boxes, i mean something between  Pack function and doVolumePackPacking, i want to save boxes but also to fill the each box to specific percentage. I also tried canBePacked function but there u can not reach box volume to determine the capacity, i also tried setMaxBoxesToBalanceWeight to set weight to distribute weight in 3 boxes, but is does not work with doVolumePack. So am kind of asking for feature i think right? or is there another way?

**Comment by YoussefAlmardini** [comment]
> There is a visualisation tool available now, we use a slightly different 3d render, but for complex orders our packers can click a button to reveal a 3d render of the packed box to show how to determined which box to use, would this be an option instead of sacrificing efficiency in box size and postage costs over the complexity of packing the box?

Thanks for reply, i am already using 3d view and it is fine, but i want really 80% full boxes, i mean something between Pack function and doVolumePackPacking, i want to save boxes but also to fill the each box to specific percentage. I also tried canBePacked function but there u can not reach box volume to determine the capacity, i also tried setMaxBoxesToBalanceWeight to set weight to distribute weight in 3 boxes, but is does not work with doVolumePack. So am kind of asking for feature i think right? or is there another way?

**Comment by dvdoug** [comment]
Hi @YoussefAlmardini 

I think https://github.com/dvdoug/BoxPacker/discussions/216 should help you out

**Comment by YoussefAlmardini** [comment]
> Hi @YoussefAlmardini
> 
> I think #216 should help you out

Nice that is what a, looking for! thanks
