### ISSUE TITLE
Inefficient packing

### ISSUE THREAD

**Issue by dvdoug** [dvdoug/BoxPacker#272]
Not sure if I should open a separate task or not but here is a similar example that is actually much simpler:

- 5 units of an item which is 2.6 L x 2.6 W x 4.6 H inches
- One box option that is 7.25 L x 7.25 W x 6.5 H inches (a USPS flat rate box)

This should be able to fit up to 6 units by laying 4 on their side and stacking those 4 two high and then the remaining two upright. However, BoxPacker splits it into two boxes (first one with 3 units shown) but you can see how six would be able to fit:

![image](https://user-images.githubusercontent.com/38738/149593639-dd536499-9d32-4169-bf85-15e79ea6d4bf.png)

_Originally posted by @colinmollenhour in https://github.com/dvdoug/BoxPacker/issues/264#issuecomment-1013518063_

**Comment by colinmollenhour** [comment]
Hi @dvdoug what are the chances realistically of you being able to make optimizations to the algorithm to address problems such as this in 2022?

**Comment by dvdoug** [comment]
Hi @colinmollenhour 

🤞 I should have time around October to come back and have a proper attempt at issues like this - unfortunately while it's easy(ish) to figure out which packing decision is being non-optimal in any given situation, it's usually the case (it is here) that tweaking things to make one packing scenario better tends to regress others - and sadly I haven't had the time recently for complicated issues, only simple ones.

Please rest assured though, this is not an abandoned lib

**Comment by colinmollenhour** [comment]
@dvdoug Thanks for the update. Let me know when you start if you need any assistance from my team with testing or otherwise.

**Comment by dvdoug** [comment]
When released, it will be automatic - it will still only consider the allowed rotations (e.g. keep flat will be respected) but instead of simply running the heuristic to guess at the best orientation and then firmly sticking to it, if there are items that don't fit into the box, it will go back and retry starting with by placing that first item in each of the other orientations to see if a better result can be obtained

**Comment by dvdoug** [comment]
By restricting the try-everything version to just the first item, performance on the whole doesn't suffer - although there will be additional extra packings done inside the new loop (potentially 3x slower), this is more than offset by the extra packing efficiency meaning that the weight redistributor doesn't kick in as much (or at all when going from 2 to 1)

**Comment by colinmollenhour** [comment]
Thanks for the additional information, and your continued support of the project.

Would you be interested in working part-time or full-time on our WMS development team? We recently received additional investment and are looking to add a lot of new features. It is mostly PHP and MySQL with a few other components.

Thanks again,
Colin
________________________________

**Comment by dvdoug** [comment]
Many thanks for that offer @colinmollenhour but happily employed currently so I'll need to decline
