### ISSUE TITLE
BoxPacker is not supportive for float values!

### ISSUE THREAD

**Issue by mumairdeveloper** [dvdoug/BoxPacker#273]
Hello,

I wanna pass the float values of length, width, height, and weight to boxes and products as well, please help

Thanks

**Comment by dvdoug** [comment]
Hi @mumairdeveloper 

The library uses integers on purpose to avoid floating point rounding errors (see https://github.com/dvdoug/BoxPacker/issues/215 for an example). If you're using centimetres or inches, just convert to millimetres
