### ISSUE TITLE
Version 3.9 - Rotation option does not work

### ISSUE THREAD

**Issue by canetti2** [dvdoug/BoxPacker#276]
Hello,

we would like to use the great library to find the best package for our shipping items.
Exemplary we have two boxes:

Box 1: 500 x 100 x 100
Box 2: 600 x 100 x 100

We work with the TestItem.php and have a modified getKeepFlat() function:

```
public function getKeepFlat(): bool
{
  // return $this->keepFlat;
     return false;
}
```

This is our Item-code:
```
$prod = new TestItem('Testprod', 501, 1, 1, 1, true); 
$packer->addItem($prod);
```

As result we get NOT the Box 1 (500x100x100) but the Box 2 (600x100x100).

Can anybody help me - what is wrong?

**Comment by canetti2** [comment]
I think I misunderstood the rotation function. Please take a look at the picture:
![box-item](https://user-images.githubusercontent.com/24872015/159160345-25496264-23a4-4e17-a9b2-d58d62bfee1a.gif)

Is this kind of packing with the library possible? Or is the library not able to place the item diagonally in the box?

**Comment by dvdoug** [comment]
Hi @canetti2 

Diagonals are not supported 😨 , only rotations of 90 degrees
