### ISSUE TITLE
How to get dimensions of multiple items?

### ISSUE THREAD

**Issue by staixe** [dvdoug/BoxPacker#297]
Hi, I want to get dimensions of multiple items.

In tests/PackerTest.php I see the method, testPackWithoutBox. I am trying to write the following code

`$item1 = new TestItem('Item1', 5, 5, 5, 10, false);
$item2 = new TestItem('Item2', 15, 15, 5, 10, false);
$item3 = new TestItem('Item3', 5, 15, 15, 10, false);

$packer = new Packer();
$packer->addItem($item1);
$packer->addItem($item2);
$packer->addItem($item3);
$packer->pack();`

and i get an error
Fatal error: Uncaught DVDoug\BoxPacker\NoBoxesAvailableException: No boxes could be found for item 'Item2'

Tell me, can I get the dimensions of an item without a box or do I always have to specify a box?

**Comment by dvdoug** [comment]
Hi @staixe 

That test checks that the relevant exception is thrown, which is in line with the behaviour you describe above.

I'm not sure what you mean though by "get the dimensions of an item without a box" - you already have the dimensions of the items?

**Comment by staixe** [comment]
Hi @dvdoug 
Yes, I Have item sizes, but I don't have box sizes. I would like to get the dimensions of the box in which I can pack all my goods.

How can i do this? or do I always need to set the dimensions of the box?

**Comment by dvdoug** [comment]
That's not something this library does, it only works with existing pre-defined box sizes. There is an open feature request you may wish to subscribe to at https://github.com/dvdoug/BoxPacker/issues/162
