### ISSUE TITLE
Sorting of boxes breaks if any difference is > 2^31-1

### ISSUE THREAD

**Issue by IBBoard** [dvdoug/BoxPacker#30]
If you have the following boxes:

                $packer->addBox(new TestBox('Large Letter', 353, 250, 25, 10, 351, 248, 23, 500));
                $packer->addBox(new TestBox('Small Parcel', 450, 350, 160, 50, 448, 348, 158, 2000));
                $packer->addBox(new TestBox('Medium Parcel', 610, 460, 460, 100, 608, 458, 458, 20000));
                $packer->addBox(new TestBox('Large Parcel', 1300, 1290, 1290, 250, 1298, 1288, 1288, 30000));

Then the BoxList will sort the items correctly and try fitting items in the large letter first, then the small parcel, then the medium, then the large parcel.

If you increase the Large Parcel slightly so that Volume(Large Letter) - Volume(Large Parcel) > 2^31-1 (which isn't PHP_INT_MAX on my system, but is the max signed integer) like this:

                $packer->addBox(new TestBox('Large Letter', 353, 250, 25, 10, 351, 248, 23, 500));
                $packer->addBox(new TestBox('Small Parcel', 450, 350, 160, 50, 448, 348, 158, 2000));
                $packer->addBox(new TestBox('Medium Parcel', 610, 460, 460, 100, 608, 458, 458, 20000));
                $packer->addBox(new TestBox('Large Parcel', 1400, 1290, 1290, 250, 1398, 1288, 1288, 30000));

Then the compare function in BoxList returns something in the region of 2.3bn and puts Large Parcel as the "smallest" item because of integer overflow (until you get to a difference of ~4.3bn, at which point the overflow wraps around to positive again and all is good… until ~6.4bn!)

**Comment by dvdoug** [comment]
Thanks for the reporting this - I'll be tag and release a new version later today with the fix.

**Comment by IBBoard** [comment]
Does that patch fix it for all situations, or have we just hit on the good ones? According to [the PHP docs](https://secure.php.net/manual/en/splheap.compare.php):

    Note:

    Having multiple elements with the same value in a Heap is not recommended. They will end up in an arbitrary relative position.

I'm used to compare being a -1/0/+1 situation in other languages, but I ended up with my convoluted solution because I was worried that it'd screw up in some situations.

That said, a few examples I've just found online use strcmp(), which only promises <0, 0 or >0, but in practice appears to give -1, 0 and 1.

**Comment by dvdoug** [comment]
In this case, that's OK because the comparison we were using before would return 0 in the same situations too - the effect of the change is just to clamp any positive/negative number to +/- 1.

The expected use case here is two identical items - it really doesn't matter which order they get packed in.

**Comment by JohntheFish** [comment]
Is there any reason why integer maths is used and hence needs special cases to avoid 2**31 limits?
Is there any reason (other than history) why floating point maths could not be used?

**Comment by dvdoug** [comment]
@JohntheFish 

Just for the naive reason that each of the 3 measurements for x/y/z would normally be integers (they're documented as mm) and therefore the end result will be an integer too. On a 64-bit system PHP_INT_MAX is 9223372036854775807, which in should be more than large enough to cover all sensible use cases.

Is a variation of this affecting you?

**Comment by IBBoard** [comment]
Don't forget that I reported this bug because I was on a 64-bit system and encountering this at the signed 32-bit limit. I'm fairly sure I checked PHP_INT_MAX at the time and confirmed it wasn't the 32-bit max, but **something** in the calculations caps out at 32-bit.

The fix removes any integer issues and follows a pattern I've seen in other languages, which is fine _as long as_ the sorting algorithm just needs comparatively different values and doesn't make any assumptions about the sizes of the difference affecting sort.

**Comment by JohntheFish** [comment]
Its not affecting me directly. I am involved in reviewing an addon for concrete5 that uses BoxPacker and it (the addon) has been running into overflow exceptions when packing the boxes.  Its it up to the addon developer to diagnose in detail (it could be a different issue) and I don't know if the addon developer has incorporated the above pull. In the mean time I got intellectually curious and my first thought was 'Why not floating point?' as it would effectively remove any environment limitations.

**Comment by JohntheFish** [comment]
PS. PHP_INT_MAX is 9223372036854775807 on the system I am using for testing.

**Comment by dvdoug** [comment]
Is there a public link to the addon? Happy to take a look if there's a reproducible testcase

**Comment by JohntheFish** [comment]
Its really a problem for the addon developer to get involved with, so I wouldn't spend time until they ask, especially as I don't know if the addon developer has incorporated the above pull.

The base store addon that incorporates is at BoxPicker is at  https://www.concrete5.org/marketplace/addons/store-ecommerce-from-vivid

The current review is for some shipping cost and payment modules (also from Vivid, but not publicly available) that sit on top of it, but checkout is glitching on the overflow.
