### ISSUE TITLE
$packer->pack() extremelly slow

### ISSUE THREAD

**Issue by 3m0** [dvdoug/BoxPacker#36]
I've created a packer with 3 types of boxes and added 1000 items to it. When I packed them, it took more than 10 minutes to finish it. Is it like this or is this a recursion problem?

**Comment by dvdoug** [comment]
10 minutes seem excessive even for a packing problem of that size - do you have xdebug turned on by any chance?

**Comment by 3m0** [comment]
Yes, in fact I do.

**Comment by dvdoug** [comment]
See the comment at the bottom of the readme - xdebug slows everything down by an obscene amount. If you turn it off temporarily and then benchmark, I would expect it to finish well under the 1min mark.
