### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by basilfawlty** [dvdoug/BoxPacker#38]
Hi @dvdoug 
I am trying to implement for an ecommerce application
I have installed with composer inside a directory outside of public_html.

I have included all of your files into my webpage php script which is in the public_html folder, using the following code:

require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/autoload.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/Box.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/BoxList.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/Item.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/ItemList.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/PackedBox.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/PackedBoxList.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/Packer.php';

When I try to run using the example code in your Readme, the script fails as soon as it gets to "$packer = new Packer();" with error message:

Fatal error: Class 'Packer' not found

If I add "namespace DVDoug\BoxPacker;" to the first line of the webpage php script I get a 500 server error but can't see what this error is.

Where am I going wrong here?

**Comment by basilfawlty** [comment]
Ok, I've cracked this. Putting "namespace DVDoug\BoxPacker;" at the top of the webscript causes all objects (eg mysql objects) to be evaluated in this namespace hence the 500 server errors.

I have got everything to work by adding one more include:
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/tests/bootstrap.php';

And then calling the objects prefixed with DVDoug\BoxPacker\ .... e.g.:

$packer = new DVDoug\BoxPacker\Packer();

**Comment by basilfawlty** [comment]
Having now got it working, this library is excellent - thanks v much @dvdoug

**Comment by haris989** [comment]
Please help me to get it to work too please

**Comment by BenRoe** [comment]
Thank you @basilfawlty. I installed it via composer `php composer.phar install` in the project directory ([more information](https://packagist.org)).

index.php
```php
<?php

namespace DVDoug\BoxPacker;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/vendor/dvdoug/boxpacker/tests/bootstrap.php';
require_once __DIR__ . '/vendor/dvdoug/boxpacker/Box.php';
require_once __DIR__ . '/vendor/dvdoug/boxpacker/BoxList.php';
require_once __DIR__ . '/vendor/dvdoug/boxpacker/Item.php';
require_once __DIR__ . '/vendor/dvdoug/boxpacker/ItemList.php';
require_once __DIR__ . '/vendor/dvdoug/boxpacker/PackedBox.php';
require_once __DIR__ . '/vendor/dvdoug/boxpacker/PackedBoxList.php';
require_once __DIR__ . '/vendor/dvdoug/boxpacker/Packer.php';

/*
 * To figure out which boxes you need, and which items go into which box
 */
$packer = new Packer();
$packer->addBox(new TestBox('Le petite box', 300, 300, 10, 10, 296, 296, 8, 1000));
$packer->addBox(new TestBox('Le grande box', 3000, 3000, 100, 100, 2960, 2960, 80, 10000));
$packer->addItem(new TestItem('Item 1', 250, 250, 2, 200, true));
$packer->addItem(new TestItem('Item 2', 250, 250, 2, 200, true));
$packer->addItem(new TestItem('Item 3', 250, 250, 2, 200, true));
$packedBoxes = $packer->pack();

echo("These items fitted into " . count($packedBoxes) . " box(es)");
foreach ($packedBoxes as $packedBox) {
  $boxType = $packedBox->getBox(); // your own box object, in this case TestBox
  echo("This box is a {$boxType->getReference()}, it is {$boxType->getOuterWidth()}mm wide, {$boxType->getOuterLength()}mm long and {$boxType->getOuterDepth()}mm high" . PHP_EOL);
  echo("The combined weight of this box and the items inside it is {$packedBox->getWeight()}g" . PHP_EOL);

  echo("The items in this box are:" . PHP_EOL);
  $itemsInTheBox = $packedBox->getItems();
  foreach ($itemsInTheBox as $item) { // your own item object, in this case TestItem
    echo($item->getDescription() . PHP_EOL);
  }

  echo(PHP_EOL);
}
```

**Comment by ViktorKirjanov** [comment]
`$packer = new Packer();
        $packer->addBox(new TestBox('Box1', 2, 2, 2, 0, 2, 2, 2, 1000));
        $packer->addBox(new TestBox('Box2', 4, 4, 4, 0, 4, 4, 4, 1000));
//        $packer->addBox(new TestBox('Le grande box', 3000, 3000, 100, 100, 2960, 2960, 80, 10000));
        $packer->addItem(new TestItem('Item 1', 1, 1, 1, 100, false));
        $packer->addItem(new TestItem('Item 2', 1, 1, 1, 100, false));
        $packer->addItem(new TestItem('Item 3', 1, 1, 1, 100, false));
        $packer->addItem(new TestItem('Item 4', 1, 1, 1, 100, false));
        $packer->addItem(new TestItem('Item 5', 2, 2, 2, 100, false));
        $packer->addItem(new TestItem('Item 6', 2, 2, 2, 100, false));
        $packer->addItem(new TestItem('Item 7', 2, 2, 2, 100, false));
        $packer->addItem(new TestItem('Item 8', 2, 2, 2, 100, false));
        $packer->addItem(new TestItem('Item 9', 4, 4, 4, 100, false));
        $packedBoxes = $packer->pack();`

and the answer is: 
This box is a Box1, it is 2mm wide, 2mm long and 2mm high
The combined weight of this box and the items inside it is 400g
The items in this box are:
Item 3
Item 2
Item 1
Item 4

This box is a Box1, it is 2mm wide, 2mm long and 2mm high
The combined weight of this box and the items inside it is 100g
The items in this box are:
Item 5

This box is a Box1, it is 2mm wide, 2mm long and 2mm high
The combined weight of this box and the items inside it is 100g
The items in this box are:
Item 6

This box is a Box1, it is 2mm wide, 2mm long and 2mm high
The combined weight of this box and the items inside it is 100g
The items in this box are:
Item 7

This box is a Box1, it is 2mm wide, 2mm long and 2mm high
The combined weight of this box and the items inside it is 100g
The items in this box are:
Item 8

This box is a Box2, it is 4mm wide, 4mm long and 4mm high
The combined weight of this box and the items inside it is 100g
The items in this box are:
Item 9


why items 5-8 are not in the same box?

**Comment by dvdoug** [comment]
@ViktorKirjanov I've just committed a fix to master to make your example work better - I'll get it into a release in the next few days
