### ISSUE TITLE
Fatal error: Class 'TestBox' not found in

### ISSUE THREAD

**Issue by cerebrumgit** [dvdoug/BoxPacker#39]
Hello good afternoon

See what is happening error as images

![captura de tela de 2015-11-23 14 37 25](https://cloud.githubusercontent.com/assets/3661079/11342908/b382579a-91f0-11e5-85c9-06f506660f37.png)
![captura de tela de 2015-11-23 14 40 33](https://cloud.githubusercontent.com/assets/3661079/11342909/b389893e-91f0-11e5-8689-5ece504c64b8.png)
![captura de tela de 2015-11-23 14 40 37](https://cloud.githubusercontent.com/assets/3661079/11342910/b3923958-91f0-11e5-94ca-f1cf03b9ae8a.png)
![captura de tela de 2015-11-23 14 40 46](https://cloud.githubusercontent.com/assets/3661079/11342911/b3948c30-91f0-11e5-8ac9-e4e0bb9823c2.png)
![captura de tela de 2015-11-23 14 43 58](https://cloud.githubusercontent.com/assets/3661079/11342912/b39776a2-91f0-11e5-9b64-9fa5297eb16d.png)

**Comment by cerebrumgit** [comment]
I just saw the following post and solved the occurrence

https://github.com/dvdoug/BoxPacker/issues/38

**Comment by dvdoug** [comment]
OK, great
