### ISSUE TITLE
Full Example

### ISSUE THREAD

**Issue by sameh-serag** [dvdoug/BoxPacker#4]
Hello @dvdoug 
Could you please provide a full example including creating items and boxes implement the BoxPacker\Item and BoxPacker\Box interfaces. Because i already created those two classes but it's seems there is something missing. 
Thanks

**Comment by primefrance** [comment]
Hello @dvdoug
i am very interested in this project and I would like to try it.
I installed composer and phpunit but I did not understand how to start the test on my server.
can you help me?

thanks a lot
F

**Comment by basilfawlty** [comment]
Hi @dvdoug 
I am trying to implement for an ecommerce application
I have installed with composer inside a directory outside of public_html.

I have included all of your files into my webpage php script which is in the public_html folder, using the following code:

require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/autoload.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/Box.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/BoxList.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/Item.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/ItemList.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/PackedBox.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/PackedBoxList.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/Packer.php';

When I try to run using the example code in your Readme, the script fails as soon as it gets to "$packer = new Packer();" with error message:

Fatal error: Class 'Packer' not found 

If I add "namespace DVDoug\BoxPacker;" to the first line of the webpage php script I get a 500 server error but can't see what this error is.

Where am I going wrong here?

**Comment by HeijnMandarijn** [comment]
@sameh-serag Did you specify:
{
        "require": {
            "dvdoug/boxpacker": "~1.5"
        }
    }

in composer.json?

I had the same error, specified this (as suggested in the Installation section), and now get the following error:
 Problem 1
    - The requested package dvdoug/boxpacker No version set (parsed as 1.0.0) could not be found.

Once I figure out how to solve that I'll post the answer here.
