### ISSUE TITLE
about unit of measurement

### ISSUE THREAD

**Issue by cerebrumgit** [dvdoug/BoxPacker#40]
=======
en_US
=======

Hello good afternoon

I see that the example is being used as the unit of measurement mm if I will use as cm would cause a problem?

=======
pt_BR
=======

Ola Boa Tarde

Vejo que no exemplo está sendo usado a unidade de medida como milimetros, caso eu venha usar como centimetros acarretaria algum problema  ?

**Comment by dvdoug** [comment]
The code is unit-agnostic, so as long as you are consistent everything will be fine
