### ISSUE TITLE
Is something wrong with single-product packaging with multiple boxes

### ISSUE THREAD

**Issue by mumairdeveloper** [dvdoug/BoxPacker#417]
First of all your library is fantastic really for packaging solutions <3

**=========== Boxes ===========**

![boxes](https://user-images.githubusercontent.com/61349306/216350885-ec81beb3-38b8-419e-8b40-dac4a4a549c1.png)

Please take a look at the boxes with the attached screenshot.

**=========== Product ===========**
When I am passing the product with quantity 6
Product Weight: 32 lbs
Product Dimensions:
Length => 7 in
Width => 6 in
Height => 4 in
Product Quantity: 6

**=========== Your results ===========**
Your packaging results in 2 boxes by the name "box2" and packed 
Package 1: 25 X 25 X 25 has 98 weight
Package 2: 25 X 25 X 25 has 98 weight 

**=========== Correct results ===========**
Even it should be: 
4 product pieces should go to box2 and 2 product pieces should go to box1 

**Note!** The rotation flag always selected Rotation::BestFit (6) for products

**Comment by mumairdeveloper** [comment]
Hi,

Any update, please?

Let me know if you need a proper request.

Thanks & Regards
-Umair

**Comment by dvdoug** [comment]
Hi @mumairdeveloper 

You're seeing https://boxpacker.io/en/stable/weight-distribution.html - to turn it off, call `$packer->setMaxBoxesToBalanceWeight(0)` and you'll see 4 + 2 rather than 3 +3

**Comment by mumairdeveloper** [comment]
Hi @dvdoug 

Fantastic, I got it.

What you will suggest I can use this flag for all large and small products, it will work properly?

Thank you

**Comment by dvdoug** [comment]
Yes, if that's the effect you want

**Comment by mumairdeveloper** [comment]
Thank you so much for cooperating.
