### ISSUE TITLE
how to set an item to be packed in a separate package ?

### ISSUE THREAD

**Issue by cerebrumgit** [dvdoug/BoxPacker#43]
Hello, good morning

I wonder how to set an item to be packed in a separate package?

**Comment by dvdoug** [comment]
You would have to have to call the library a second time with a different ItemList e.g.

$inStockPacker = new Packer(...);
...
$outOfStockPacker = new Packer(...);

**Comment by cerebrumgit** [comment]
Hello .. Good evening

Thank you my friend, you saved me

Congratulations for your project, it really is a fantastic project
