### ISSUE TITLE
Hi, where is the TestBox and TestItem class?

### ISSUE THREAD

**Issue by Jokewd** [dvdoug/BoxPacker#44]
Hello, I downloaded your library now, but when I try to run your examples (README.md), I get the message that TestBox and TestItem classes were not found.

So I implemented them, but even so, there are methods in ItemList and BoxList classes that do not exist, for example, $box->insert().

Can you share all the files to help me?

**Comment by dvdoug** [comment]
Hi

The test implementations of `TestBox` and `TestItem` are in https://github.com/dvdoug/BoxPacker/blob/master/tests/bootstrap.php .

The `insert()` method on a BoxList and ItemList are actually built into PHP - see http://php.net/manual/en/splheap.insert.php

Hope that helps?
Doug
