### ISSUE TITLE
Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by Jaimesg** [dvdoug/BoxPacker#45]
Hi thanks for this awesome library. I'm trying to make it work accessing to: tests/PackerTest.php
But i get the following error:

**Fatal error:** Class 'PHPUnit_Framework_TestCase' not found in ***/boxpacker/tests/PackerTest.php on line **11**

Seems that I don't have the Class PHPUnit_Framework_TestCase but I'm using PHP 5.4, any suggestions?
Thanks

**Comment by Jaimesg** [comment]
I've edited the line 11: class PackerTest //extends \PHPUnit_Framework_TestCase
Removing the class extension but there is no output, just a blank page. What can it be?

**Comment by dvdoug** [comment]
Have you run a `composer install`? You can then run the tests by doing `vendor/bin/phpunit` from the project root

**Comment by Jaimesg** [comment]
Sorry I don't, Is there any way to run it without the composer?

**Comment by HeijnMandarijn** [comment]
@Jaimesg You could simply install composer https://getcomposer.org/download/, then navigate to the boxpacker file directory via a command prompt (CMD) and execute 'composer install'. Then you can do exactly what dvdoug suggested

@dvdoug Also, nice work Doug and thanks for sharing! I was looking for a simple 3D bin packing algo like this for a while and finally found one thanks to you! I think it's going to be very useful as a basis for a little side project I'm working on in C++ :)

**Comment by dvdoug** [comment]
@Jaimesg I highly recommend an autoloader - composer provides this for free alongside many other benefits. If you don't want to use one, you'll need to modify `tests/bootstrap.php` to include a `require_once` statement for each .php file in the project and then use a standalone copy of PHPUnit from from https://phpunit.de.

**Comment by dvdoug** [comment]
No update since Feb - assuming this worked for you.
