### ISSUE TITLE
Optimize box suggestion by box cost?

### ISSUE THREAD

**Issue by dvadri** [dvdoug/BoxPacker#458]
Look at this API: https://www.3dbinpacking.com/en/customer/product/pack-a-shipment/calculations
It allow you to optimize by box cost. Does this feature already exist on dvdoug/BoxPacker ??? If so, where is it? Can someone show me in details.? Thank you.

**Comment by dvdoug** [comment]
Hi @dvadri 

You'll need to write the code yourself to calculate the costs, but you can then hook that into BoxPacker via a custom sorter, see https://boxpacker.io/en/stable/sortation.html#choosing-between-permutations
