### ISSUE TITLE
PHPUnit error: Interface not found

### ISSUE THREAD

**Issue by HeijnMandarijn** [dvdoug/BoxPacker#46]
Hey Doug,

First of all, I want to thank you for sharing your project! However, I've tried running the tests with composer but couldn't get it to work.

This is what I've done:

- Download the project folder
- (CMD) composer install
- (CMD) phpunit

This is the error I got at first:
Problem 1
    - The requested package dvdoug/boxpacker No version set (parsed as 1.0.0) could not be found.

This was solved by adding: 
`"dvdoug/boxpacker": "*"`
To:
`"require": {
            ...
        }`
in composer.json.

The error that followed was:
`PHP Fatal error:  Interface 'DVDoug\BoxPacker\Box' not found in C:\<mainFolder>\BoxPacker\tests\bootstrap.php on line 10`

`Fatal error: Interface 'DVDoug\BoxPacker\Box' not found in C:\<mainFolder>\BoxPacker\tests\bootstrap.php on line 10`

Do you have any idea what I could be doing wrong here?

Kind rgds,
Chris

**Comment by dvdoug** [comment]
I've just done the following on a Win10 box - can you explain where you've done anything different, and we'll try and figure this out.

* Downloaded PHP from php.net (I used 7.0.3, but it shouldn't matter)
* Extracted to c:\php
* Downloaded the latest composer from getcomposer.org. I used the Windows installer. It complained that php didn't have openssl enabled, so I went back and tweaked php.ini to enable it
* Downloaded a zip of latest master (I used Github's download Zip button)
* Extracted to c:\temp\boxpacker-master
* Opened a CMD window to c:\temp\boxpacker-master
* Executed `composer install`. It downloade Monolog and PHPUnit
* Ran `vendor\bin\phpunit`. The tests executed.

**Comment by HeijnMandarijn** [comment]
![scrn_01](https://cloud.githubusercontent.com/assets/3775039/13433159/ee8f3172-dfd0-11e5-8815-e19422f19831.png)

I've replicated your actions, but I'm still getting errors:
```
C:\xampp\htdocs\BoxPacker>vendor\bin\phpunit
PHP Fatal error:  Class PHPUnit_TextUI_ResultPrinter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PHPUnit_Framework_TestListener::addRiskyTest) in C:\xampp\php\pear\PHPUnit\TextUI\Re
sultPrinter.php on line 57

Fatal error: Class PHPUnit_TextUI_ResultPrinter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PHPUnit_Framework_TestListener::addRiskyTest) in C:\xampp\php\pear\PHPUnit\TextUI\ResultP
rinter.php on line 57
```

Instead of using the XAMPP php folder, I've tried downloading php7 separately, adding that folder to the path instead, and extracting the latest version of BoxPacker to c:\temp. However, the zip is missing a php.ini file and it gives me the complaint about the openssl file like you mentioned so I thought it was a dead end.

**Comment by dvdoug** [comment]
OK, so it seems that XAMPP is bundled with a really old version of PHPUnit (3.7.21) that's conflicting with the the version being installed by Composer (4.8) - as you can see it's trying to load PHPUnit files from inside the `c:\xampp` folder which seems weird. I assume it's something to do with the include path settings inside the XAMPP php.ini - I can't help you there.

With the pure-PHP install I explained, inside the `.zip` there is a file called `php.ini-development`. Rename that to `php.ini`, uncomment the line `extension_dir = "ext"` and `extension=php_openssl.dll`.

**Comment by HeijnMandarijn** [comment]
![image](https://cloud.githubusercontent.com/assets/3775039/13454159/84daa394-e055-11e5-9ef3-e9dfc8fd76b2.png)
Worked like a charm. Thanks Doug, you're great! ;)
