### ISSUE TITLE
Unexpected box packing result

### ISSUE THREAD

**Issue by jacksleight** [dvdoug/BoxPacker#465]
I've been testing out BoxPacker for a project I'm working on and it's already been fantastic, so thank you!

I just have a question regarding an unexpected result, basically this:

![Screenshot 2023-04-11 at 16 37 31](https://user-images.githubusercontent.com/126740/231216083-089502cc-e5ad-488f-8f9c-7328cfe728fa.png)

The last item should fit in the first box, but BoxPacker puts it in a new box. Is this expected due to how the algorithm works? No worries if so, I just wanted to check I'm not doing something wrong. 😅

I'm only packing in 2D as you can probably see, all depths are set to 1 and I'm not using weight at all.

**Comment by dvdoug** [comment]
Hi @jacksleight 

Happy to look at this, but I'll need to know the dimensions of your box and the items you're trying to pack to investigate

**Comment by dvdoug** [comment]
Thanks, I'll take a look
