### ISSUE TITLE
Its not compatible with php 8.1 version

### ISSUE THREAD

**Issue by Anantkprajapati** [dvdoug/BoxPacker#473]
Here is the error Own Box or Ship Separately Because Deprecated Functionality: Implicit conversion from float 5.125 to int loses precision in /vendor/dvdoug/boxpacker/tests/Test/TestBox.php on line 65

Is there any patch to fix this?

**Comment by Tomsgu** [comment]
Are you trying to pass float values to the TestBox?

**Comment by Anantkprajapati** [comment]
yes @Tomsgu - I have checked on TestBox Class and its uses on int value.

**Comment by Tomsgu** [comment]
For more details see https://github.com/dvdoug/BoxPacker/issues/273#issuecomment-1053574952

**Comment by dvdoug** [comment]
As @Tomsgu mentions, this will need to be a patch in your code - those arguments are typed as integers so passing floats into them may have "worked" previously, but PHP will always have been silently truncating them - your `5.125` is received by the library as simply `5`, PHP8.1 simply makes this more obvious.
