### ISSUE TITLE
laravel 5.2

### ISSUE THREAD

**Issue by alko79** [dvdoug/BoxPacker#49]
I used composer, all seems correctly installed.
but even when running phpunit i got error about:
"Fatal error: Interface 'DVDoug\BoxPacker\Box' not found "
I installed BoxPacker on a vanilla fresh laravel 5.2 installation.

**Comment by alko79** [comment]
reading closed issues i found interesting issue  "Can't get it to work #38 ".
solution there is:
require_once $_SERVER['DOCUMENT_ROOT'] . '/../composer/vendor/dvdoug/boxpacker/tests/bootstrap.php';
and calling then 
$packer = new DVDoug\BoxPacker\Packer();

how to translate this in laravel? 
I would like to use that as intented also "$packer = new Packer();"

my feeling is that something is missing from laravel side, could you investigate, maybe solution is trivial but I can't see.
:)

**Comment by dvdoug** [comment]
Hello

I'm not that familiar with Laravel - could you give me a step by step on your you installed both it and BoxPacker and I'll try and reproduce and see if I can spot anything.

Thanks,
Doug

**Comment by alko79** [comment]
thanks for reply,

just go in your htdocs  folder,
run:
composer create-project --prefer-dist laravel/laravel TESTPACKER

this will create laravel scaffold into folder TESTPACKER

then enter  TESTPACKER folder and add your package to the composer.json file, exactly like you instructed.

then run composer update and then dumpautoload to be sure the autolad is reloaded.

you will find your package into folder vendor.

if you check  /vendor/composer/autoload_psr4.php:

'DVDoug\\BoxPacker\\' => array($vendorDir . '/dvdoug/boxpacker'),

and  check also  /vendor/composer/autoload_classmap.php:

    'DVDoug\\BoxPacker\\Box' => $vendorDir . '/dvdoug/boxpacker/Box.php',
    'DVDoug\\BoxPacker\\BoxList' => $vendorDir . '/dvdoug/boxpacker/BoxList.php',
    'DVDoug\\BoxPacker\\BoxListTest' => $vendorDir . '/dvdoug/boxpacker/tests/BoxListTest.php',
    'DVDoug\\BoxPacker\\Item' => $vendorDir . '/dvdoug/boxpacker/Item.php',
    'DVDoug\\BoxPacker\\ItemList' => $vendorDir . '/dvdoug/boxpacker/ItemList.php',
    'DVDoug\\BoxPacker\\ItemListTest' => $vendorDir . '/dvdoug/boxpacker/tests/ItemListTest.php',
    'DVDoug\\BoxPacker\\PackedBox' => $vendorDir . '/dvdoug/boxpacker/PackedBox.php',
    'DVDoug\\BoxPacker\\PackedBoxList' => $vendorDir . '/dvdoug/boxpacker/PackedBoxList.php',
    'DVDoug\\BoxPacker\\Packer' => $vendorDir . '/dvdoug/boxpacker/Packer.php',
    'DVDoug\\BoxPacker\\PackerTest' => $vendorDir . '/dvdoug/boxpacker/tests/PackerTest.php',
    'DVDoug\\BoxPacker\\TestBox' => $vendorDir . '/dvdoug/boxpacker/tests/bootstrap.php',
    'DVDoug\\BoxPacker\\TestItem' => $vendorDir . '/dvdoug/boxpacker/tests/bootstrap.php',


so all seem in place here.

if you run phpunit it gives error.
if you try to create a controller into app folder and "use DVDoug\BoxPacker\Box"  to create a new Box for example it gives error ...

i was wandering these days that PSR4 examples I read got the source into "src" folder, that also could be a cause?Just asking.
I never wrote a package, not a "normal" not a "laravel one"...so really I'm reading whatever I find to get it works...but this also add confusion to confusion :)

the alternative I was thinking too is fork your code and build it around a laravel package base, but it seem I'm missing something trivial here, the 2 things should work togheter without any trouble, they are both so standard.

**Comment by dvdoug** [comment]
Does https://github.com/dvdoug/BoxPacker/commits/issue-49-example help for the unit tests? Note DVDoug\BoxPacker\Box is an interface, not a class so you'd need to create your own class that implements the required methods, similar to how the TestBox class does it.

http://php.net/manual/en/language.oop5.interfaces.php

**Comment by dvdoug** [comment]
Assuming this is now resolved
