### ISSUE TITLE
Step by Step use

### ISSUE THREAD

**Issue by haris989** [dvdoug/BoxPacker#51]
I spent an entire day to try to make it work but failed miserably. Can anyone tell me step by step how to use it. I need it urgently

**Comment by dvdoug** [comment]
There's an example of basic usage in the readme - it's basically impossible to diagnose your issue without further information - is there is a specific error? Are you trying to run the library standalone (e.g. make the unit tests work), or integrate with something else? 

http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
