### ISSUE TITLE
Dimensions of the used space

### ISSUE THREAD

**Issue by torava** [dvdoug/BoxPacker#52]
How can I get dimensions of the used space in a box? In my approach the container is only used to tell maximum dimensions. I want to know how much space the actual items are taking inside the container.

In the simple example below you can see that getRemainingLength() etc. functions are not helping in this case. The space items are taking in total is something like 15x13x16.  I want to get this information programmatically.

containers
100x50x50 0.814kg 1.2%
remaining 100x22x50
items
15x13x8 0.407kg 
15x13x8 0.407kg 

This is really important for me because I need to know the minimum container for items that I don't know beforehand. There is no functionality like in php-laff which allows to pack items without knowing the containers.

**Comment by dvdoug** [comment]
Hi

Currently the data isn't stored during the packing process to generate that kind of information. I'll keep this open as a feature request though.

**Comment by cornernote** [comment]
+1

**Comment by mgscreativa** [comment]
+1, that's exactly what I'm nedding right now! to calculate the box size needed to pack some cart products

**Comment by torava** [comment]
Thanks, works exactly as I needed, but when I tested it in many situations I happened to get zero height in one situation:
[boxpacker-zeroheight.txt](https://github.com/dvdoug/BoxPacker/files/874993/boxpacker-zeroheight.txt)

**Comment by dvdoug** [comment]
@torava That JSON doesn't appear to have the empty box dimensions so I can't construct a testcase. Happy to look into this once I can reproduce

**Comment by torava** [comment]
Test box outer dimensions are 100x50x50, inner dimensions are 90.9091x45.4545x45.4545 and max weight is 30 kg if those are what you were asking for.

**Comment by dvdoug** [comment]
v2.3.1 should fix this - please let me know if it doesn't!
