### ISSUE TITLE
Fatal error:  Uncaught Error: Call to undefined method DVDoug\BoxPacker\Packer::packIntoBox(

### ISSUE THREAD

**Issue by mozgbrasil** [dvdoug/BoxPacker#55]
Good afternoon

Hello my friend

When trying to play the integration example is being returned error

Fatal error:  Uncaught Error: Call to undefined method DVDoug\BoxPacker\Packer::packIntoBox(

I see that the "packIntoBox" does not belong to the class "Packer"

**Comment by dvdoug** [comment]
Ah, whoops that method was removed in v2. I'll update the instructions!

**Comment by mozgbrasil** [comment]
It is in error

It should be used

in

$volumePacker = new VolumePacker($box, $this->items);

use

$volumePacker = new VolumePacker($box, $items);
