### ISSUE TITLE
Composer Issues & Autoload Issues

### ISSUE THREAD

**Issue by Kracheads** [dvdoug/BoxPacker#56]
I've been experiences an odd issue in my Laravel Setup, I have added "dvdoug/boxpacker": "^2.0" to my composer.json, it installs fine but everytime I try to run the Packer I get the following error:

`local.ERROR: exception 'Symfony\\Component\\Debug\\Exception\\FatalErrorException' with message 'Class 'DVDoug\\BoxPacker\\TestBox' not found' in /Users/someone/Sites/nerd/rest/app/Http/Controllers/OrdersController.php:2846\nStack trace:\n#0 {main}  \n`

The code at that Errors Line Number is: 

`$_packer->addBox(
                                new TestBox(
                                    $_package->id,
                                    $_outerwidth,
                                    $_outlength,
                                    $_outerdepth,
                                    $_emptyweight,
                                    $_innerwidth,
                                    $_innerlength,
                                    $_innerdepth,
                                    $_maxweight
                                )
                            );`

But I have the following included in my controller:

```
use DVDoug\BoxPacker\Packer;
use DVDoug\BoxPacker\TestBox;
use DVDoug\BoxPacker\TestItem;
```

Now here is the part that is driving me crazy, this only happens when I run a composer update for anything at all, it's like I have to reinstall it everytime not sure why. The package goes missing again?

Any Suggestions?

**Comment by Kracheads** [comment]
To get the package to work again, I ran a composer remove dvdoug/boxpacker then rolled back from 2.0.2 to 2.0 with the command composer require dvdoug/boxpacker 2.0

The Packer now works again, but I'm not sure if the issue will return once I run a composer update. Still looking for any suggestions to my original question if anyone has any insight.

**Comment by dvdoug** [comment]
So you're using the implementation from the tests (TestBox) in your app directly? The diff between 2.0 and 2.0.2 is very small - the only thing I could possible be is https://github.com/dvdoug/BoxPacker/commit/fe5b4526ac01b2975ea72c8dd67c60a73ed41833 where the file that defines TestBox now pulls in the autoloader from Composer directly rather than assuming it was already loaded.

Can you try just removing that line manually and see if that fixes it for you? Also, worth checking - are you running the latest version of Composer? (run `composer self-update`)

**Comment by trsteel88** [comment]
We're having the same problem. @Kracheads did you figure it out?

**Comment by trsteel88** [comment]
@Kracheads @dvdoug I see the problem. You're not meant to use the classes inside /tests?

Probably needs to be made a bit clearer in the documentation. Or, those classes should be usable as a base.

**Comment by dvdoug** [comment]
No, the test suite shouldn't be considered part of the actual library code.

The readme states:

> BoxPacker is designed to integrate as seamlessly as possible into your existing systems. To use the library, you will need to implement the BoxPacker\Item interface on your item/product objects and BoxPacker\Box on the objects you use to to represent a box.


although if you think it could be made clearer I'm happy to accept suggestions for wording.
