### ISSUE TITLE
Slow with large quantities of items

### ISSUE THREAD

**Issue by JamesB7** [dvdoug/BoxPacker#58]
I'd like to use this box packer. However, it seems to always process boxes one at a time, even if I specify a quantity.

If I am shipping 5000 of something, for instance, it can take quite a long time to compute. It would be nice if the box packer recognized entire boxes that could be packed with (say) 100 of a single item, so that the remaining work would be fairly small for the odds and ends.

**Comment by dvdoug** [comment]
What are you shipping 5000 of on a regular basis? I would have thought anything like that would come pre-packed/sold in larger quantities, so you'd be doing e.g. 25x200 rather than 5000x1 but if your use-case is different it would be good to understand more about it

**Comment by JamesB7** [comment]
It's true, many of these are also available in packs of 800.

But, given that it's a web based pricing and shipping estimator, I don't 
want it to freeze up if they specify a high quantity for those that aren't.

Right now, I'm having it fallback above 250 items to a dumb 'total 
volume / volume of box' approach. This might work okay.

**Comment by dvdoug** [comment]
Would you be able to knock up a quick testcase showing the slowness you're seeing? (i.e. a typical large order with the potential boxes you're configuring it with). I've got a couple of potential ideas for smarter shortcuts but I'd like to know if they'd actually help your case out before I try them.
