### ISSUE TITLE
Constraints on items?

### ISSUE THREAD

**Issue by JamesB7** [dvdoug/BoxPacker#60]
Not sure if this would even be in the same scope of program, but one feature  that would be useful would be to express quantity limits for object classes. Lithium ion batteries cannot be shipped more than two to a package, but you could put other things in the package, for example.

**Comment by dvdoug** [comment]
Given the number of potential restrictions, I think this would need to be some kind of hook/extension/callback system rather than just limiting solely on quantity. The question is designing the right one.

I think it's a valid feature request so I'll give it some thought.
