### ISSUE TITLE
Flexible Size Packaging

### ISSUE THREAD

**Issue by elvispdosreis** [dvdoug/BoxPacker#62]
Had a situation in my box can be up to 1050x1050x1050 but the soman of the sides can not exceed 2000mm and 3000g.
In fact it would vary packages wrapped in craft paper, but have to respect those limits.
When to exceed create a new package

reference
https://www.correios.com.br/para-voce/precisa-de-ajuda/limites-de-dimensoes-e-de-peso

**Comment by dvdoug** [comment]
Hello

I'm not 100% sure what you're trying to do here - the assumption behind this library is that your warehouse would have certain sized empty boxes for shipping in stock already, and then the library would try to calculate how many (and which size) of those shipping boxes would be needed to fulfil a customer order.

It sounds like you might be trying to determine the size of shipping box "on demand"? That sort of functionality is out of scope for the library.

**Comment by elvispdosreis** [comment]
The company of the post office in Brazil has a limitation, the sum of the three sides of the box can not exceed the sum of 200, when this happens I have to go to the next box. 
width + height + length <= 2000

**Comment by dvdoug** [comment]
I'm not sure I understand what you're trying to do - don't the empty boxes you're purchasing to put your items into already comply with this limitation?

**Comment by dvdoug** [comment]
@elvispdosreis ?

**Comment by elvispdosreis** [comment]
I'll check the behavior in version 3, it's smarter

**Comment by dvdoug** [comment]
Assuming this is OK now. Please reopen if you still have any concerns
