### ISSUE TITLE
Rotación de los articulos

### ISSUE THREAD

**Issue by oscarjavierbernalguzman** [dvdoug/BoxPacker#63]
Cordial saludo.
Estoy usando la función  "To just see if a selection of items will fit into one specific box"

Quisiera saber si esta se encarga de rotar los items insertados de la mejor manera y como lo hace.
Si lo realiza por items?
Si lo realiza por presentación? (es decir todos los items que sean iguales).

Muchas gracias por sus respuestas.

**Comment by dvdoug** [comment]
Hello

The code tries the heaviest/largest items first, and for each item it rotates on the x and y axis (2 permutations/item). 3D rotation (x,y,z - 6 permutations/item) is an enhancement that will be coming in a future version.

Hope that helps?

**Comment by oscarjavierbernalguzman** [comment]
Excelente.
Muchas gracias por la información.
Estaré pendiente al lanzamiento de las actualizaciones, por ahora usaré lo que se proporciona.
