### ISSUE TITLE
Dimensions Remaining

### ISSUE THREAD

**Issue by elvispdosreis** [dvdoug/BoxPacker#64]
$box = new Box('Big Box', 105, 105, 105, 0.010, 104, 104, 104, 30);
$items = new \DVDoug\BoxPacker\ItemList();
$items->insert(new tem('Laser Printer', 30, 55, 52, 9, true));

DVDoug\BoxPacker\PackedBox Object
(
    [box:protected] => Reis\CorreiosSdk\Package\Box Object
        (
            [reference] => Big Box
            [outerWidth] => 105
            [outerLength] => 105
            [outerDepth] => 105
            [emptyWeight] => 0.01
            [innerWidth] => 104
            [innerLength] => 104
            [innerDepth] => 104
            [maxWeight] => 30
            [innerVolume] => 1124864
        )
    [items:protected] => DVDoug\BoxPacker\ItemList Object
        (
            [flags:SplHeap:private] => 0
            [isCorrupted:SplHeap:private] => 
            [heap:SplHeap:private] => Array
                (
                    [0] => Reis\CorreiosSdk\Package\Item Object
                        (
                            [description] => Laser Printer
                            [width] => 30
                            [length] => 55
                            [depth] => 52
                            [weight] => 9
                            [keepFlat] => 
                            [volume] => 85800
                        )
                )
        )
    [weight:protected] => 
    [remainingWidth:protected] => 104
    [remainingLength:protected] => 49
    [remainingDepth:protected] => 104
    [remainingWeight:protected] => 20.99
)

The remaining dimensions would be these the correct

 [remainingWidth:protected] => 74
 [remainingLength:protected] => 49
 [remainingDepth:protected] => 52
 [remainingWeight:protected] => 20.99

**Comment by dvdoug** [comment]
Does this diagram makes it clearer?

![untitled](https://cloud.githubusercontent.com/assets/1571110/21296825/5d319b70-c56c-11e6-893b-6b7167f4054f.png)
