### ISSUE TITLE
Exception 'RuntimeException' with message

### ISSUE THREAD

**Issue by FidoOndra** [dvdoug/BoxPacker#65]
Could you please help me. Below is a mistake.

Fatal error: Uncaught exception 'RuntimeException' with message 'Item Item 4 is too large to fit into any box' in /Applications/XAMPP/xamppfiles/htdocs/BoxPacker-master/Packer.php:150 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/BoxPacker-master/Packer.php(102): DVDoug\BoxPacker\Packer->doVolumePacking() #1 /Applications/XAMPP/xamppfiles/htdocs/BoxPacker-master/tests/bootstrap.php(189): DVDoug\BoxPacker\Packer->pack() #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/BoxPacker-master/Packer.php on line 150

`  $packer = new Packer();
  $packer->addBox(new TestBox('Le box', 203, 203, 203, 10, 200, 200, 200, 10000));
  $packer->addBox(new TestBox('Le grande box', 300, 300, 100, 100, 280, 280, 80, 10000));
  $packer->addItem(new TestItem('Item 1', 250, 250, 2, 200, true));
  $packer->addItem(new TestItem('Item 2', 250, 250, 2, 200, true));
  $packer->addItem(new TestItem('Item 3', 250, 250, 2, 200, true));
  $packer->addItem(new TestItem('Item 4', 250, 250, 800, 200, true));
  $packedBoxes = $packer->pack();

echo "<br>";
echo "<br>";
echo "<br>";
print_r($packedBoxes);

  echo("These items fitted into " . count($packedBoxes) . " box(es)" . PHP_EOL);
  foreach ($packedBoxes as $packedBox) {
    $boxType = $packedBox->getBox(); // your own box object, in this case TestBox
    echo("This box is a {$boxType->getReference()}, it is {$boxType->getOuterWidth()}mm wide, {$boxType->getOuterLength()}mm long and {$boxType->getOuterDepth()}mm high" . PHP_EOL);
    echo("The combined weight of this box and the items inside it is {$packedBox->getWeight()}g" . PHP_EOL);
    echo "<br>";
    echo("The items in this box are:" . PHP_EOL);
    echo "<br>";
    $itemsInTheBox = $packedBox->getItems();
    foreach ($itemsInTheBox as $item) { // your own item object, in this case TestItem
      echo($item->getDescription() . PHP_EOL);
      echo "<br>";
    }

    echo(PHP_EOL);
  }`

**Comment by dvdoug** [comment]
Item 4 is 800mm in depth. The container boxes have inner depths of 200 and 80 respectively. Therefore it doesn't fit :). Did you mean to use a depth of 80mm in your test?

**Comment by FidoOndra** [comment]
Hey, sorry for the delay in replying.
The error is fine, but I cant work with a fatal error.
I just need to report the error not stop with fatal error.

Thank you for your help.
Ondra

**Comment by lenar** [comment]
It's only fatal because you do not catch the ```\RuntimeException``` thrown when calling ```$packer->pack();```

**Comment by FidoOndra** [comment]
Thank you. I'm going to search for it.
