### ISSUE TITLE
BoxPacker cannot be used with Composer

### ISSUE THREAD

**Issue by mpathy** [dvdoug/BoxPacker#67]
When I install BoxPacker with Composer, it doesnt work.
Other packages work.

Error message
`Fatal error: Uncaught Error: Class 'Packer' not found in /var/www/html/path-to-project/boxpacker.php: 18 Stack trace: #0 {main} thrown in /var/www/html/path-to-project/boxpacker.php on line 18`

What is the reason?

**Comment by mitaichik** [comment]
I installed it throught composer 2 days ago and it work. I think that problem on your side.

**Comment by mpathy** [comment]
I did it on several systems, where each other composer package works..
Sure that all dependencies are installed? The test use much more for example

**Comment by dvdoug** [comment]
Did you include the appropriate namespace `use` statement(s)?
