### ISSUE TITLE
Method Parameters

### ISSUE THREAD

**Issue by darryljackman** [dvdoug/BoxPacker#69]
Cannot find any description of what parameters are what when creating boxes/items.

E.g.
$box = new TestBox('Le box', 300, 300, 10, 10, 296, 296, 8, 1000);

Can't find any way to know what any of these parameters are. Obviously Length, Width and Height are in there somewhere, but how can someone use this without know what parameters are what??

**Comment by dvdoug** [comment]
The library is intended by used by implementing the interfaces via your own objects, so the parameters used in the test examples aren't relevant to actual usage. But if you want to see them to experiment with they're defined in https://github.com/dvdoug/BoxPacker/blob/master/tests/bootstrap.php

**Comment by warmwhisky** [comment]
Hi,

I am trying to figure out what this means. Upon reading the docs, the example states that this is not real code.

I have installed and tried to run the example and as I would guess it doesnt work becuase it is not real code.

Do you have a working example?

Can you explain what is going on in each item in new TestBox('Le petite box', 300, 300, 10, 10, 296, 296, 8, 1000)?

In each case there are 9 entries starting with a label?

I thought maybe the first three numbers were length width height, then maybe weight? then it might be inner length, width, height and then volume? but that would just be a wild guess.
