### ISSUE TITLE
Add an optional item price

### ISSUE THREAD

**Issue by gui-gui** [dvdoug/BoxPacker#70]
Maybe it would be interesting to add an option to also pass the item price.
At the end of the sorting we would have the box total price that could be used for insurance quotes for instance.

**Comment by dvdoug** [comment]
Hello

This should in fact be possible for you to do right now - because you pass in items that implement the `Item` interface, these can in fact be your regular item objects - with access to e.g. your price info. You'll just need to loop over the items in each returned `PackedBox` and add them up

**Comment by gui-gui** [comment]
Thanks for the tip mate!

I'm a bit new to PHP and was overcomplicating my implementation. 
Just implemented it using the original item object. 
Fairly easy to get the box price now. 

Thanks

**Comment by dvdoug** [comment]
Excellent, glad to hear it. This library is a bit unusual with the interface thing, I think it's caught a few people out
