### ISSUE TITLE
ItemTooLargeException handling

### ISSUE THREAD

**Issue by Hammish** [dvdoug/BoxPacker#71]
The use case in question: I am working with a scenario where sometimes an item is too large to fit into a box. When that happens, it is shipped on its own without a box.

When Packer is told to pack something that can't fit in a box, it raises a ItemTooLargeException exception, which is good, except that that doesn't provide feedback on which item was too large, except for giving back a plain-text description in the exception message.

It would be better if I could get back which item it is. I hacked in a constructor to ItemTooLargeException to allow Packer to pass the actual item in addition to a message, so that I can then catch the exception and remove the offending item from the list that I'm passing to packer. This works for my purposes, but I thought I would pass along the feedback.

**Comment by dvdoug** [comment]
This is a good idea, I've implemented in v2.2.1. Thanks!
