### ISSUE TITLE
$stableOrientationsInEmptyBox used for?

### ISSUE THREAD

**Issue by fuzknutz** [dvdoug/BoxPacker#74]
I digged in your code and I saw $stableOrientationsInEmptyBox in VolumePacker->findBestOrientation()
didn't been used.

Sorry, if I missed anything.

**Comment by dvdoug** [comment]
Where possible, a stable orientation is wanted - however where there is no stable orientation possible at all (even when the box is empty), then the algorithm allows for an unstable one to be used. Does that explain?
