### ISSUE TITLE
I found dead area.

### ISSUE THREAD

**Issue by fuzknutz** [dvdoug/BoxPacker#75]
First, I try this probiem.
  $packer->addBox(new TestBox('CONTAINER (20 x 12 x 10)', 20, 12, 10, 0, 20, 12, 10, 2500));
  $packer->addItem(new TestItem('B (12 x 12 x 5)', 12, 12, 5, 8, FALSE),2);
  $packer->addItem(new TestItem('C (8 x 12 x 5)', 8, 12, 5, 8, FALSE),2);

Normally, It will really fit 100% 
But this project told it need to fit in 2 boxes. by last item C can't pack in it.

It doesn't make sense. so I dig in to your code. and I saw that in 
`$this->logger->debug("No more fit in lengthwise, resetting for new row");`
`$this->lengthLeft += $layerLength;`
`$this->widthLeft -= $layerWidth;`
`$layerWidth = $layerLength = 0;`
`$this->items->insert($itemToPack);`
`continue;`

This is what I think it will explain to you.
(https://cloud.githubusercontent.com/assets/24362057/24329031/7d3bcd0a-1224-11e7-996a-d847b92415ff.jpg)

Your project is very cool, I really like how you implement your code.
and I'm so sorry about annoy you, I would like to you to know that I include your project to my bachelor degree final project. So I need to know every single line of code that I use to explain for my professor :P.
Sorry for my English.

**Comment by dvdoug** [comment]
Fixed in v2.4.0
