### ISSUE TITLE
Function tryAndStackItemsIntoSpace

### ISSUE THREAD

**Issue by fuzknutz** [dvdoug/BoxPacker#76]
I don't understand I think this function can't used.
`$stackedItem = $this->findBestOrientation($this->items->top(), $prevItem, $nextItem, $maxWidth, $maxLength, $maxDepth);`

on this line I think `prevItem` and `nextItem` will always be same in every loop.
If this function work well. I think it should be complete my issue #75

**Comment by fuzknutz** [comment]
OK I think I dump now, XD
First I think this Function try to re-stack all packedItem.
So now I think I know that this function just be a quick add next item if it have almost or same width length depth.

If I correct I try to create this
  $packer->addBox(new TestBox('CONTAINER (20 x 12 x 10)', 20, 12, 10, 0, 20, 12, 10, 2500));
  $packer->addItem(new TestItem('B (12 x 12 x 1)', 12, 12, 1, 8, FALSE),10);
  $packer->addItem(new TestItem('C (8 x 12 x 5)', 8, 12, 5, 8, FALSE),2);

but it don't do this function every, why?

**Comment by victorhramos** [comment]
I guess your problem is about the inner dimensions of the box are the same as outter. In real world we doesnt have boxes like this.

**Comment by dvdoug** [comment]
Sorry, I don't think I understand the question. But #75 is fixed, so assuming this one is too?
