### ISSUE TITLE
How to get the item's position in the box

### ISSUE THREAD

**Issue by rsurfings** [dvdoug/BoxPacker#78]
for example:
$itemsInTheBox = $packedBox->getItems ();
foreach ( $itemsInTheBox as $item ) {

$itemPosition = $item->getPositionInBox();//Something like

}

**Comment by dvdoug** [comment]
In the currently released versions it's not - it will be possible in v3. Soon....

**Comment by aspiresupport** [comment]
Hi, is there a timeframe for version 3? Is there code available for this that I could look at and maybe contribute?

**Comment by dvdoug** [comment]
Hello

The code on the master branch is approximately what will be v3 - you can see how the positional info works at https://boxpacker.readthedocs.io/en/latest/whatsnew.html and https://boxpacker.readthedocs.io/en/latest/advanced-usage.html#positional-information.

Timeline wise, I'm mostly just waiting until PHP7.2 is released so I can verify compatibility and I also want to write up a few more pages of documentation.

**Comment by dvdoug** [comment]
v3 now released

**Comment by aspiresupport** [comment]
Thanks for letting me know.

I'll look into it.

--

Jon Horner

support@aspirecreative.co.uk ( support@aspirecreative.co.uk )

**Comment by RobinTail** [comment]
Is there any ability to use "Positional information" feature in v2 (without PHP7)? @dvdoug

**Comment by dvdoug** [comment]
5.4 is quite old now, there's no chance I could persuade you to upgrade? 😞
