### ISSUE TITLE
Incorrect Depth

### ISSUE THREAD

**Issue by serkozk** [dvdoug/BoxPacker#79]
I use the following code to get the combined package width, height and depth.

$packer = new Packer();
$packer->addBox(new TestBox('8x10', 100, 10, 10, 0, 100, 10, 10, 60));
$packer->addBox(new TestBox('Bundle', 75, 15, 15, 0, 75, 15, 15, 30));
$packer->addItem(new TestItem('Item 1', 14, 12, 2, 2, true));
$packer->addItem(new TestItem('Item 2', 14, 12, 2, 2, true));
$packer->addItem(new TestItem('Item 3', 14, 12, 2, 2, true));
$packer->addItem(new TestItem('Item 4', 14, 12, 2, 2, true));
$packer->addItem(new TestItem('Item 5', 14, 12, 2, 2, true));
$packedBoxes = $packer->pack();

echo("These items fitted into " . count($packedBoxes) . " box(es)" . PHP_EOL);
foreach ($packedBoxes as $packedBox) {
$boxType = $packedBox->getBox(); // your own box object, in this case TestBox
echo("{$boxType->getReference()} w: {$packedBox->getUsedWidth()} l: {$packedBox->getUsedLength()} d: {$packedBox->getUsedDepth()}" . PHP_EOL);
echo("The combined weight of this box and the items inside it is {$packedBox->getWeight()} lbs" . PHP_EOL);

echo("The items in this box are:" . PHP_EOL);
$itemsInTheBox = $packedBox->getItems();
foreach ($itemsInTheBox as $item) { // your own item object, in this case TestItem
  echo($item->getDescription() . PHP_EOL);
}

echo(PHP_EOL);
}

The result is correct except the dimension

These items fitted into 1 box(es)
Bundle w: 12 l: 14 d: 2
The combined weight of this box and the items inside it is 10 lbs
The items in this box are:

The correct usedDepth should be 10 in this scenario. Please advice.

**Comment by dvdoug** [comment]
Hello

I'll take a look this weekend - unfortunately I'm not likely to have time before then :(

**Comment by serkozk** [comment]
Thanks Doug,

At the end I am trying to get the combined package size not the box size.

Regards,
Serkan

**Comment by dvdoug** [comment]
Hello

So in this case, I believe the depth is correct - the items aren't being packed in a stack, but are all being placed side by side in a long line. As such, a depth of 2 appears correct. It's the /other/ numbers that look suspicious to me.

Investigating further...

**Comment by dvdoug** [comment]
Just wanted to say I haven't forgotten about this - I think I have a fix, but it's wrapped up in a slightly bigger bit of work that I'm still validating. Hoping to confirm it can applied soon

**Comment by serkozk** [comment]
Great thanks. If it works I am planning to implement this in a bigger project.

**Comment by dvdoug** [comment]
Fixed in v2.4.0
