### ISSUE TITLE
Box Packing PHP extension

### ISSUE THREAD

**Issue by corbinu** [dvdoug/BoxPacker#80]
@dvdoug 

I am currently looking to build my own box packer and am looking at yours as one of the prior arts to base it on. I was wondering if you would be interested if it could be implemented as a PHP extension as the core code will be in Rust. Would be happy to chat with you even just about box packing in general. Happy to chat here or via email or slack or something if your interested.

**Comment by dvdoug** [comment]
Ah Rust - interesting! TBH, I've not looked at the possibility of doing this as a PHP extension - I guess it would be possible to take advantage of parallelism that way which could be intriguing.

What's the focus you've got in mind for yours? Something that needs to run quickly like this one, or something that can run for longer and try more of a brute force approach to squeeze every last space out?

**Comment by corbinu** [comment]
@dvdoug the idea is to have a toggle based upon need for accuracy so base it on this one and and a few others like https://github.com/JamesBremner/Pack and just let people specify the algorithm they want.

**Comment by corbinu** [comment]
I am going to close this my intial effort to get the packer working with Neon hit some roadblocks. Then some new WASM features were added to Rust so I am compiling to that for now. May come back to other language support like PHP in the future however.
