### ISSUE TITLE
Mass Quantity Execution Time.

### ISSUE THREAD

**Issue by terryw3316** [dvdoug/BoxPacker#81]
Hey,

When using this, I am having some difficulty when the number of items needed to be packed are in the thousands (the time required for all calculations is timing out), even if its the same item and box type. Is there some kind of caching comparison that can check if the same item and box type have previously been packed and use the same solution instantly instead of going through all the calculations again?

Regards,

**Comment by dvdoug** [comment]
Hello

Firstly, do you have xdebug turned on? That has a huge performance impact, so please try disabling that if you do.

Secondly, would you be able to supply a scenario/testcase (doesn't have to be PHPUnit) for your usecase (e.g. typical item set and the potential boxes you're configuring it with)? Happy to take a look, but the performance characteristics (e.g. hotspots) will vary quite a lot for different scenarios so I'd like to profile something representative of what you're seeing.

**Comment by terryw3316** [comment]
Hey,

xdebug is not on, no. 

I will get you some test cases together by Monday, we have some live examples so ill use those when I am able to access the data again (currently unable).

Thanks :)

Regards,

**Comment by dvdoug** [comment]
Gentle poke about a testcase? :)

**Comment by terryw3316** [comment]
Hey Man,

REALLY sorry about not getting back to you sooner... I'm really struggling for time right now, we've done some internal changes to compensate for the issue right now, so It is cool if you close this issue for now, I can come back to you when I have a bit more time in the future.

As a quick example the high volume was related to items being introduced at roughly 1mm thick and thousands being ordered at a time, since each 1mm items was having its orientation checked it was really overloading the whole thing. 

Once again sorry about the delay.

Regards,

**Comment by dvdoug** [comment]
Not sure if it helps your particular situation @terryw3316, but I've recently added a way to tune the weight distribution repack and turn it off - see http://www.boxpacker.io/en/stable/weight-distribution.html

I'm going to close this for now, but if you do ever have a testcase for your usage please feel free to reopen and I'd be happy to take a look.
