### ISSUE TITLE
[Question] How do I add multiple quantities of one item properly?

### ISSUE THREAD

**Issue by amirshawn** [dvdoug/BoxPacker#82]
Hi,

I'm testing this out to use in an e-commerce site.  We deal with fractional quantities since we sell items by weight.  I'm wondering if you have some advice on how to insert multiples of one item?  I worry that if a customer orders 20 of one item and I multiply the width by 20, it may not fit in one of our boxes.  I'm also not sure how to properly insert all the boxes.  I created a database table for the boxes and created a few boxes.  Do I have to loop them all and run the addBox function every time I need a calculation?
Thank you very much for your help and this package!

**Comment by dvdoug** [comment]
Hi

Yes - to add the boxes, you'll need to loop through. If you've got a suggestion for a better way please do feel free to suggest it.

Selling by weight is not something I've ever needed to consider for this library - that's a tricky one! What's the item if you don't mind me asking?

**Comment by amirshawn** [comment]
We sell glass blowing supplies, so the product is glass color rods and tubing.  It would be nice if the boxes object could be stored in cache and reused until a new box size is added.

**Comment by dvdoug** [comment]
Ah - if was something like cheese, then I'd have suggested trying something along the lines of making it cube-shaped (not sure if that's optimal or not).

I don't actually have an idea for your case - other than dividing into a standard unit and so if a customer orders 20, pack "20" items. Depends on the logistics side of your business. Sorry that's not helpful

**Comment by dvdoug** [comment]
Regarding caching boxes - if you're doing repeated packings in the same code execution, then you could call `setItems()` rather than `addItems()` on each iteration - that would effectively reset the state.

**Comment by amirshawn** [comment]
I was just thinking, an improvement to this packer could be the possibility of adding the value of items being packed into the box.  That would help with figuring out insurance and duty costs.  Maybe a custom fields array that could be attached to each item instead of just the title.

**Comment by amirshawn** [comment]
I just updated to the new version when running composer update.  It made me update to PHP 7.1 which was a process.  Anyways, after the update I'm getting this error:
Declaration of App\Product::getDescription() must be compatible with DVDoug\BoxPacker\Item::getDescription(): string

Not sure what changed that's causing this.

**Comment by dvdoug** [comment]
Looks like you've updated to master - that will be 7.1+ when I release v3 - the current stable v2.4.0 still supports PHP5, I plan on supporting that alongside the eventual v3 for quite some time.

I recommend downgrading back to the stable version for now as I am doing some API changes for v3 - if you want to keep on the version you updated to, you'll need to add the return types from the interface to your implementation e.g `getDescription()` changes to `getDescription(): string`.

**Comment by dvdoug** [comment]
Regarding value etc - that should be available already - your original `App\Product` will be what's packed into the box so when you loop over what's in it you'll get your own objects back

**Comment by dvdoug** [comment]
Assuming this is answered now - please reopen if not
