### ISSUE TITLE
how can i ingore box's max weight

### ISSUE THREAD

**Issue by zjfaker** [dvdoug/BoxPacker#83]
hello
How can i ingore box's max weight

**Comment by dvdoug** [comment]
Hi

Not sure why you'd want to do that (boxes do have max weights before they break, couriers have max weights too for H&S reasons), but you could set the individual item weights to 0 and/or set the max weight of the box to PHP_INT_MAX. Either of those I should work I think.

Hope that helps?

**Comment by zjfaker** [comment]
That's a good idea! thanks very much
