### ISSUE TITLE
Negative Remaining Width

### ISSUE THREAD

**Issue by Gabriel-aa** [dvdoug/BoxPacker#86]
Some tests are returning usedWidth bigger then the box outerWidth. Am I doing something wrong?

PackedBoxList {#707
  #meanWeight: null
  heap: array:1 [
    0 => PackedBox {#763
      #box: TestBox {#714
        +"reference": "Box 9"
        +"outerWidth": 22.5
        +"outerLength": 27.0
        +"outerDepth": 13.5
        +"emptyWeight": 0.2
        +"innerWidth": 22.5
        +"innerLength": 27.0
        +"innerDepth": 13.5
        +"maxWeight": 30
        +"innerVolume": 8201.25
      }
      #items: ItemList {#754
        heap: array:10 [
          9 => TestItem {#691
            +"description": 48
            +"width": 11.2
            +"length": 22.2
            +"depth": 2.2
            +"weight": 0.075
            +"keepFlat": true
            +"volume": 547.008
          }
          8 => TestItem {#700
            +"description": 48
            +"width": 11.2
            +"length": 22.2
            +"depth": 2.2
            +"weight": 0.075
            +"keepFlat": true
            +"volume": 547.008
          }
          7 => TestItem {#662
            +"description": 48
            +"width": 11.2
            +"length": 22.2
            +"depth": 2.2
            +"weight": 0.075
            +"keepFlat": true
            +"volume": 547.008
          }
          6 => TestItem {#698
            +"description": 58
            +"width": 10.8
            +"length": 21.5
            +"depth": 2.0
            +"weight": 0.102
            +"keepFlat": true
            +"volume": 464.4
          }
          5 => TestItem {#701
            +"description": 58
            +"width": 10.8
            +"length": 21.5
            +"depth": 2.0
            +"weight": 0.102
            +"keepFlat": true
            +"volume": 464.4
          }
          4 => TestItem {#693
            +"description": 58
            +"width": 10.8
            +"length": 21.5
            +"depth": 2.0
            +"weight": 0.102
            +"keepFlat": true
            +"volume": 464.4
          }
          3 => TestItem {#697
            +"description": 58
            +"width": 10.8
            +"length": 21.5
            +"depth": 2.0
            +"weight": 0.102
            +"keepFlat": true
            +"volume": 464.4
          }
          2 => TestItem {#702
            +"description": 61
            +"width": 6.2
            +"length": 17.0
            +"depth": 1.8
            +"weight": 0.03
            +"keepFlat": true
            +"volume": 189.72
          }
          1 => TestItem {#703
            +"description": 61
            +"width": 6.2
            +"length": 17.0
            +"depth": 1.8
            +"weight": 0.03
            +"keepFlat": true
            +"volume": 189.72
          }
          0 => TestItem {#704
            +"description": 61
            +"width": 6.2
            +"length": 17.0
            +"depth": 1.8
            +"weight": 0.03
            +"keepFlat": true
            +"volume": 189.72
          }
        ]
      }
      #weight: null
      #remainingWidth: -0.7
      #remainingLength: 4.8
      #remainingDepth: 3.3
      #remainingWeight: 29.077
      #usedWidth: 23.2
      #usedLength: 22.2
      #usedDepth: 10.2
    }
  ]
}

**Comment by dvdoug** [comment]
Thanks for the bug report - the issue was that for the purposes of the algorithm the box width is defined as the longest side, and the length as the shortest which is the opposite way around to the dimensions in your example.

However when calculating the remaining space after packing, it didn't rotate everything back to the original frame of reference.

I'll be tagging a new version with the fix shortly.
