### ISSUE TITLE
Flat items in a box should fit easily

### ISSUE THREAD

**Issue by matt-usurp** [dvdoug/BoxPacker#89]
I have been using this project as a kind of cheat to work out how many sheets of paper I can fit on another sheet of paper. Its been working perfectly so far, I implemented a `Box` model for my master sheet, then an `Item` for the size to fit on it. To work out how many I would run this in a loop util the box count increased past `1`, then it was the amount last tried minus `1` giving me my final count. I know it sounds like it might be inefficient but the amount of sizes on a sheet is rarely above 10 so the operation is fast, plus its ran on a worker anyway.

Now I have a series of test cases running against the class to make sure the logic is sound, recently we came across a case that doesn't work but should.

`100x100 on 100x100 = 1 (correct)`
`100x50  on 100x100 = 2 (correct)`
`50x100  on 100x100 = 2 (correct)`
`148x210 on 450x320 = 3 (expected 4)`

As you can see a real world example (in our case `SRA3 (450x320)`) should be able to fit 4 of the defined size (`A5 (148x210)`) but doesn't. Now I assumed this was down to the distribution so I ended up stripping the code down to the point where it now only uses `VolumePacker` directly.

Expected that you can fit `2x2 (A5)` in the box. That is `296x420` should fit easily in the box when rotated `320x450`. Any ideas?

```php
$sheet = new BoxImpositionModel('sheet', $parent);
$size = new ItemImpositionModel('size', $child);

$count = 0;
$list = new ItemList();

while ($count < self::RECURSION_LIMIT) { // 50
    ++$count;

    //  Insert a new size for this iteration.
    $list->insert($size);

    $packer = new VolumePacker($sheet, clone $list);
    $packed = $packer->pack()->getItems()->count();

    if ($packed !== $count) {
        --$count;
        break;
    }
}

return $count;
```

Note that the imposition models simply return the size `width` for the width methods and `height` is used as the length methods. The outer and inner methods both return the same values, I am not sure if this will cause an issue in the long run.

**Comment by dvdoug** [comment]
Hello

Can I check what version you're using? The following testcase seems to work OK for me

```
    public function testIssue89()
    {
        $packer = new Packer();
        $packer->addBox(new TestBox('A3 Sheet', 450, 320, 1, 0, 450, 320, 1, 0));
        $packer->addItem(new TestItem('A5 Sheet', 296, 420, 0, 0, true), 4);
        $packedBoxes = $packer->pack();

        self::assertEquals(1, $packedBoxes->count());
    }
```

**Comment by dvdoug** [comment]
Actually, hang on - that only worked because I gave it 0 depth. I can reproduce with a depth of 1

**Comment by matt-usurp** [comment]
I was running version `2` and I hoped that upgrading to `3` could fix it. But as you said you can replicate it. Is setting the depth to `0` something that should be possible?

**Comment by dvdoug** [comment]
0 would allow for infinite stacking so it's not advised :)

It will probably be this weekend before I have time to look at this properly

**Comment by matt-usurp** [comment]
Thanks for taking a look at this 👍
