### ISSUE TITLE
Better handling of items too big

### ISSUE THREAD

**Issue by sjelfull** [dvdoug/BoxPacker#94]
Similar to issue #71, I want to support just shipping too large items as their own package.

In the context of a shopping cart, users can add one or more items that can be too large.

Since BoxPacker throws an exception when it hits a item too large, this makes it hard to just do the following:
- Pack up all items that fit within the predefined box(es)
- Get a list of the x item(s) that is too large, and handle them some other way, i.e. pack them up.

Is it possible to make the exception optional, and add some methods to easily separate the too-large items from the ones that fit?

The only alternative I currently see is to `->pack()` the items up, catch any exceptions, get the item, move it into a separate list, and repeat until there is no exceptions.

**Comment by dvdoug** [comment]
Hello

I'd like to understand this use case a little better - do you often have items that are too large for a box?

My assumption is that in normal circumstances you do have the required boxes - any item that requires special handling/shipping would be flagged as such in the DB and would thus be separated out into a different flow that didn't involve the packer. Anything that is too large would therefore be "wrong" and would need investigation.

Do you have a different way of working e.g. often just putting a label on an item and shipping as-is?

**Comment by sjelfull** [comment]
I probably should give you some more context of what i'm trying to build.

Essential i'm creating a shipping calculation plugin for a e-commerce platform, that integrates with Bring (Norway's equivalent of Royal Mail).

Any store can install this plugin, and I can't predict what type of products they will be selling.

The way the plugin works, is that you predefine boxes, and it then packs the products with your package.

However, I would like to add an option that allow the store owner to pack any items that does not fit into the predefined boxes. I don't imagine this being set on a per-product basis.

The way I see it, the customer should _never_ get any errors, which means the exception is useless except for logging purposes.

This would allow a store owner to do what you suggested, e.g. just slap a label on the item.

By the way, this is what i'm currently doing to circumvent this limitation:

```
do {
            try {
                $packer->setItems($items);

                $packedBoxes = $packer->pack();
                $finalized   = true;
            }
            catch (ItemTooLargeException $e) {
                $largeItem           = $e->getItem();
                $id                  = $largeItem->getId();
                $toLargeItems[ $id ] = $largeItem;

                unset($items[ $id ]);
            }
        } while (!$finalized); 
```
